// ══════════════════════════════════════════════════════════════════
//  CODE GENERATION
// ══════════════════════════════════════════════════════════════════
//  Turns a drawn machine into source you can run, a statechart config
//  you can hand to a runtime, or a test suite you can drop into a
//  project.
//
//  Scope is deliberate. Generating a recogniser is only worth doing if
//  the generated thing decides the same language the canvas does, so
//  these emitters cover exactly the models whose runtime semantics
//  translate faithfully to a few dozen lines of host code:
//
//    DFA            deterministic walk over a transition table
//    NFA, ε-NFA     subset simulation with an ε-closure
//    Moore, Mealy   deterministic walk that emits output
//
//  Stack and tape machines are refused rather than approximated. A
//  "PDA in Python" that silently drops nondeterminism, or a TM whose
//  generated tape is finite, is worse than no output at all — it looks
//  authoritative and is wrong. codegenSupport() is the single place
//  that decision lives, and every emitter routes through it.
//
//  ── styles ───────────────────────────────────────────────────────
//  The same machine emits in three shapes, because the shape that is
//  useful depends on what the code is for:
//
//    table   δ as a data literal, walked by a loop. Compact, and the
//            structure stays visible — the transition function reads
//            back off the page. Best when the machine may be edited.
//
//    switch  no data structure at all; δ becomes nested control flow.
//            This is what a person writes by hand in embedded C or a
//            hot loop, and what a reviewer can follow without holding
//            a table in their head.
//
//    class   an object with the state as a field: reset(), step(), and
//            isAccepting(). The other two consume a whole string; this
//            one accepts input incrementally, which is what a stream,
//            a parser, or a UI driving one symbol per event needs.
//            (C has no classes, so it gets the honest analogue: an
//            opaque struct plus functions taking a pointer to it.)
//
//  Style changes the shape, never the language decided. The generated
//  recogniser is differential-tested against the app's own simulator
//  for every style.
// ══════════════════════════════════════════════════════════════════

const CODEGEN_MODELS = new Set(['DFA', 'NFA', 'ε-NFA', 'Moore', 'Mealy']);
const CODEGEN_STYLES = ['table', 'switch', 'class'];

function codegenStyle(opts) {
  const s = opts && opts.style;
  return CODEGEN_STYLES.includes(s) ? s : 'table';
}

function codegenSupport(ir) {
  if (!ir.states.length) return { ok: false, reason: 'The canvas is empty.' };
  if (!ir.startId) return { ok: false, reason: 'This machine has no start state.' };
  if (!CODEGEN_MODELS.has(ir.machine)) {
    return {
      ok: false,
      reason: `Code generation covers DFA, NFA, ε-NFA, Moore and Mealy machines. `
        + `${ir.machineLabel} needs a stack or a tape, and a generated recogniser that quietly `
        + `dropped either would decide a different language than the one on the canvas.`
    };
  }
  return { ok: true };
}

function codegenIsTransducer(ir) { return ir.machine === 'Moore' || ir.machine === 'Mealy'; }
function codegenIsNondeterministic(ir) { return ir.machine === 'NFA' || ir.machine === 'ε-NFA'; }

// ── shared shaping ────────────────────────────────────────────────
// δ as name → symbol → [target names]. Built once; every language
// emitter walks this rather than the transition array.
function codegenDelta(ir, names) {
  const delta = new Map();
  ir.states.forEach(s => delta.set(names.get(s.id), new Map()));
  ir.transitions.forEach(t => {
    const row = delta.get(names.get(t.from));
    if (!row) return;
    if (!row.has(t.symbol)) row.set(t.symbol, []);
    const dest = names.get(t.to);
    // Mealy carries the emitted symbol on the edge, so the row holds a
    // pair rather than a bare target.
    row.get(t.symbol).push(ir.machine === 'Mealy'
      ? { to: dest, out: t.output == null ? '' : t.output }
      : dest);
  });
  return delta;
}

function codegenNames(ir) {
  return exportUniqueIdents(ir.states, s => s);
}

const CODEGEN_STYLE_NOTE = {
  table: 'δ is a data literal walked by a loop.',
  switch: 'δ is control flow — no transition table.',
  class: 'Stateful object: reset() / step() / isAccepting(), for incremental input.'
};

function codegenBanner(ir, prefix, opts) {
  const lines = [
    `Generated by Automata Playground from a ${ir.machineLabel}.`,
    `States: ${ir.states.length} · Σ = {${ir.sigma.join(', ')}}`,
    ir.isSymbolic
      ? 'Input is read one character at a time.'
      : 'Σ contains multi-character symbols — input is split on whitespace.'
  ];
  if (opts && opts.style) lines.push(CODEGEN_STYLE_NOTE[codegenStyle(opts)]);
  if (opts && opts.extraNote) lines.push(opts.extraNote);
  return lines.map(l => `${prefix} ${l}`).join('\n');
}

// Rows of δ for one state, as [symbol, destinations] pairs — the shape
// the switch emitters walk when writing nested cases.
function codegenRowsFor(delta, stateName) {
  const row = delta.get(stateName);
  return row ? [...row.entries()] : [];
}

// ε-targets for one state, used by the nondeterministic switch emitters
// where the closure cannot read a table.
function codegenEpsTargets(delta, stateName, eps) {
  const row = delta.get(stateName);
  const hit = row && row.get(eps);
  return hit ? hit.slice() : [];
}

function codegenUnsupported(reason, prefix) {
  return `${prefix} Cannot generate code for this machine.\n${prefix}\n`
    + reason.replace(/(.{1,68})(\s|$)/g, (m, chunk) => `${prefix} ${chunk.trim()}\n`);
}

// ── string escaping, per host language ────────────────────────────
function jsStr(s) {
  return JSON.stringify(String(s == null ? '' : s));
}
function pyStr(s) {
  return "'" + String(s == null ? '' : s)
    .replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n') + "'";
}
function javaStr(s) {
  return '"' + String(s == null ? '' : s)
    .replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n') + '"';
}
function xmlAttr(s) {
  return String(s == null ? '' : s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&apos;');
}

// ══════════════════════════════════════════════════════════════════
//  JAVASCRIPT
// ══════════════════════════════════════════════════════════════════
function codegenJavaScript(ir, opts = {}) {
  const support = codegenSupport(ir);
  if (!support.ok) return codegenUnsupported(support.reason, '//');
  const style = codegenStyle(opts);
  if (style === 'switch') return codegenJsSwitch(ir, opts);
  if (style === 'class') return codegenJsClass(ir, opts);
  return codegenJsTable(ir, opts);
}

// The JS tokenizer, shared by all three styles.
function codegenJsTokenize(ir) {
  return [
    'function tokenize(input) {',
    ir.isSymbolic ? '  return Array.from(input);' : '  return input.split(/\\s+/).filter(Boolean);',
    '}'
  ];
}

function codegenJsTable(ir, opts = {}) {
  const names = codegenNames(ir);
  const delta = codegenDelta(ir, names);
  const start = names.get(ir.startId);
  const accepting = ir.states.filter(s => s.isAccept).map(s => names.get(s.id));
  const eps = ir.sym.eps;
  const nd = codegenIsNondeterministic(ir);

  const out = [];
  out.push(codegenBanner(ir, '//', { ...opts, style: 'table' }));
  out.push('');

  // δ literal
  out.push('const DELTA = {');
  [...delta.entries()].forEach(([from, row]) => {
    if (!row.size) { out.push(`  ${jsStr(from)}: {},`); return; }
    const cells = [...row.entries()].map(([sym, dests]) => {
      if (ir.machine === 'Mealy') {
        const d = dests[0];
        return `${jsStr(sym)}: { to: ${jsStr(d.to)}, out: ${jsStr(d.out)} }`;
      }
      return `${jsStr(sym)}: ${nd ? `[${dests.map(jsStr).join(', ')}]` : jsStr(dests[0])}`;
    });
    out.push(`  ${jsStr(from)}: { ${cells.join(', ')} },`);
  });
  out.push('};');
  out.push('');
  out.push(`const START = ${jsStr(start)};`);
  if (!codegenIsTransducer(ir)) {
    out.push(`const ACCEPTING = new Set([${accepting.map(jsStr).join(', ')}]);`);
  }
  if (ir.machine === 'Moore') {
    const outputs = ir.states.map(s => `  ${jsStr(names.get(s.id))}: ${jsStr(s.output == null ? '' : s.output)},`);
    out.push('');
    out.push('// Moore output is a property of the state, not the edge.');
    out.push('const OUTPUT = {');
    outputs.forEach(l => out.push(l));
    out.push('};');
  }
  out.push('');
  codegenJsTokenize(ir).forEach(l => out.push(l));
  out.push('');

  if (nd) {
    out.push(`const EPSILON = ${jsStr(eps)};`);
    out.push('');
    out.push('function epsilonClosure(states) {');
    out.push('  const seen = new Set(states);');
    out.push('  const stack = [...states];');
    out.push('  while (stack.length) {');
    out.push('    const s = stack.pop();');
    out.push('    for (const t of (DELTA[s]?.[EPSILON] ?? [])) {');
    out.push('      if (!seen.has(t)) { seen.add(t); stack.push(t); }');
    out.push('    }');
    out.push('  }');
    out.push('  return seen;');
    out.push('}');
    out.push('');
    out.push('function accepts(input) {');
    out.push('  let current = epsilonClosure([START]);');
    out.push('  for (const symbol of tokenize(input)) {');
    out.push('    const next = new Set();');
    out.push('    for (const s of current) {');
    out.push('      for (const t of (DELTA[s]?.[symbol] ?? [])) next.add(t);');
    out.push('    }');
    out.push('    current = epsilonClosure(next);');
    out.push('    if (!current.size) return false;');
    out.push('  }');
    out.push('  for (const s of current) if (ACCEPTING.has(s)) return true;');
    out.push('  return false;');
    out.push('}');
  } else if (ir.machine === 'Mealy') {
    out.push('function transduce(input) {');
    out.push('  let state = START;');
    out.push('  const output = [];');
    out.push('  for (const symbol of tokenize(input)) {');
    out.push('    const edge = DELTA[state]?.[symbol];');
    out.push('    if (edge === undefined) return null; // undefined transition');
    out.push('    output.push(edge.out);');
    out.push('    state = edge.to;');
    out.push('  }');
    out.push(`  return output.join(${ir.isSymbolic ? "''" : "' '"});`);
    out.push('}');
  } else if (ir.machine === 'Moore') {
    out.push('function transduce(input) {');
    out.push('  let state = START;');
    out.push('  const output = [OUTPUT[state]];');
    out.push('  for (const symbol of tokenize(input)) {');
    out.push('    const next = DELTA[state]?.[symbol];');
    out.push('    if (next === undefined) return null; // undefined transition');
    out.push('    state = next;');
    out.push('    output.push(OUTPUT[state]);');
    out.push('  }');
    out.push(`  return output.join(${ir.isSymbolic ? "''" : "' '"});`);
    out.push('}');
  } else {
    out.push('function accepts(input) {');
    out.push('  let state = START;');
    out.push('  for (const symbol of tokenize(input)) {');
    out.push('    const next = DELTA[state]?.[symbol];');
    out.push('    if (next === undefined) return false; // dead: no such transition');
    out.push('    state = next;');
    out.push('  }');
    out.push('  return ACCEPTING.has(state);');
    out.push('}');
  }

  out.push('');
  const api = codegenIsTransducer(ir) ? 'transduce' : 'accepts';
  out.push(`if (typeof module !== 'undefined') module.exports = { ${api}, DELTA, START };`);
  return out.join('\n');
}

// ── JavaScript: switch ────────────────────────────────────────────
// δ becomes nested switches. Nothing is looked up; a reader follows the
// machine by reading, and a missing case is a visible `default` rather
// than an absent map key.
function codegenJsSwitch(ir, opts = {}) {
  const names = codegenNames(ir);
  const delta = codegenDelta(ir, names);
  const start = names.get(ir.startId);
  const eps = ir.sym.eps;
  const nd = codegenIsNondeterministic(ir);
  const order = ir.states.map(s => names.get(s.id));

  const out = [];
  out.push(codegenBanner(ir, '//', { ...opts, style: 'switch' }));
  out.push('');
  out.push(`const START = ${jsStr(start)};`);
  out.push('');
  codegenJsTokenize(ir).forEach(l => out.push(l));
  out.push('');

  // Accepting is a switch too, so the file holds no Set literal at all.
  if (!codegenIsTransducer(ir)) {
    out.push('function isAccepting(state) {');
    out.push('  switch (state) {');
    ir.states.filter(s => s.isAccept).forEach(s => out.push(`    case ${jsStr(names.get(s.id))}:`));
    if (ir.states.some(s => s.isAccept)) out.push('      return true;');
    out.push('    default:');
    out.push('      return false;');
    out.push('  }');
    out.push('}');
    out.push('');
  }

  if (ir.machine === 'Moore') {
    out.push('function outputOf(state) {');
    out.push('  switch (state) {');
    ir.states.forEach(s => {
      out.push(`    case ${jsStr(names.get(s.id))}: return ${jsStr(s.output == null ? '' : s.output)};`);
    });
    out.push('    default: return null;');
    out.push('  }');
    out.push('}');
    out.push('');
  }

  if (nd) {
    // The closure needs ε-targets per state; with no table that is its
    // own switch rather than a lookup.
    out.push('function epsilonTargets(state) {');
    out.push('  switch (state) {');
    order.forEach(name => {
      const targets = codegenEpsTargets(delta, name, eps);
      if (targets.length) out.push(`    case ${jsStr(name)}: return [${targets.map(jsStr).join(', ')}];`);
    });
    out.push('    default: return [];');
    out.push('  }');
    out.push('}');
    out.push('');
    out.push('function epsilonClosure(states) {');
    out.push('  const seen = new Set(states);');
    out.push('  const stack = [...states];');
    out.push('  while (stack.length) {');
    out.push('    for (const t of epsilonTargets(stack.pop())) {');
    out.push('      if (!seen.has(t)) { seen.add(t); stack.push(t); }');
    out.push('    }');
    out.push('  }');
    out.push('  return seen;');
    out.push('}');
    out.push('');
    out.push('// Collects every target of `state` on `symbol` into `next`.');
    out.push('function stepInto(state, symbol, next) {');
    out.push('  switch (state) {');
    order.forEach(name => {
      const rows = codegenRowsFor(delta, name).filter(([sym]) => sym !== eps);
      if (!rows.length) return;
      out.push(`    case ${jsStr(name)}:`);
      out.push('      switch (symbol) {');
      rows.forEach(([sym, dests]) => {
        const adds = dests.map(d => `next.add(${jsStr(d)});`).join(' ');
        out.push(`        case ${jsStr(sym)}: ${adds} break;`);
      });
      out.push('      }');
      out.push('      break;');
    });
    out.push('  }');
    out.push('}');
    out.push('');
    out.push('function accepts(input) {');
    out.push('  let current = epsilonClosure([START]);');
    out.push('  for (const symbol of tokenize(input)) {');
    out.push('    const next = new Set();');
    out.push('    for (const state of current) stepInto(state, symbol, next);');
    out.push('    current = epsilonClosure(next);');
    out.push('    if (!current.size) return false;');
    out.push('  }');
    out.push('  for (const state of current) if (isAccepting(state)) return true;');
    out.push('  return false;');
    out.push('}');
  } else {
    const transducer = codegenIsTransducer(ir);
    const sep = ir.isSymbolic ? "''" : "' '";
    out.push(transducer ? 'function transduce(input) {' : 'function accepts(input) {');
    out.push('  let state = START;');
    if (transducer) out.push('  const output = [];');
    if (ir.machine === 'Moore') out.push('  output.push(outputOf(state));');
    out.push('  for (const symbol of tokenize(input)) {');
    out.push('    switch (state) {');
    order.forEach(name => {
      const rows = codegenRowsFor(delta, name);
      out.push(`      case ${jsStr(name)}:`);
      if (!rows.length) {
        out.push(`        return ${transducer ? 'null' : 'false'}; // no outgoing transitions`);
        return;
      }
      out.push('        switch (symbol) {');
      rows.forEach(([sym, dests]) => {
        const d = dests[0];
        if (ir.machine === 'Mealy') {
          out.push(`          case ${jsStr(sym)}: output.push(${jsStr(d.out)}); state = ${jsStr(d.to)}; break;`);
        } else {
          out.push(`          case ${jsStr(sym)}: state = ${jsStr(d)}; break;`);
        }
      });
      out.push(`          default: return ${transducer ? 'null' : 'false'};`);
      out.push('        }');
      if (ir.machine === 'Moore') out.push('        output.push(outputOf(state));');
      out.push('        break;');
    });
    out.push(`      default: return ${transducer ? 'null' : 'false'};`);
    out.push('    }');
    out.push('  }');
    out.push(transducer ? `  return output.join(${sep});` : '  return isAccepting(state);');
    out.push('}');
  }

  out.push('');
  const api = codegenIsTransducer(ir) ? 'transduce' : 'accepts';
  out.push(`if (typeof module !== 'undefined') module.exports = { ${api}, START };`);
  return out.join('\n');
}

// ── JavaScript: class ─────────────────────────────────────────────
// The other two styles consume a whole string. This one exposes the
// state so input can arrive one symbol at a time — a stream, a parser,
// a UI dispatching an event per keystroke. accepts()/transduce() are
// still exported so a generated test suite works against any style.
function codegenJsClass(ir, opts = {}) {
  const names = codegenNames(ir);
  const delta = codegenDelta(ir, names);
  const start = names.get(ir.startId);
  const accepting = ir.states.filter(s => s.isAccept).map(s => names.get(s.id));
  const eps = ir.sym.eps;
  const nd = codegenIsNondeterministic(ir);
  const transducer = codegenIsTransducer(ir);
  const sep = ir.isSymbolic ? "''" : "' '";

  const out = [];
  out.push(codegenBanner(ir, '//', { ...opts, style: 'class' }));
  out.push('');

  // The table stays module-level rather than becoming static class
  // fields: this style is about the interface, and module consts work
  // in every runtime without relying on class-fields support.
  out.push('const DELTA = {');
  [...delta.entries()].forEach(([from, row]) => {
    if (!row.size) { out.push(`  ${jsStr(from)}: {},`); return; }
    const cells = [...row.entries()].map(([sym, dests]) => {
      if (ir.machine === 'Mealy') {
        const d = dests[0];
        return `${jsStr(sym)}: { to: ${jsStr(d.to)}, out: ${jsStr(d.out)} }`;
      }
      return `${jsStr(sym)}: ${nd ? `[${dests.map(jsStr).join(', ')}]` : jsStr(dests[0])}`;
    });
    out.push(`  ${jsStr(from)}: { ${cells.join(', ')} },`);
  });
  out.push('};');
  out.push('');
  out.push(`const START = ${jsStr(start)};`);
  if (!transducer) out.push(`const ACCEPTING = new Set([${accepting.map(jsStr).join(', ')}]);`);
  if (ir.machine === 'Moore') {
    out.push('const OUTPUT = {');
    ir.states.forEach(s => out.push(`  ${jsStr(names.get(s.id))}: ${jsStr(s.output == null ? '' : s.output)},`));
    out.push('};');
  }
  if (nd) out.push(`const EPSILON = ${jsStr(eps)};`);
  out.push('');
  codegenJsTokenize(ir).forEach(l => out.push(l));
  out.push('');

  if (nd) {
    out.push('function epsilonClosure(states) {');
    out.push('  const seen = new Set(states);');
    out.push('  const stack = [...states];');
    out.push('  while (stack.length) {');
    out.push('    const s = stack.pop();');
    out.push('    for (const t of (DELTA[s]?.[EPSILON] ?? [])) {');
    out.push('      if (!seen.has(t)) { seen.add(t); stack.push(t); }');
    out.push('    }');
    out.push('  }');
    out.push('  return seen;');
    out.push('}');
    out.push('');
  }

  out.push('class Automaton {');
  out.push('  constructor() {');
  out.push('    this.reset();');
  out.push('  }');
  out.push('');
  out.push('  /** Returns the machine to its start configuration. */');
  out.push('  reset() {');
  if (nd) {
    out.push('    this.current = epsilonClosure([START]);');
  } else {
    out.push('    this.state = START;');
    out.push('    this.dead = false;');
  }
  if (transducer) out.push(`    this.output = [${ir.machine === 'Moore' ? 'OUTPUT[START]' : ''}];`);
  out.push('    return this;');
  out.push('  }');
  out.push('');

  if (nd) {
    out.push('  /** Consumes one symbol. Returns false once no state survives. */');
    out.push('  step(symbol) {');
    out.push('    const next = new Set();');
    out.push('    for (const s of this.current) {');
    out.push('      for (const t of (DELTA[s]?.[symbol] ?? [])) next.add(t);');
    out.push('    }');
    out.push('    this.current = epsilonClosure(next);');
    out.push('    return this.current.size > 0;');
    out.push('  }');
    out.push('');
    out.push('  get isAccepting() {');
    out.push('    for (const s of this.current) if (ACCEPTING.has(s)) return true;');
    out.push('    return false;');
    out.push('  }');
    out.push('');
    out.push('  /** The set of states the machine could currently be in. */');
    out.push('  get states() {');
    out.push('    return [...this.current];');
    out.push('  }');
  } else if (ir.machine === 'Mealy') {
    out.push('  /** Consumes one symbol and returns what it emits, or null. */');
    out.push('  step(symbol) {');
    out.push('    const edge = DELTA[this.state]?.[symbol];');
    out.push('    if (edge === undefined) { this.dead = true; return null; }');
    out.push('    this.state = edge.to;');
    out.push('    this.output.push(edge.out);');
    out.push('    return edge.out;');
    out.push('  }');
  } else if (ir.machine === 'Moore') {
    out.push('  /** Consumes one symbol and returns the new state\'s output. */');
    out.push('  step(symbol) {');
    out.push('    const next = DELTA[this.state]?.[symbol];');
    out.push('    if (next === undefined) { this.dead = true; return null; }');
    out.push('    this.state = next;');
    out.push('    const emitted = OUTPUT[this.state];');
    out.push('    this.output.push(emitted);');
    out.push('    return emitted;');
    out.push('  }');
  } else {
    out.push('  /** Consumes one symbol. Returns false if it kills the run. */');
    out.push('  step(symbol) {');
    out.push('    const next = DELTA[this.state]?.[symbol];');
    out.push('    if (next === undefined) { this.dead = true; return false; }');
    out.push('    this.state = next;');
    out.push('    return true;');
    out.push('  }');
    out.push('');
    out.push('  get isAccepting() {');
    out.push('    return !this.dead && ACCEPTING.has(this.state);');
    out.push('  }');
  }

  out.push('');
  if (transducer) {
    out.push('  /** Runs a whole input. Returns null on an undefined transition. */');
    out.push('  transduce(input) {');
    out.push('    this.reset();');
    out.push('    for (const symbol of tokenize(input)) {');
    out.push('      if (this.step(symbol) === null) return null;');
    out.push('    }');
    out.push(`    return this.output.join(${sep});`);
    out.push('  }');
  } else {
    out.push('  /** Runs a whole input from the start state. */');
    out.push('  accepts(input) {');
    out.push('    this.reset();');
    out.push('    for (const symbol of tokenize(input)) {');
    out.push('      if (!this.step(symbol)) return false;');
    out.push('    }');
    out.push('    return this.isAccepting;');
    out.push('  }');
  }
  out.push('}');
  out.push('');

  const api = transducer ? 'transduce' : 'accepts';
  out.push(`// Convenience wrapper, so every style exposes the same ${api}().`);
  out.push(`function ${api}(input) {`);
  out.push(`  return new Automaton().${api}(input);`);
  out.push('}');
  out.push('');
  out.push(`if (typeof module !== 'undefined') module.exports = { Automaton, ${api}, DELTA, START };`);
  return out.join('\n');
}

// ══════════════════════════════════════════════════════════════════
//  PYTHON
// ══════════════════════════════════════════════════════════════════
function codegenPython(ir, opts = {}) {
  const support = codegenSupport(ir);
  if (!support.ok) return codegenUnsupported(support.reason, '#');
  const style = codegenStyle(opts);
  if (style === 'switch') return codegenPySwitch(ir, opts);
  if (style === 'class') return codegenPyClass(ir, opts);
  return codegenPyTable(ir, opts);
}

function codegenPyTokenize(ir) {
  return [
    'def tokenize(text):',
    ir.isSymbolic ? '    return list(text)' : '    return text.split()'
  ];
}

function codegenPyTable(ir, opts = {}) {
  const names = codegenNames(ir);
  const delta = codegenDelta(ir, names);
  const start = names.get(ir.startId);
  const accepting = ir.states.filter(s => s.isAccept).map(s => names.get(s.id));
  const nd = codegenIsNondeterministic(ir);

  const out = [];
  out.push(codegenBanner(ir, '#', { ...opts, style: 'table' }));
  out.push('');
  out.push('DELTA = {');
  [...delta.entries()].forEach(([from, row]) => {
    if (!row.size) { out.push(`    ${pyStr(from)}: {},`); return; }
    const cells = [...row.entries()].map(([sym, dests]) => {
      if (ir.machine === 'Mealy') {
        const d = dests[0];
        return `${pyStr(sym)}: (${pyStr(d.to)}, ${pyStr(d.out)})`;
      }
      return `${pyStr(sym)}: ${nd ? `(${dests.map(pyStr).join(', ')}${dests.length === 1 ? ',' : ''})` : pyStr(dests[0])}`;
    });
    out.push(`    ${pyStr(from)}: {${cells.join(', ')}},`);
  });
  out.push('}');
  out.push('');
  out.push(`START = ${pyStr(start)}`);
  if (!codegenIsTransducer(ir)) {
    out.push(`ACCEPTING = frozenset({${accepting.map(pyStr).join(', ')}})`);
  }
  if (ir.machine === 'Moore') {
    out.push('');
    out.push('# Moore output is a property of the state, not the edge.');
    out.push('OUTPUT = {');
    ir.states.forEach(s => out.push(`    ${pyStr(names.get(s.id))}: ${pyStr(s.output == null ? '' : s.output)},`));
    out.push('}');
  }
  out.push('');
  codegenPyTokenize(ir).forEach(l => out.push(l));
  out.push('');
  out.push('');

  if (nd) {
    out.push(`EPSILON = ${pyStr(ir.sym.eps)}`);
    out.push('');
    out.push('');
    out.push('def epsilon_closure(states):');
    out.push('    seen = set(states)');
    out.push('    stack = list(states)');
    out.push('    while stack:');
    out.push('        state = stack.pop()');
    out.push('        for target in DELTA.get(state, {}).get(EPSILON, ()):');
    out.push('            if target not in seen:');
    out.push('                seen.add(target)');
    out.push('                stack.append(target)');
    out.push('    return seen');
    out.push('');
    out.push('');
    out.push('def accepts(text):');
    out.push('    current = epsilon_closure({START})');
    out.push('    for symbol in tokenize(text):');
    out.push('        nxt = set()');
    out.push('        for state in current:');
    out.push('            nxt.update(DELTA.get(state, {}).get(symbol, ()))');
    out.push('        current = epsilon_closure(nxt)');
    out.push('        if not current:');
    out.push('            return False');
    out.push('    return bool(current & ACCEPTING)');
  } else if (ir.machine === 'Mealy') {
    out.push('def transduce(text):');
    out.push('    state = START');
    out.push('    output = []');
    out.push('    for symbol in tokenize(text):');
    out.push('        edge = DELTA.get(state, {}).get(symbol)');
    out.push('        if edge is None:');
    out.push('            return None  # undefined transition');
    out.push('        output.append(edge[1])');
    out.push('        state = edge[0]');
    out.push(`    return ${ir.isSymbolic ? "''" : "' '"}.join(output)`);
  } else if (ir.machine === 'Moore') {
    out.push('def transduce(text):');
    out.push('    state = START');
    out.push('    output = [OUTPUT[state]]');
    out.push('    for symbol in tokenize(text):');
    out.push('        nxt = DELTA.get(state, {}).get(symbol)');
    out.push('        if nxt is None:');
    out.push('            return None  # undefined transition');
    out.push('        state = nxt');
    out.push('        output.append(OUTPUT[state])');
    out.push(`    return ${ir.isSymbolic ? "''" : "' '"}.join(output)`);
  } else {
    out.push('def accepts(text):');
    out.push('    state = START');
    out.push('    for symbol in tokenize(text):');
    out.push('        nxt = DELTA.get(state, {}).get(symbol)');
    out.push('        if nxt is None:');
    out.push('            return False  # dead: no such transition');
    out.push('        state = nxt');
    out.push('    return state in ACCEPTING');
  }
  out.push('');
  return out.join('\n');
}

// ── Python: match/case ────────────────────────────────────────────
// `match` is Python's switch, and the direct translation of the nested
// control flow the other languages get. Note the version floor: match
// landed in 3.10, so this style says so in the banner rather than
// failing at import time on an older interpreter.
//
// Every pattern here is a string literal. A bare name in a case would
// be a capture pattern — it would match anything and bind, silently
// turning the state machine into an unconditional branch.
function codegenPySwitch(ir, opts = {}) {
  const names = codegenNames(ir);
  const delta = codegenDelta(ir, names);
  const start = names.get(ir.startId);
  const eps = ir.sym.eps;
  const nd = codegenIsNondeterministic(ir);
  const transducer = codegenIsTransducer(ir);
  const order = ir.states.map(s => names.get(s.id));

  const out = [];
  out.push(codegenBanner(ir, '#', { ...opts, style: 'switch', extraNote: 'Requires Python 3.10+ for the match statement.' }));
  out.push('');
  out.push(`START = ${pyStr(start)}`);
  out.push('');
  out.push('');
  codegenPyTokenize(ir).forEach(l => out.push(l));
  out.push('');
  out.push('');

  if (!transducer) {
    out.push('def is_accepting(state):');
    out.push('    match state:');
    const accs = ir.states.filter(s => s.isAccept).map(s => pyStr(names.get(s.id)));
    if (accs.length) {
      out.push(`        case ${accs.join(' | ')}:`);
      out.push('            return True');
    }
    out.push('        case _:');
    out.push('            return False');
    out.push('');
    out.push('');
  }

  if (ir.machine === 'Moore') {
    out.push('def output_of(state):');
    out.push('    match state:');
    ir.states.forEach(s => {
      out.push(`        case ${pyStr(names.get(s.id))}:`);
      out.push(`            return ${pyStr(s.output == null ? '' : s.output)}`);
    });
    out.push('        case _:');
    out.push('            return None');
    out.push('');
    out.push('');
  }

  if (nd) {
    out.push('def epsilon_targets(state):');
    out.push('    match state:');
    let anyEps = false;
    order.forEach(name => {
      const targets = codegenEpsTargets(delta, name, eps);
      if (!targets.length) return;
      anyEps = true;
      out.push(`        case ${pyStr(name)}:`);
      out.push(`            return (${targets.map(pyStr).join(', ')}${targets.length === 1 ? ',' : ''})`);
    });
    if (!anyEps) out.push('        # this machine has no ε-transitions');
    out.push('        case _:');
    out.push('            return ()');
    out.push('');
    out.push('');
    out.push('def epsilon_closure(states):');
    out.push('    seen = set(states)');
    out.push('    stack = list(states)');
    out.push('    while stack:');
    out.push('        for target in epsilon_targets(stack.pop()):');
    out.push('            if target not in seen:');
    out.push('                seen.add(target)');
    out.push('                stack.append(target)');
    out.push('    return seen');
    out.push('');
    out.push('');
    out.push('def step_into(state, symbol, nxt):');
    out.push('    """Adds every target of `state` on `symbol` to `nxt`."""');
    out.push('    match state:');
    let anyRows = false;
    order.forEach(name => {
      const rows = codegenRowsFor(delta, name).filter(([sym]) => sym !== eps);
      if (!rows.length) return;
      anyRows = true;
      out.push(`        case ${pyStr(name)}:`);
      out.push('            match symbol:');
      rows.forEach(([sym, dests]) => {
        out.push(`                case ${pyStr(sym)}:`);
        out.push(`                    nxt.update((${dests.map(pyStr).join(', ')}${dests.length === 1 ? ',' : ''}))`);
      });
    });
    if (!anyRows) out.push('        case _:');
    if (!anyRows) out.push('            pass');
    out.push('');
    out.push('');
    out.push('def accepts(text):');
    out.push('    current = epsilon_closure({START})');
    out.push('    for symbol in tokenize(text):');
    out.push('        nxt = set()');
    out.push('        for state in current:');
    out.push('            step_into(state, symbol, nxt)');
    out.push('        current = epsilon_closure(nxt)');
    out.push('        if not current:');
    out.push('            return False');
    out.push('    return any(is_accepting(state) for state in current)');
  } else {
    const fail = transducer ? 'None' : 'False';
    out.push(transducer ? 'def transduce(text):' : 'def accepts(text):');
    out.push('    state = START');
    if (transducer) out.push(ir.machine === 'Moore' ? '    output = [output_of(state)]' : '    output = []');
    out.push('    for symbol in tokenize(text):');
    out.push('        match state:');
    order.forEach(name => {
      const rows = codegenRowsFor(delta, name);
      out.push(`            case ${pyStr(name)}:`);
      if (!rows.length) {
        out.push(`                return ${fail}  # no outgoing transitions`);
        return;
      }
      out.push('                match symbol:');
      rows.forEach(([sym, dests]) => {
        const d = dests[0];
        out.push(`                    case ${pyStr(sym)}:`);
        if (ir.machine === 'Mealy') {
          out.push(`                        output.append(${pyStr(d.out)})`);
          out.push(`                        state = ${pyStr(d.to)}`);
        } else {
          out.push(`                        state = ${pyStr(d)}`);
        }
      });
      out.push('                    case _:');
      out.push(`                        return ${fail}`);
      if (ir.machine === 'Moore') out.push('                output.append(output_of(state))');
    });
    out.push('            case _:');
    out.push(`                return ${fail}`);
    out.push(transducer
      ? `    return ${ir.isSymbolic ? "''" : "' '"}.join(output)`
      : '    return is_accepting(state)');
  }

  out.push('');
  return out.join('\n');
}

// ── Python: class ─────────────────────────────────────────────────
function codegenPyClass(ir, opts = {}) {
  const names = codegenNames(ir);
  const delta = codegenDelta(ir, names);
  const start = names.get(ir.startId);
  const accepting = ir.states.filter(s => s.isAccept).map(s => names.get(s.id));
  const eps = ir.sym.eps;
  const nd = codegenIsNondeterministic(ir);
  const transducer = codegenIsTransducer(ir);
  const join = ir.isSymbolic ? "''" : "' '";

  const out = [];
  out.push(codegenBanner(ir, '#', { ...opts, style: 'class' }));
  out.push('');
  out.push('DELTA = {');
  [...delta.entries()].forEach(([from, row]) => {
    if (!row.size) { out.push(`    ${pyStr(from)}: {},`); return; }
    const cells = [...row.entries()].map(([sym, dests]) => {
      if (ir.machine === 'Mealy') {
        const d = dests[0];
        return `${pyStr(sym)}: (${pyStr(d.to)}, ${pyStr(d.out)})`;
      }
      return `${pyStr(sym)}: ${nd ? `(${dests.map(pyStr).join(', ')}${dests.length === 1 ? ',' : ''})` : pyStr(dests[0])}`;
    });
    out.push(`    ${pyStr(from)}: {${cells.join(', ')}},`);
  });
  out.push('}');
  out.push('');
  out.push(`START = ${pyStr(start)}`);
  if (!transducer) out.push(`ACCEPTING = frozenset({${accepting.map(pyStr).join(', ')}})`);
  if (nd) out.push(`EPSILON = ${pyStr(eps)}`);
  if (ir.machine === 'Moore') {
    out.push('OUTPUT = {');
    ir.states.forEach(s => out.push(`    ${pyStr(names.get(s.id))}: ${pyStr(s.output == null ? '' : s.output)},`));
    out.push('}');
  }
  out.push('');
  out.push('');
  codegenPyTokenize(ir).forEach(l => out.push(l));
  out.push('');
  out.push('');

  if (nd) {
    out.push('def epsilon_closure(states):');
    out.push('    seen = set(states)');
    out.push('    stack = list(states)');
    out.push('    while stack:');
    out.push('        state = stack.pop()');
    out.push('        for target in DELTA.get(state, {}).get(EPSILON, ()):');
    out.push('            if target not in seen:');
    out.push('                seen.add(target)');
    out.push('                stack.append(target)');
    out.push('    return seen');
    out.push('');
    out.push('');
  }

  out.push('class Automaton:');
  out.push('    """Stateful recogniser: feed it one symbol at a time."""');
  out.push('');
  out.push('    def __init__(self):');
  out.push('        self.reset()');
  out.push('');
  out.push('    def reset(self):');
  if (nd) {
    out.push('        self.current = epsilon_closure({START})');
  } else {
    out.push('        self.state = START');
    out.push('        self.dead = False');
  }
  if (transducer) out.push(ir.machine === 'Moore' ? '        self.output = [OUTPUT[START]]' : '        self.output = []');
  out.push('        return self');
  out.push('');

  if (nd) {
    out.push('    def step(self, symbol):');
    out.push('        """Consumes one symbol. False once no state survives."""');
    out.push('        nxt = set()');
    out.push('        for state in self.current:');
    out.push('            nxt.update(DELTA.get(state, {}).get(symbol, ()))');
    out.push('        self.current = epsilon_closure(nxt)');
    out.push('        return bool(self.current)');
    out.push('');
    out.push('    @property');
    out.push('    def is_accepting(self):');
    out.push('        return bool(self.current & ACCEPTING)');
    out.push('');
    out.push('    @property');
    out.push('    def states(self):');
    out.push('        """Every state the machine could currently be in."""');
    out.push('        return frozenset(self.current)');
  } else if (ir.machine === 'Mealy') {
    out.push('    def step(self, symbol):');
    out.push('        """Consumes one symbol, returning what it emits or None."""');
    out.push('        edge = DELTA.get(self.state, {}).get(symbol)');
    out.push('        if edge is None:');
    out.push('            self.dead = True');
    out.push('            return None');
    out.push('        self.state, emitted = edge');
    out.push('        self.output.append(emitted)');
    out.push('        return emitted');
  } else if (ir.machine === 'Moore') {
    out.push('    def step(self, symbol):');
    out.push('        """Consumes one symbol, returning the new state\'s output."""');
    out.push('        nxt = DELTA.get(self.state, {}).get(symbol)');
    out.push('        if nxt is None:');
    out.push('            self.dead = True');
    out.push('            return None');
    out.push('        self.state = nxt');
    out.push('        emitted = OUTPUT[self.state]');
    out.push('        self.output.append(emitted)');
    out.push('        return emitted');
  } else {
    out.push('    def step(self, symbol):');
    out.push('        """Consumes one symbol. False if it kills the run."""');
    out.push('        nxt = DELTA.get(self.state, {}).get(symbol)');
    out.push('        if nxt is None:');
    out.push('            self.dead = True');
    out.push('            return False');
    out.push('        self.state = nxt');
    out.push('        return True');
    out.push('');
    out.push('    @property');
    out.push('    def is_accepting(self):');
    out.push('        return not self.dead and self.state in ACCEPTING');
  }

  out.push('');
  if (transducer) {
    out.push('    def transduce(self, text):');
    out.push('        self.reset()');
    out.push('        for symbol in tokenize(text):');
    out.push('            if self.step(symbol) is None:');
    out.push('                return None');
    out.push(`        return ${join}.join(self.output)`);
  } else {
    out.push('    def accepts(self, text):');
    out.push('        self.reset()');
    out.push('        for symbol in tokenize(text):');
    out.push('            if not self.step(symbol):');
    out.push('                return False');
    out.push('        return self.is_accepting');
  }

  out.push('');
  out.push('');
  const api = transducer ? 'transduce' : 'accepts';
  out.push(`# Convenience wrapper, so every style exposes the same ${api}().`);
  out.push(`def ${api}(text):`);
  out.push(`    return Automaton().${api}(text)`);
  out.push('');
  return out.join('\n');
}

// ══════════════════════════════════════════════════════════════════
//  JAVA
// ══════════════════════════════════════════════════════════════════
function codegenJava(ir, opts = {}) {
  const support = codegenSupport(ir);
  if (!support.ok) return codegenUnsupported(support.reason, '//');
  const style = codegenStyle(opts);
  if (style === 'switch') return codegenJavaSwitch(ir, opts);
  if (style === 'class') return codegenJavaClass(ir, opts);
  return codegenJavaTable(ir, opts);
}

// Java's tokenizer body, indented for a class member.
function codegenJavaTokenize(ir) {
  const out = ['    private static List<String> tokenize(String input) {'];
  if (ir.isSymbolic) {
    out.push('        List<String> out = new ArrayList<>();');
    out.push('        for (int i = 0; i < input.length(); ) {');
    out.push('            int cp = input.codePointAt(i);');
    out.push('            out.add(new String(Character.toChars(cp)));');
    out.push('            i += Character.charCount(cp);');
    out.push('        }');
    out.push('        return out;');
  } else {
    out.push('        List<String> out = new ArrayList<>();');
    out.push('        for (String part : input.trim().split("\\\\s+")) {');
    out.push('            if (!part.isEmpty()) out.add(part);');
    out.push('        }');
    out.push('        return out;');
  }
  out.push('    }');
  return out;
}

function codegenJavaTable(ir, opts = {}) {
  const cls = exportIdent(opts.className || 'Automaton', 'Automaton');
  const names = codegenNames(ir);
  const delta = codegenDelta(ir, names);
  const nd = codegenIsNondeterministic(ir);

  const out = [];
  out.push(codegenBanner(ir, '//', { ...opts, style: 'table' }));
  out.push('');
  out.push('import java.util.*;');
  out.push('');
  out.push(`public final class ${cls} {`);
  out.push(`    private static final String START = ${javaStr(names.get(ir.startId))};`);

  if (!codegenIsTransducer(ir)) {
    const acc = ir.states.filter(s => s.isAccept).map(s => javaStr(names.get(s.id)));
    out.push(`    private static final Set<String> ACCEPTING = new HashSet<>(Arrays.asList(${acc.join(', ')}));`);
  }

  // Java has no map literal; the table is filled in a static block.
  const valueType = nd ? 'List<String>' : (ir.machine === 'Mealy' ? 'String[]' : 'String');
  out.push(`    private static final Map<String, Map<String, ${valueType}>> DELTA = new HashMap<>();`);
  if (ir.machine === 'Moore') {
    out.push('    private static final Map<String, String> OUTPUT = new HashMap<>();');
  }
  out.push('');
  out.push('    static {');
  out.push(`        Map<String, ${valueType}> row;`);
  [...delta.entries()].forEach(([from, row]) => {
    out.push('        row = new HashMap<>();');
    [...row.entries()].forEach(([sym, dests]) => {
      if (ir.machine === 'Mealy') {
        const d = dests[0];
        out.push(`        row.put(${javaStr(sym)}, new String[]{${javaStr(d.to)}, ${javaStr(d.out)}});`);
      } else if (nd) {
        out.push(`        row.put(${javaStr(sym)}, Arrays.asList(${dests.map(javaStr).join(', ')}));`);
      } else {
        out.push(`        row.put(${javaStr(sym)}, ${javaStr(dests[0])});`);
      }
    });
    out.push(`        DELTA.put(${javaStr(from)}, row);`);
  });
  if (ir.machine === 'Moore') {
    ir.states.forEach(s => {
      out.push(`        OUTPUT.put(${javaStr(names.get(s.id))}, ${javaStr(s.output == null ? '' : s.output)});`);
    });
  }
  out.push('    }');
  out.push('');
  codegenJavaTokenize(ir).forEach(l => out.push(l));
  out.push('');

  if (nd) {
    out.push(`    private static final String EPSILON = ${javaStr(ir.sym.eps)};`);
    out.push('');
    out.push('    private static Set<String> epsilonClosure(Collection<String> states) {');
    out.push('        Set<String> seen = new HashSet<>(states);');
    out.push('        Deque<String> stack = new ArrayDeque<>(states);');
    out.push('        while (!stack.isEmpty()) {');
    out.push('            Map<String, List<String>> row = DELTA.get(stack.pop());');
    out.push('            if (row == null) continue;');
    out.push('            for (String target : row.getOrDefault(EPSILON, Collections.emptyList())) {');
    out.push('                if (seen.add(target)) stack.push(target);');
    out.push('            }');
    out.push('        }');
    out.push('        return seen;');
    out.push('    }');
    out.push('');
    out.push('    public static boolean accepts(String input) {');
    out.push('        Set<String> current = epsilonClosure(Collections.singletonList(START));');
    out.push('        for (String symbol : tokenize(input)) {');
    out.push('            Set<String> next = new HashSet<>();');
    out.push('            for (String state : current) {');
    out.push('                Map<String, List<String>> row = DELTA.get(state);');
    out.push('                if (row != null) next.addAll(row.getOrDefault(symbol, Collections.emptyList()));');
    out.push('            }');
    out.push('            current = epsilonClosure(next);');
    out.push('            if (current.isEmpty()) return false;');
    out.push('        }');
    out.push('        for (String state : current) if (ACCEPTING.contains(state)) return true;');
    out.push('        return false;');
    out.push('    }');
  } else if (codegenIsTransducer(ir)) {
    const sep = ir.isSymbolic ? '""' : '" "';
    out.push(`    private static final String SEP = ${sep};`);
    out.push('');
    out.push('    public static String transduce(String input) {');
    out.push('        String state = START;');
    out.push('        StringBuilder out = new StringBuilder();');
    if (ir.machine === 'Mealy') {
      // A `first` flag rather than a length check: an empty emitted symbol
      // would otherwise swallow the separator before the one after it.
      out.push('        boolean first = true;');
      out.push('        for (String symbol : tokenize(input)) {');
      out.push('            Map<String, String[]> row = DELTA.get(state);');
      out.push('            String[] edge = row == null ? null : row.get(symbol);');
      out.push('            if (edge == null) return null; // undefined transition');
      out.push('            if (!first) out.append(SEP);');
      out.push('            out.append(edge[1]);');
      out.push('            state = edge[0];');
      out.push('            first = false;');
      out.push('        }');
    } else {
      out.push('        out.append(OUTPUT.get(state));');
      out.push('        for (String symbol : tokenize(input)) {');
      out.push('            Map<String, String> row = DELTA.get(state);');
      out.push('            String next = row == null ? null : row.get(symbol);');
      out.push('            if (next == null) return null; // undefined transition');
      out.push('            state = next;');
      out.push('            out.append(SEP).append(OUTPUT.get(state));');
      out.push('        }');
    }
    out.push('        return out.toString();');
    out.push('    }');
  } else {
    out.push('    public static boolean accepts(String input) {');
    out.push('        String state = START;');
    out.push('        for (String symbol : tokenize(input)) {');
    out.push('            Map<String, String> row = DELTA.get(state);');
    out.push('            String next = row == null ? null : row.get(symbol);');
    out.push('            if (next == null) return false; // dead: no such transition');
    out.push('            state = next;');
    out.push('        }');
    out.push('        return ACCEPTING.contains(state);');
    out.push('    }');
  }

  out.push('}');
  return out.join('\n');
}

// ── Java: switch ──────────────────────────────────────────────────
// Switching on String has been legal since Java 7, so the state stays a
// readable name rather than becoming an int the reader has to decode
// against a table of constants — which would defeat the point of
// choosing this style.
function codegenJavaSwitch(ir, opts = {}) {
  const cls = exportIdent(opts.className || 'Automaton', 'Automaton');
  const names = codegenNames(ir);
  const delta = codegenDelta(ir, names);
  const eps = ir.sym.eps;
  const nd = codegenIsNondeterministic(ir);
  const transducer = codegenIsTransducer(ir);
  const order = ir.states.map(s => names.get(s.id));

  const out = [];
  out.push(codegenBanner(ir, '//', { ...opts, style: 'switch' }));
  out.push('');
  out.push('import java.util.*;');
  out.push('');
  out.push(`public final class ${cls} {`);
  out.push(`    private static final String START = ${javaStr(names.get(ir.startId))};`);
  if (transducer) out.push(`    private static final String SEP = ${ir.isSymbolic ? '""' : '" "'};`);
  out.push('');
  codegenJavaTokenize(ir).forEach(l => out.push(l));
  out.push('');

  if (!transducer) {
    out.push('    private static boolean isAccepting(String state) {');
    out.push('        switch (state) {');
    ir.states.filter(s => s.isAccept).forEach(s => out.push(`            case ${javaStr(names.get(s.id))}:`));
    if (ir.states.some(s => s.isAccept)) out.push('                return true;');
    out.push('            default:');
    out.push('                return false;');
    out.push('        }');
    out.push('    }');
    out.push('');
  }

  if (ir.machine === 'Moore') {
    out.push('    private static String outputOf(String state) {');
    out.push('        switch (state) {');
    ir.states.forEach(s => {
      out.push(`            case ${javaStr(names.get(s.id))}: return ${javaStr(s.output == null ? '' : s.output)};`);
    });
    out.push('            default: return null;');
    out.push('        }');
    out.push('    }');
    out.push('');
  }

  if (nd) {
    out.push('    private static List<String> epsilonTargets(String state) {');
    out.push('        switch (state) {');
    order.forEach(name => {
      const targets = codegenEpsTargets(delta, name, eps);
      if (targets.length) {
        out.push(`            case ${javaStr(name)}: return Arrays.asList(${targets.map(javaStr).join(', ')});`);
      }
    });
    out.push('            default: return Collections.emptyList();');
    out.push('        }');
    out.push('    }');
    out.push('');
    out.push('    private static Set<String> epsilonClosure(Collection<String> states) {');
    out.push('        Set<String> seen = new HashSet<>(states);');
    out.push('        Deque<String> stack = new ArrayDeque<>(states);');
    out.push('        while (!stack.isEmpty()) {');
    out.push('            for (String target : epsilonTargets(stack.pop())) {');
    out.push('                if (seen.add(target)) stack.push(target);');
    out.push('            }');
    out.push('        }');
    out.push('        return seen;');
    out.push('    }');
    out.push('');
    out.push('    /** Adds every target of {@code state} on {@code symbol} to {@code next}. */');
    out.push('    private static void stepInto(String state, String symbol, Set<String> next) {');
    out.push('        switch (state) {');
    order.forEach(name => {
      const rows = codegenRowsFor(delta, name).filter(([sym]) => sym !== eps);
      if (!rows.length) return;
      out.push(`            case ${javaStr(name)}:`);
      out.push('                switch (symbol) {');
      rows.forEach(([sym, dests]) => {
        out.push(`                    case ${javaStr(sym)}:`);
        dests.forEach(d => out.push(`                        next.add(${javaStr(d)});`));
        out.push('                        break;');
      });
      out.push('                }');
      out.push('                break;');
    });
    out.push('        }');
    out.push('    }');
    out.push('');
    out.push('    public static boolean accepts(String input) {');
    out.push('        Set<String> current = epsilonClosure(Collections.singletonList(START));');
    out.push('        for (String symbol : tokenize(input)) {');
    out.push('            Set<String> next = new HashSet<>();');
    out.push('            for (String state : current) stepInto(state, symbol, next);');
    out.push('            current = epsilonClosure(next);');
    out.push('            if (current.isEmpty()) return false;');
    out.push('        }');
    out.push('        for (String state : current) if (isAccepting(state)) return true;');
    out.push('        return false;');
    out.push('    }');
  } else {
    const fail = transducer ? 'null' : 'false';
    out.push(transducer
      ? '    public static String transduce(String input) {'
      : '    public static boolean accepts(String input) {');
    out.push('        String state = START;');
    if (transducer) {
      out.push('        StringBuilder out = new StringBuilder();');
      out.push('        boolean first = true;');
      if (ir.machine === 'Moore') {
        out.push('        out.append(outputOf(state));');
        out.push('        first = false;');
      }
    }
    out.push('        for (String symbol : tokenize(input)) {');
    out.push('            switch (state) {');
    order.forEach(name => {
      const rows = codegenRowsFor(delta, name);
      out.push(`                case ${javaStr(name)}:`);
      if (!rows.length) {
        out.push(`                    return ${fail}; // no outgoing transitions`);
        return;
      }
      out.push('                    switch (symbol) {');
      rows.forEach(([sym, dests]) => {
        const d = dests[0];
        out.push(`                        case ${javaStr(sym)}:`);
        if (ir.machine === 'Mealy') {
          out.push('                            if (!first) out.append(SEP);');
          out.push(`                            out.append(${javaStr(d.out)});`);
          out.push('                            first = false;');
          out.push(`                            state = ${javaStr(d.to)};`);
        } else {
          out.push(`                            state = ${javaStr(d)};`);
        }
        out.push('                            break;');
      });
      out.push(`                        default: return ${fail};`);
      out.push('                    }');
      if (ir.machine === 'Moore') {
        out.push('                    if (!first) out.append(SEP);');
        out.push('                    out.append(outputOf(state));');
        out.push('                    first = false;');
      }
      out.push('                    break;');
    });
    out.push(`                default: return ${fail};`);
    out.push('            }');
    out.push('        }');
    out.push(transducer ? '        return out.toString();' : '        return isAccepting(state);');
    out.push('    }');
  }

  out.push('}');
  return out.join('\n');
}

// ── Java: class ───────────────────────────────────────────────────
// Instance state plus reset/step/isAccepting, with the static accepts()
// kept so the same call site works whichever style was generated.
function codegenJavaClass(ir, opts = {}) {
  const cls = exportIdent(opts.className || 'Automaton', 'Automaton');
  const names = codegenNames(ir);
  const delta = codegenDelta(ir, names);
  const eps = ir.sym.eps;
  const nd = codegenIsNondeterministic(ir);
  const transducer = codegenIsTransducer(ir);

  const out = [];
  out.push(codegenBanner(ir, '//', { ...opts, style: 'class' }));
  out.push('');
  out.push('import java.util.*;');
  out.push('');
  out.push(`public final class ${cls} {`);
  out.push(`    private static final String START = ${javaStr(names.get(ir.startId))};`);
  if (!transducer) {
    const acc = ir.states.filter(s => s.isAccept).map(s => javaStr(names.get(s.id)));
    out.push(`    private static final Set<String> ACCEPTING = new HashSet<>(Arrays.asList(${acc.join(', ')}));`);
  }
  if (nd) out.push(`    private static final String EPSILON = ${javaStr(eps)};`);
  if (transducer) out.push(`    private static final String SEP = ${ir.isSymbolic ? '""' : '" "'};`);

  const valueType = nd ? 'List<String>' : (ir.machine === 'Mealy' ? 'String[]' : 'String');
  out.push(`    private static final Map<String, Map<String, ${valueType}>> DELTA = new HashMap<>();`);
  if (ir.machine === 'Moore') out.push('    private static final Map<String, String> OUTPUT = new HashMap<>();');
  out.push('');
  out.push('    static {');
  out.push(`        Map<String, ${valueType}> row;`);
  [...delta.entries()].forEach(([from, row]) => {
    out.push('        row = new HashMap<>();');
    [...row.entries()].forEach(([sym, dests]) => {
      if (ir.machine === 'Mealy') {
        const d = dests[0];
        out.push(`        row.put(${javaStr(sym)}, new String[]{${javaStr(d.to)}, ${javaStr(d.out)}});`);
      } else if (nd) {
        out.push(`        row.put(${javaStr(sym)}, Arrays.asList(${dests.map(javaStr).join(', ')}));`);
      } else {
        out.push(`        row.put(${javaStr(sym)}, ${javaStr(dests[0])});`);
      }
    });
    out.push(`        DELTA.put(${javaStr(from)}, row);`);
  });
  if (ir.machine === 'Moore') {
    ir.states.forEach(s => out.push(`        OUTPUT.put(${javaStr(names.get(s.id))}, ${javaStr(s.output == null ? '' : s.output)});`));
  }
  out.push('    }');
  out.push('');

  // Instance fields
  if (nd) out.push('    private Set<String> current;');
  else {
    out.push('    private String state;');
    out.push('    private boolean dead;');
  }
  if (transducer) out.push('    private final List<String> output = new ArrayList<>();');
  out.push('');
  out.push(`    public ${cls}() {`);
  out.push('        reset();');
  out.push('    }');
  out.push('');
  codegenJavaTokenize(ir).forEach(l => out.push(l));
  out.push('');

  if (nd) {
    out.push('    private static Set<String> epsilonClosure(Collection<String> states) {');
    out.push('        Set<String> seen = new HashSet<>(states);');
    out.push('        Deque<String> stack = new ArrayDeque<>(states);');
    out.push('        while (!stack.isEmpty()) {');
    out.push('            Map<String, List<String>> row = DELTA.get(stack.pop());');
    out.push('            if (row == null) continue;');
    out.push('            for (String target : row.getOrDefault(EPSILON, Collections.emptyList())) {');
    out.push('                if (seen.add(target)) stack.push(target);');
    out.push('            }');
    out.push('        }');
    out.push('        return seen;');
    out.push('    }');
    out.push('');
  }

  out.push('    /** Returns the machine to its start configuration. */');
  out.push(`    public ${cls} reset() {`);
  if (nd) out.push('        current = epsilonClosure(Collections.singletonList(START));');
  else {
    out.push('        state = START;');
    out.push('        dead = false;');
  }
  if (transducer) {
    out.push('        output.clear();');
    if (ir.machine === 'Moore') out.push('        output.add(OUTPUT.get(START));');
  }
  out.push('        return this;');
  out.push('    }');
  out.push('');

  if (nd) {
    out.push('    /** Consumes one symbol. False once no state survives. */');
    out.push('    public boolean step(String symbol) {');
    out.push('        Set<String> next = new HashSet<>();');
    out.push('        for (String s : current) {');
    out.push('            Map<String, List<String>> row = DELTA.get(s);');
    out.push('            if (row != null) next.addAll(row.getOrDefault(symbol, Collections.emptyList()));');
    out.push('        }');
    out.push('        current = epsilonClosure(next);');
    out.push('        return !current.isEmpty();');
    out.push('    }');
    out.push('');
    out.push('    public boolean isAccepting() {');
    out.push('        for (String s : current) if (ACCEPTING.contains(s)) return true;');
    out.push('        return false;');
    out.push('    }');
    out.push('');
    out.push('    /** Every state the machine could currently be in. */');
    out.push('    public Set<String> states() {');
    out.push('        return Collections.unmodifiableSet(current);');
    out.push('    }');
  } else if (ir.machine === 'Mealy') {
    out.push('    /** Consumes one symbol, returning what it emits or null. */');
    out.push('    public String step(String symbol) {');
    out.push('        Map<String, String[]> row = DELTA.get(state);');
    out.push('        String[] edge = row == null ? null : row.get(symbol);');
    out.push('        if (edge == null) { dead = true; return null; }');
    out.push('        state = edge[0];');
    out.push('        output.add(edge[1]);');
    out.push('        return edge[1];');
    out.push('    }');
  } else if (ir.machine === 'Moore') {
    out.push('    /** Consumes one symbol, returning the new state\'s output. */');
    out.push('    public String step(String symbol) {');
    out.push('        Map<String, String> row = DELTA.get(state);');
    out.push('        String next = row == null ? null : row.get(symbol);');
    out.push('        if (next == null) { dead = true; return null; }');
    out.push('        state = next;');
    out.push('        String emitted = OUTPUT.get(state);');
    out.push('        output.add(emitted);');
    out.push('        return emitted;');
    out.push('    }');
  } else {
    out.push('    /** Consumes one symbol. False if it kills the run. */');
    out.push('    public boolean step(String symbol) {');
    out.push('        Map<String, String> row = DELTA.get(state);');
    out.push('        String next = row == null ? null : row.get(symbol);');
    out.push('        if (next == null) { dead = true; return false; }');
    out.push('        state = next;');
    out.push('        return true;');
    out.push('    }');
    out.push('');
    out.push('    public boolean isAccepting() {');
    out.push('        return !dead && ACCEPTING.contains(state);');
    out.push('    }');
  }

  out.push('');
  if (transducer) {
    out.push('    public String run(String input) {');
    out.push('        reset();');
    out.push('        for (String symbol : tokenize(input)) {');
    out.push('            if (step(symbol) == null) return null;');
    out.push('        }');
    out.push('        StringBuilder sb = new StringBuilder();');
    out.push('        for (int i = 0; i < output.size(); i++) {');
    out.push('            if (i > 0) sb.append(SEP);');
    out.push('            sb.append(output.get(i));');
    out.push('        }');
    out.push('        return sb.toString();');
    out.push('    }');
    out.push('');
    out.push('    public static String transduce(String input) {');
    out.push(`        return new ${cls}().run(input);`);
    out.push('    }');
  } else {
    out.push('    public boolean run(String input) {');
    out.push('        reset();');
    out.push('        for (String symbol : tokenize(input)) {');
    out.push('            if (!step(symbol)) return false;');
    out.push('        }');
    out.push('        return isAccepting();');
    out.push('    }');
    out.push('');
    out.push('    /** Kept static so the call site matches the other styles. */');
    out.push('    public static boolean accepts(String input) {');
    out.push(`        return new ${cls}().run(input);`);
    out.push('    }');
  }

  out.push('}');
  return out.join('\n');
}

// ══════════════════════════════════════════════════════════════════
//  C
// ══════════════════════════════════════════════════════════════════
//  Narrower than the others on purpose. C has no string map, so the
//  clean, genuinely idiomatic output is a dense table indexed by state
//  and symbol — which needs every symbol to be one byte. Word-length
//  alphabets and nondeterminism both push this into building a hash
//  map and a subset simulator in C, and the result would be neither
//  readable nor obviously correct.
function codegenC(ir, opts = {}) {
  const support = codegenSupport(ir);
  if (!support.ok) return codegenUnsupported(support.reason, '/*');

  if (ir.machine !== 'DFA') {
    return codegenUnsupported(
      `C generation covers deterministic finite automata only. ${ir.machineLabel} needs either a `
      + `subset simulation or an output function, which in C means hand-rolling a string map — `
      + `use the JavaScript, Python or Java target instead.`, '//');
  }
  const oneByte = ir.sigma.every(s => [...s].length === 1 && s.charCodeAt(0) < 128);
  if (!oneByte) {
    return codegenUnsupported(
      'C generation needs every input symbol to be a single ASCII character, because the '
      + 'transition table is indexed directly by symbol. This alphabet has multi-character or '
      + 'non-ASCII symbols — use the JavaScript, Python or Java target instead.', '//');
  }

  const style = codegenStyle(opts);
  if (style === 'switch') return codegenCSwitch(ir, opts);
  if (style === 'class') return codegenCStruct(ir, opts);
  return codegenCTable(ir, opts);
}

// State ids, index map, sorted Σ, and the dense δ table — everything the
// three C emitters agree on. -1 is the dead state.
function codegenCShape(ir) {
  const names = exportUniqueIdents(ir.states, s => s.toUpperCase());
  const order = ir.states.map(s => s.id);
  const idx = new Map(order.map((id, i) => [id, i]));
  const sigma = [...ir.sigma].sort();
  const table = order.map(id => sigma.map(sym => {
    const t = ir.transitions.find(x => x.from === id && x.symbol === sym);
    return t ? idx.get(t.to) : -1;
  }));
  const accIdx = ir.states.filter(s => s.isAccept).map(s => idx.get(s.id));
  return { names, order, idx, sigma, table, accIdx };
}

// A C character literal for a Σ symbol, with the two that need escaping.
function codegenCChar(s) {
  return `'${s === "'" ? "\\'" : s === '\\' ? '\\\\' : s}'`;
}

function codegenCTable(ir, opts = {}) {
  const { names, order, idx, sigma, table, accIdx } = codegenCShape(ir);

  const out = [];
  out.push(codegenBanner(ir, '//', { ...opts, style: 'table' }));
  out.push('');
  out.push('#include <stdbool.h>');
  out.push('#include <stddef.h>');
  out.push('');
  out.push(`#define STATE_COUNT ${order.length}`);
  out.push(`#define SYMBOL_COUNT ${sigma.length}`);
  out.push('');
  out.push('// State indices, in canvas order.');
  order.forEach((id, i) => out.push(`#define ${names.get(id)} ${i}`));
  out.push('');
  out.push(`static const char SYMBOLS[SYMBOL_COUNT] = {${sigma.map(codegenCChar).join(', ')}};`);
  out.push('');
  out.push('// DELTA[state][symbol index]; -1 means no transition (reject).');
  out.push('static const int DELTA[STATE_COUNT][SYMBOL_COUNT] = {');
  table.forEach((row, i) => {
    out.push(`    {${row.map(v => String(v).padStart(2)).join(', ')}},  // ${ir.states[i].name}`);
  });
  out.push('};');
  out.push('');
  out.push(`static const int ACCEPTING[] = {${accIdx.length ? accIdx.join(', ') : '-1'}};`);
  out.push(`static const size_t ACCEPTING_COUNT = ${accIdx.length};`);
  out.push('');
  out.push('static int symbol_index(char c) {');
  out.push('    for (int i = 0; i < SYMBOL_COUNT; i++) {');
  out.push('        if (SYMBOLS[i] == c) return i;');
  out.push('    }');
  out.push('    return -1;');
  out.push('}');
  out.push('');
  out.push('bool automaton_accepts(const char *input) {');
  out.push(`    int state = ${names.get(ir.startId)};`);
  out.push('    for (const char *p = input; *p; p++) {');
  out.push('        int s = symbol_index(*p);');
  out.push('        if (s < 0) return false;  // symbol not in the alphabet');
  out.push('        state = DELTA[state][s];');
  out.push('        if (state < 0) return false;  // dead: no such transition');
  out.push('    }');
  out.push('    for (size_t i = 0; i < ACCEPTING_COUNT; i++) {');
  out.push('        if (ACCEPTING[i] == state) return true;');
  out.push('    }');
  out.push('    return false;');
  out.push('}');
  return out.join('\n');
}

// ── C: switch ─────────────────────────────────────────────────────
// No tables at all — δ is nested switches on the state and the byte.
// This is the shape you write by hand for a protocol or lexer inner
// loop: the compiler turns it into a jump table, and nothing is
// dereferenced per symbol.
function codegenCSwitch(ir, opts = {}) {
  const { names, order, sigma, table, accIdx } = codegenCShape(ir);

  const out = [];
  out.push(codegenBanner(ir, '//', { ...opts, style: 'switch' }));
  out.push('');
  out.push('#include <stdbool.h>');
  out.push('');
  out.push('// State indices, in canvas order.');
  out.push('enum {');
  order.forEach((id, i) => out.push(`    ${names.get(id)} = ${i},`));
  out.push('};');
  out.push('');
  out.push('bool automaton_accepts(const char *input) {');
  out.push(`    int state = ${names.get(ir.startId)};`);
  out.push('    for (const char *p = input; *p; p++) {');
  out.push('        switch (state) {');
  order.forEach((id, i) => {
    out.push(`        case ${names.get(id)}:`);
    const live = table[i].map((dest, k) => [sigma[k], dest]).filter(([, dest]) => dest >= 0);
    if (!live.length) {
      out.push('            return false;  // no outgoing transitions');
      return;
    }
    out.push('            switch (*p) {');
    live.forEach(([sym, dest]) => {
      out.push(`            case ${codegenCChar(sym)}: state = ${names.get(order[dest])}; break;`);
    });
    out.push('            default: return false;  // dead: no such transition');
    out.push('            }');
    out.push('            break;');
  });
  out.push('        default: return false;');
  out.push('        }');
  out.push('    }');
  out.push('    switch (state) {');
  if (accIdx.length) {
    accIdx.forEach(i => out.push(`    case ${names.get(order[i])}:`));
    out.push('        return true;');
  }
  out.push('    default:');
  out.push('        return false;');
  out.push('    }');
  out.push('}');
  return out.join('\n');
}

// ── C: struct handle ──────────────────────────────────────────────
// C has no classes, so the class style becomes the pattern C actually
// uses for the same job: a small struct the caller owns, plus functions
// taking a pointer to it. That is what lets input arrive incrementally
// — one byte per interrupt, per read(), per event — rather than as one
// whole string.
function codegenCStruct(ir, opts = {}) {
  const { names, order, sigma, table, accIdx } = codegenCShape(ir);

  const out = [];
  out.push(codegenBanner(ir, '//', {
    ...opts, style: 'class',
    extraNote: 'C has no classes; this is the equivalent struct-and-functions handle.'
  }));
  out.push('');
  out.push('#include <stdbool.h>');
  out.push('#include <stddef.h>');
  out.push('');
  out.push(`#define STATE_COUNT ${order.length}`);
  out.push(`#define SYMBOL_COUNT ${sigma.length}`);
  out.push('');
  out.push('// State indices, in canvas order.');
  out.push('enum {');
  order.forEach((id, i) => out.push(`    ${names.get(id)} = ${i},`));
  out.push('};');
  out.push('');
  out.push(`static const char SYMBOLS[SYMBOL_COUNT] = {${sigma.map(codegenCChar).join(', ')}};`);
  out.push('');
  out.push('// DELTA[state][symbol index]; -1 means no transition (reject).');
  out.push('static const int DELTA[STATE_COUNT][SYMBOL_COUNT] = {');
  table.forEach((row, i) => {
    out.push(`    {${row.map(v => String(v).padStart(2)).join(', ')}},  // ${ir.states[i].name}`);
  });
  out.push('};');
  out.push('');
  out.push(`static const int ACCEPTING[] = {${accIdx.length ? accIdx.join(', ') : '-1'}};`);
  out.push(`static const size_t ACCEPTING_COUNT = ${accIdx.length};`);
  out.push('');
  out.push('typedef struct {');
  out.push('    int state;  // current state, or -1 once the run is dead');
  out.push('} automaton_t;');
  out.push('');
  out.push('static int symbol_index(char c) {');
  out.push('    for (int i = 0; i < SYMBOL_COUNT; i++) {');
  out.push('        if (SYMBOLS[i] == c) return i;');
  out.push('    }');
  out.push('    return -1;');
  out.push('}');
  out.push('');
  out.push('/** Returns the machine to its start configuration. */');
  out.push('void automaton_reset(automaton_t *m) {');
  out.push(`    m->state = ${names.get(ir.startId)};`);
  out.push('}');
  out.push('');
  out.push('/** Consumes one byte. Returns false once the run is dead. */');
  out.push('bool automaton_step(automaton_t *m, char c) {');
  out.push('    if (m->state < 0) return false;');
  out.push('    int s = symbol_index(c);');
  out.push('    if (s < 0) { m->state = -1; return false; }  // not in the alphabet');
  out.push('    m->state = DELTA[m->state][s];');
  out.push('    return m->state >= 0;');
  out.push('}');
  out.push('');
  out.push('bool automaton_is_accepting(const automaton_t *m) {');
  out.push('    if (m->state < 0) return false;');
  out.push('    for (size_t i = 0; i < ACCEPTING_COUNT; i++) {');
  out.push('        if (ACCEPTING[i] == m->state) return true;');
  out.push('    }');
  out.push('    return false;');
  out.push('}');
  out.push('');
  out.push('/** Convenience: run a whole NUL-terminated string. */');
  out.push('bool automaton_accepts(const char *input) {');
  out.push('    automaton_t m;');
  out.push('    automaton_reset(&m);');
  out.push('    for (const char *p = input; *p; p++) {');
  out.push('        if (!automaton_step(&m, *p)) return false;');
  out.push('    }');
  out.push('    return automaton_is_accepting(&m);');
  out.push('}');
  return out.join('\n');
}

// ══════════════════════════════════════════════════════════════════
//  XSTATE
// ══════════════════════════════════════════════════════════════════
//  XState dispatches one event to one target, so a nondeterministic
//  machine has no faithful config — determinise it first.
function codegenXState(ir) {
  const support = codegenSupport(ir);
  if (!support.ok) return codegenUnsupported(support.reason, '//');
  if (codegenIsNondeterministic(ir)) {
    return codegenUnsupported(
      'XState resolves one event to one target, so a nondeterministic machine cannot be expressed '
      + 'directly. Run Algorithms › NFA → DFA (subset construction) first, then export the result.', '//');
  }

  const names = codegenNames(ir);
  const states = {};
  ir.states.forEach(s => {
    const name = names.get(s.id);
    const on = {};
    ir.transitions.filter(t => t.from === s.id).forEach(t => {
      // Event names are the input symbols; XState treats them as opaque strings.
      if (ir.machine === 'Mealy') {
        on[t.symbol] = { target: names.get(t.to), actions: [{ type: 'emit', params: { output: t.output == null ? '' : t.output } }] };
      } else {
        on[t.symbol] = names.get(t.to);
      }
    });
    const node = {};
    if (Object.keys(on).length) node.on = on;
    // Accepting is not an XState concept; carry it as metadata rather than
    // pretending it is a final state, which would halt the machine.
    const meta = {};
    if (s.isAccept) meta.accepting = true;
    if (ir.machine === 'Moore' && s.output != null && s.output !== '') meta.output = s.output;
    if (Object.keys(meta).length) node.meta = meta;
    states[name] = node;
  });

  const config = {
    id: exportIdent(ir.machine, 'automaton').toLowerCase(),
    initial: names.get(ir.startId),
    states
  };

  return [
    codegenBanner(ir, '//'),
    '// Accepting states are marked in `meta.accepting` — XState has no',
    '// accept notion, and a `final` state would stop the machine instead.',
    '',
    `export const machine = ${JSON.stringify(config, null, 2)};`,
    ''
  ].join('\n');
}

// ══════════════════════════════════════════════════════════════════
//  SCXML  (W3C State Chart XML)
// ══════════════════════════════════════════════════════════════════
function codegenSCXML(ir) {
  const support = codegenSupport(ir);
  if (!support.ok) return codegenUnsupported(support.reason, '<!--');

  const names = codegenNames(ir);
  const out = [];
  out.push('<?xml version="1.0" encoding="UTF-8"?>');
  out.push(`<!-- ${codegenBanner(ir, '').trim().split('\n').join(' | ').trim()} -->`);
  out.push('<scxml xmlns="http://www.w3.org/2005/07/scxml" version="1.0"'
    + ` initial="${xmlAttr(names.get(ir.startId))}" datamodel="ecmascript">`);

  ir.states.forEach(s => {
    const name = names.get(s.id);
    const edges = ir.transitions.filter(t => t.from === s.id);
    // Accepting states stay <state>, not <final>: entering a <final> ends
    // the machine, but an accepting state here can still be left.
    const attrs = `id="${xmlAttr(name)}"`;
    if (!edges.length && !s.isAccept && ir.machine !== 'Moore') {
      out.push(`  <state ${attrs}/>`);
      return;
    }
    out.push(`  <state ${attrs}>`);
    if (s.isAccept) out.push('    <datamodel><data id="accepting" expr="true"/></datamodel>');
    if (ir.machine === 'Moore' && s.output != null && s.output !== '') {
      out.push(`    <onentry><log label="output" expr="${xmlAttr(JSON.stringify(s.output))}"/></onentry>`);
    }
    edges.forEach(t => {
      const ev = xmlAttr(t.symbol);
      const target = xmlAttr(names.get(t.to));
      if (ir.machine === 'Mealy') {
        out.push(`    <transition event="${ev}" target="${target}">`);
        out.push(`      <log label="output" expr="${xmlAttr(JSON.stringify(t.output == null ? '' : t.output))}"/>`);
        out.push('    </transition>');
      } else {
        out.push(`    <transition event="${ev}" target="${target}"/>`);
      }
    });
    out.push('  </state>');
  });

  out.push('</scxml>');
  return out.join('\n');
}

// ══════════════════════════════════════════════════════════════════
//  TEST SUITES
// ══════════════════════════════════════════════════════════════════
//  The generated cases come from exportSampleWords, so they are derived
//  from the machine rather than written by hand — the same idea as
//  model-based test generation. Pair with the JavaScript/Python target
//  and the suite runs against generated source.
function codegenJest(ir, opts = {}) {
  const support = codegenSupport(ir);
  if (!support.ok) return codegenUnsupported(support.reason, '//');
  if (codegenIsTransducer(ir)) {
    return codegenUnsupported(
      'Test generation asserts membership in L(M). A transducer has no accept/reject notion '
      + 'unless "transducers accept" is enabled in Settings.', '//');
  }

  const samples = exportSampleWords(opts);
  const acc = samples.accepted.map(w => exportWordText(w, ir));
  const rej = samples.rejected.map(w => exportWordText(w, ir));
  const mod = opts.module || './automaton';

  return [
    codegenBanner(ir, '//'),
    '// Cases are derived from the machine itself, in shortlex order.',
    '',
    `const { accepts } = require(${jsStr(mod)});`,
    '',
    `describe(${jsStr(`L(M) — ${ir.machineLabel}`)}, () => {`,
    acc.length ? `  test.each([\n${acc.map(w => `    ${jsStr(w)},`).join('\n')}\n  ])('accepts %j', (word) => {\n    expect(accepts(word)).toBe(true);\n  });` : '  // no accepted words found within the search budget',
    '',
    rej.length ? `  test.each([\n${rej.map(w => `    ${jsStr(w)},`).join('\n')}\n  ])('rejects %j', (word) => {\n    expect(accepts(word)).toBe(false);\n  });` : '  // no rejected words found within the search budget',
    '});',
    ''
  ].join('\n');
}

function codegenPytest(ir, opts = {}) {
  const support = codegenSupport(ir);
  if (!support.ok) return codegenUnsupported(support.reason, '#');
  if (codegenIsTransducer(ir)) {
    return codegenUnsupported(
      'Test generation asserts membership in L(M). A transducer has no accept/reject notion '
      + 'unless "transducers accept" is enabled in Settings.', '#');
  }

  const samples = exportSampleWords(opts);
  const acc = samples.accepted.map(w => exportWordText(w, ir));
  const rej = samples.rejected.map(w => exportWordText(w, ir));
  const mod = (opts.module || 'automaton').replace(/^\.\//, '').replace(/\.py$/, '');

  const out = [];
  out.push(codegenBanner(ir, '#'));
  out.push('# Cases are derived from the machine itself, in shortlex order.');
  out.push('');
  out.push('import pytest');
  out.push('');
  out.push(`from ${mod} import accepts`);
  out.push('');
  out.push('');
  if (acc.length) {
    out.push(`@pytest.mark.parametrize('word', [\n${acc.map(w => `    ${pyStr(w)},`).join('\n')}\n])`);
    out.push('def test_accepts(word):');
    out.push('    assert accepts(word) is True');
    out.push('');
    out.push('');
  }
  if (rej.length) {
    out.push(`@pytest.mark.parametrize('word', [\n${rej.map(w => `    ${pyStr(w)},`).join('\n')}\n])`);
    out.push('def test_rejects(word):');
    out.push('    assert accepts(word) is False');
    out.push('');
  }
  return out.join('\n');
}

// ══════════════════════════════════════════════════════════════════
//  REGISTRY
// ══════════════════════════════════════════════════════════════════
// Extends the Export dialog built in export-ui.js. Declared here so the
// dialog needs no knowledge of code generation.
// Offered on every language target. The wording is per-language where the
// idiom differs — Python's switch is `match`, and C's class is a struct.
const CODEGEN_STYLE_OPTION = {
  id: 'style', type: 'select', label: 'Shape', def: 'table',
  choices: [['table', 'Transition table'], ['switch', 'Switch statements'], ['class', 'Class']]
};
const CODEGEN_STYLE_OPTION_PY = {
  ...CODEGEN_STYLE_OPTION,
  choices: [['table', 'Transition table'], ['switch', 'match / case'], ['class', 'Class']]
};
const CODEGEN_STYLE_OPTION_C = {
  ...CODEGEN_STYLE_OPTION,
  choices: [['table', 'Transition table'], ['switch', 'Switch statements'], ['class', 'Struct + functions']]
};

if (typeof ExportFormats !== 'undefined') {
  ExportFormats['code-js'] = {
    label: 'JavaScript', group: 'Code', ext: 'js', mime: 'text/javascript',
    blurb: 'Exports <code>accepts()</code> as a CommonJS module, whichever shape you pick.',
    options: [CODEGEN_STYLE_OPTION], build: (ir, o) => codegenJavaScript(ir, o)
  };
  ExportFormats['code-py'] = {
    label: 'Python', group: 'Code', ext: 'py', mime: 'text/x-python',
    blurb: 'Module-level <code>accepts()</code>. The <code>match</code> shape needs Python 3.10+.',
    options: [CODEGEN_STYLE_OPTION_PY], build: (ir, o) => codegenPython(ir, o)
  };
  ExportFormats['code-java'] = {
    label: 'Java', group: 'Code', ext: 'java', mime: 'text/x-java-source',
    blurb: 'Static <code>accepts()</code>; the class shape adds <code>reset()</code>/<code>step()</code>.',
    options: [
      CODEGEN_STYLE_OPTION,
      { id: 'className', type: 'text', label: 'Class name', def: 'Automaton' }
    ],
    extFor: () => 'java',
    build: (ir, o) => codegenJava(ir, o)
  };
  ExportFormats['code-c'] = {
    label: 'C', group: 'Code', ext: 'c', mime: 'text/x-csrc',
    blurb: 'DFAs over single-byte alphabets only. The struct shape accepts input a byte at a time.',
    options: [CODEGEN_STYLE_OPTION_C], build: (ir, o) => codegenC(ir, o)
  };
  ExportFormats['code-xstate'] = {
    label: 'XState config', group: 'Code', ext: 'js', mime: 'text/javascript',
    blurb: 'Statechart config for XState v5. Deterministic machines only.',
    options: [], build: ir => codegenXState(ir)
  };
  ExportFormats['code-scxml'] = {
    label: 'SCXML', group: 'Code', ext: 'scxml', mime: 'application/scxml+xml',
    blurb: 'W3C State Chart XML, for interop with SCXML runtimes.',
    options: [], build: ir => codegenSCXML(ir)
  };
  ExportFormats['test-jest'] = {
    label: 'Jest test suite', group: 'Tests', ext: 'test.js', mime: 'text/javascript',
    blurb: 'Cases derived from L(M) — pair with the JavaScript target.',
    options: [
      { id: 'module', type: 'text', label: 'Import from', def: './automaton' },
      { id: 'accepted', type: 'number', label: 'Accepted cases', def: 15, min: 0, max: 200, step: 5 },
      { id: 'rejected', type: 'number', label: 'Rejected cases', def: 15, min: 0, max: 200, step: 5 },
      { id: 'maxLength', type: 'number', label: 'Max length', def: 8, min: 1, max: 20, step: 1 }
    ],
    build: (ir, o) => codegenJest(ir, o)
  };
  ExportFormats['test-pytest'] = {
    label: 'pytest suite', group: 'Tests', ext: 'py', mime: 'text/x-python',
    blurb: 'Cases derived from L(M) — pair with the Python target.',
    options: [
      { id: 'module', type: 'text', label: 'Import from', def: 'automaton' },
      { id: 'accepted', type: 'number', label: 'Accepted cases', def: 15, min: 0, max: 200, step: 5 },
      { id: 'rejected', type: 'number', label: 'Rejected cases', def: 15, min: 0, max: 200, step: 5 },
      { id: 'maxLength', type: 'number', label: 'Max length', def: 8, min: 1, max: 20, step: 1 }
    ],
    build: (ir, o) => codegenPytest(ir, o)
  };
}
