// ══════════════════════════════════════════════════════════════════
//  CODE GENERATION
// ══════════════════════════════════════════════════════════════════
//  Turns a drawn machine into source you can run, a statechart config
//  you can hand to a runtime, or a test suite you can drop into a
//  project.
//
//  Scope is deliberate. Generating a recogniser is only worth doing if
//  the generated thing decides the same language the canvas does, so
//  these emitters cover exactly the models whose runtime semantics
//  translate faithfully to a few dozen lines of host code:
//
//    DFA            deterministic walk over a transition table
//    NFA, ε-NFA     subset simulation with an ε-closure
//    Moore, Mealy   deterministic walk that emits output
//
//  Stack and tape machines are refused rather than approximated. A
//  "PDA in Python" that silently drops nondeterminism, or a TM whose
//  generated tape is finite, is worse than no output at all — it looks
//  authoritative and is wrong. codegenSupport() is the single place
//  that decision lives, and every emitter routes through it.
// ══════════════════════════════════════════════════════════════════

const CODEGEN_MODELS = new Set(['DFA', 'NFA', 'ε-NFA', 'Moore', 'Mealy']);

function codegenSupport(ir) {
  if (!ir.states.length) return { ok: false, reason: 'The canvas is empty.' };
  if (!ir.startId) return { ok: false, reason: 'This machine has no start state.' };
  if (!CODEGEN_MODELS.has(ir.machine)) {
    return {
      ok: false,
      reason: `Code generation covers DFA, NFA, ε-NFA, Moore and Mealy machines. `
        + `${ir.machineLabel} needs a stack or a tape, and a generated recogniser that quietly `
        + `dropped either would decide a different language than the one on the canvas.`
    };
  }
  return { ok: true };
}

function codegenIsTransducer(ir) { return ir.machine === 'Moore' || ir.machine === 'Mealy'; }
function codegenIsNondeterministic(ir) { return ir.machine === 'NFA' || ir.machine === 'ε-NFA'; }

// ── shared shaping ────────────────────────────────────────────────
// δ as name → symbol → [target names]. Built once; every language
// emitter walks this rather than the transition array.
function codegenDelta(ir, names) {
  const delta = new Map();
  ir.states.forEach(s => delta.set(names.get(s.id), new Map()));
  ir.transitions.forEach(t => {
    const row = delta.get(names.get(t.from));
    if (!row) return;
    if (!row.has(t.symbol)) row.set(t.symbol, []);
    const dest = names.get(t.to);
    // Mealy carries the emitted symbol on the edge, so the row holds a
    // pair rather than a bare target.
    row.get(t.symbol).push(ir.machine === 'Mealy'
      ? { to: dest, out: t.output == null ? '' : t.output }
      : dest);
  });
  return delta;
}

function codegenNames(ir) {
  return exportUniqueIdents(ir.states, s => s);
}

function codegenBanner(ir, prefix) {
  const lines = [
    `Generated by Automata Playground from a ${ir.machineLabel}.`,
    `States: ${ir.states.length} · Σ = {${ir.sigma.join(', ')}}`,
    ir.isSymbolic
      ? 'Input is read one character at a time.'
      : 'Σ contains multi-character symbols — input is split on whitespace.'
  ];
  return lines.map(l => `${prefix} ${l}`).join('\n');
}

function codegenUnsupported(reason, prefix) {
  return `${prefix} Cannot generate code for this machine.\n${prefix}\n`
    + reason.replace(/(.{1,68})(\s|$)/g, (m, chunk) => `${prefix} ${chunk.trim()}\n`);
}

// ── string escaping, per host language ────────────────────────────
function jsStr(s) {
  return JSON.stringify(String(s == null ? '' : s));
}
function pyStr(s) {
  return "'" + String(s == null ? '' : s)
    .replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n') + "'";
}
function javaStr(s) {
  return '"' + String(s == null ? '' : s)
    .replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n') + '"';
}
function xmlAttr(s) {
  return String(s == null ? '' : s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&apos;');
}

// ══════════════════════════════════════════════════════════════════
//  JAVASCRIPT
// ══════════════════════════════════════════════════════════════════
function codegenJavaScript(ir) {
  const support = codegenSupport(ir);
  if (!support.ok) return codegenUnsupported(support.reason, '//');

  const names = codegenNames(ir);
  const delta = codegenDelta(ir, names);
  const start = names.get(ir.startId);
  const accepting = ir.states.filter(s => s.isAccept).map(s => names.get(s.id));
  const eps = ir.sym.eps;
  const nd = codegenIsNondeterministic(ir);

  const out = [];
  out.push(codegenBanner(ir, '//'));
  out.push('');

  // δ literal
  out.push('const DELTA = {');
  [...delta.entries()].forEach(([from, row]) => {
    if (!row.size) { out.push(`  ${jsStr(from)}: {},`); return; }
    const cells = [...row.entries()].map(([sym, dests]) => {
      if (ir.machine === 'Mealy') {
        const d = dests[0];
        return `${jsStr(sym)}: { to: ${jsStr(d.to)}, out: ${jsStr(d.out)} }`;
      }
      return `${jsStr(sym)}: ${nd ? `[${dests.map(jsStr).join(', ')}]` : jsStr(dests[0])}`;
    });
    out.push(`  ${jsStr(from)}: { ${cells.join(', ')} },`);
  });
  out.push('};');
  out.push('');
  out.push(`const START = ${jsStr(start)};`);
  if (!codegenIsTransducer(ir)) {
    out.push(`const ACCEPTING = new Set([${accepting.map(jsStr).join(', ')}]);`);
  }
  if (ir.machine === 'Moore') {
    const outputs = ir.states.map(s => `  ${jsStr(names.get(s.id))}: ${jsStr(s.output == null ? '' : s.output)},`);
    out.push('');
    out.push('// Moore output is a property of the state, not the edge.');
    out.push('const OUTPUT = {');
    outputs.forEach(l => out.push(l));
    out.push('};');
  }
  out.push('');
  out.push('function tokenize(input) {');
  out.push(ir.isSymbolic
    ? '  return Array.from(input);'
    : '  return input.split(/\\s+/).filter(Boolean);');
  out.push('}');
  out.push('');

  if (nd) {
    out.push(`const EPSILON = ${jsStr(eps)};`);
    out.push('');
    out.push('function epsilonClosure(states) {');
    out.push('  const seen = new Set(states);');
    out.push('  const stack = [...states];');
    out.push('  while (stack.length) {');
    out.push('    const s = stack.pop();');
    out.push('    for (const t of (DELTA[s]?.[EPSILON] ?? [])) {');
    out.push('      if (!seen.has(t)) { seen.add(t); stack.push(t); }');
    out.push('    }');
    out.push('  }');
    out.push('  return seen;');
    out.push('}');
    out.push('');
    out.push('function accepts(input) {');
    out.push('  let current = epsilonClosure([START]);');
    out.push('  for (const symbol of tokenize(input)) {');
    out.push('    const next = new Set();');
    out.push('    for (const s of current) {');
    out.push('      for (const t of (DELTA[s]?.[symbol] ?? [])) next.add(t);');
    out.push('    }');
    out.push('    current = epsilonClosure(next);');
    out.push('    if (!current.size) return false;');
    out.push('  }');
    out.push('  for (const s of current) if (ACCEPTING.has(s)) return true;');
    out.push('  return false;');
    out.push('}');
  } else if (ir.machine === 'Mealy') {
    out.push('function transduce(input) {');
    out.push('  let state = START;');
    out.push('  const output = [];');
    out.push('  for (const symbol of tokenize(input)) {');
    out.push('    const edge = DELTA[state]?.[symbol];');
    out.push('    if (edge === undefined) return null; // undefined transition');
    out.push('    output.push(edge.out);');
    out.push('    state = edge.to;');
    out.push('  }');
    out.push(`  return output.join(${ir.isSymbolic ? "''" : "' '"});`);
    out.push('}');
  } else if (ir.machine === 'Moore') {
    out.push('function transduce(input) {');
    out.push('  let state = START;');
    out.push('  const output = [OUTPUT[state]];');
    out.push('  for (const symbol of tokenize(input)) {');
    out.push('    const next = DELTA[state]?.[symbol];');
    out.push('    if (next === undefined) return null; // undefined transition');
    out.push('    state = next;');
    out.push('    output.push(OUTPUT[state]);');
    out.push('  }');
    out.push(`  return output.join(${ir.isSymbolic ? "''" : "' '"});`);
    out.push('}');
  } else {
    out.push('function accepts(input) {');
    out.push('  let state = START;');
    out.push('  for (const symbol of tokenize(input)) {');
    out.push('    const next = DELTA[state]?.[symbol];');
    out.push('    if (next === undefined) return false; // dead: no such transition');
    out.push('    state = next;');
    out.push('  }');
    out.push('  return ACCEPTING.has(state);');
    out.push('}');
  }

  out.push('');
  const api = codegenIsTransducer(ir) ? 'transduce' : 'accepts';
  out.push(`if (typeof module !== 'undefined') module.exports = { ${api}, DELTA, START };`);
  return out.join('\n');
}

// ══════════════════════════════════════════════════════════════════
//  PYTHON
// ══════════════════════════════════════════════════════════════════
function codegenPython(ir) {
  const support = codegenSupport(ir);
  if (!support.ok) return codegenUnsupported(support.reason, '#');

  const names = codegenNames(ir);
  const delta = codegenDelta(ir, names);
  const start = names.get(ir.startId);
  const accepting = ir.states.filter(s => s.isAccept).map(s => names.get(s.id));
  const nd = codegenIsNondeterministic(ir);

  const out = [];
  out.push(codegenBanner(ir, '#'));
  out.push('');
  out.push('DELTA = {');
  [...delta.entries()].forEach(([from, row]) => {
    if (!row.size) { out.push(`    ${pyStr(from)}: {},`); return; }
    const cells = [...row.entries()].map(([sym, dests]) => {
      if (ir.machine === 'Mealy') {
        const d = dests[0];
        return `${pyStr(sym)}: (${pyStr(d.to)}, ${pyStr(d.out)})`;
      }
      return `${pyStr(sym)}: ${nd ? `(${dests.map(pyStr).join(', ')}${dests.length === 1 ? ',' : ''})` : pyStr(dests[0])}`;
    });
    out.push(`    ${pyStr(from)}: {${cells.join(', ')}},`);
  });
  out.push('}');
  out.push('');
  out.push(`START = ${pyStr(start)}`);
  if (!codegenIsTransducer(ir)) {
    out.push(`ACCEPTING = frozenset({${accepting.map(pyStr).join(', ')}})`);
  }
  if (ir.machine === 'Moore') {
    out.push('');
    out.push('# Moore output is a property of the state, not the edge.');
    out.push('OUTPUT = {');
    ir.states.forEach(s => out.push(`    ${pyStr(names.get(s.id))}: ${pyStr(s.output == null ? '' : s.output)},`));
    out.push('}');
  }
  out.push('');
  out.push('def tokenize(text):');
  out.push(ir.isSymbolic ? '    return list(text)' : '    return text.split()');
  out.push('');
  out.push('');

  if (nd) {
    out.push(`EPSILON = ${pyStr(ir.sym.eps)}`);
    out.push('');
    out.push('');
    out.push('def epsilon_closure(states):');
    out.push('    seen = set(states)');
    out.push('    stack = list(states)');
    out.push('    while stack:');
    out.push('        state = stack.pop()');
    out.push('        for target in DELTA.get(state, {}).get(EPSILON, ()):');
    out.push('            if target not in seen:');
    out.push('                seen.add(target)');
    out.push('                stack.append(target)');
    out.push('    return seen');
    out.push('');
    out.push('');
    out.push('def accepts(text):');
    out.push('    current = epsilon_closure({START})');
    out.push('    for symbol in tokenize(text):');
    out.push('        nxt = set()');
    out.push('        for state in current:');
    out.push('            nxt.update(DELTA.get(state, {}).get(symbol, ()))');
    out.push('        current = epsilon_closure(nxt)');
    out.push('        if not current:');
    out.push('            return False');
    out.push('    return bool(current & ACCEPTING)');
  } else if (ir.machine === 'Mealy') {
    out.push('def transduce(text):');
    out.push('    state = START');
    out.push('    output = []');
    out.push('    for symbol in tokenize(text):');
    out.push('        edge = DELTA.get(state, {}).get(symbol)');
    out.push('        if edge is None:');
    out.push('            return None  # undefined transition');
    out.push('        output.append(edge[1])');
    out.push('        state = edge[0]');
    out.push(`    return ${ir.isSymbolic ? "''" : "' '"}.join(output)`);
  } else if (ir.machine === 'Moore') {
    out.push('def transduce(text):');
    out.push('    state = START');
    out.push('    output = [OUTPUT[state]]');
    out.push('    for symbol in tokenize(text):');
    out.push('        nxt = DELTA.get(state, {}).get(symbol)');
    out.push('        if nxt is None:');
    out.push('            return None  # undefined transition');
    out.push('        state = nxt');
    out.push('        output.append(OUTPUT[state])');
    out.push(`    return ${ir.isSymbolic ? "''" : "' '"}.join(output)`);
  } else {
    out.push('def accepts(text):');
    out.push('    state = START');
    out.push('    for symbol in tokenize(text):');
    out.push('        nxt = DELTA.get(state, {}).get(symbol)');
    out.push('        if nxt is None:');
    out.push('            return False  # dead: no such transition');
    out.push('        state = nxt');
    out.push('    return state in ACCEPTING');
  }
  out.push('');
  return out.join('\n');
}

// ══════════════════════════════════════════════════════════════════
//  JAVA
// ══════════════════════════════════════════════════════════════════
function codegenJava(ir, opts = {}) {
  const support = codegenSupport(ir);
  if (!support.ok) return codegenUnsupported(support.reason, '//');

  const cls = exportIdent(opts.className || 'Automaton', 'Automaton');
  const names = codegenNames(ir);
  const delta = codegenDelta(ir, names);
  const nd = codegenIsNondeterministic(ir);

  const out = [];
  out.push(codegenBanner(ir, '//'));
  out.push('');
  out.push('import java.util.*;');
  out.push('');
  out.push(`public final class ${cls} {`);
  out.push(`    private static final String START = ${javaStr(names.get(ir.startId))};`);

  if (!codegenIsTransducer(ir)) {
    const acc = ir.states.filter(s => s.isAccept).map(s => javaStr(names.get(s.id)));
    out.push(`    private static final Set<String> ACCEPTING = new HashSet<>(Arrays.asList(${acc.join(', ')}));`);
  }

  // Java has no map literal; the table is filled in a static block.
  const valueType = nd ? 'List<String>' : (ir.machine === 'Mealy' ? 'String[]' : 'String');
  out.push(`    private static final Map<String, Map<String, ${valueType}>> DELTA = new HashMap<>();`);
  if (ir.machine === 'Moore') {
    out.push('    private static final Map<String, String> OUTPUT = new HashMap<>();');
  }
  out.push('');
  out.push('    static {');
  out.push(`        Map<String, ${valueType}> row;`);
  [...delta.entries()].forEach(([from, row]) => {
    out.push('        row = new HashMap<>();');
    [...row.entries()].forEach(([sym, dests]) => {
      if (ir.machine === 'Mealy') {
        const d = dests[0];
        out.push(`        row.put(${javaStr(sym)}, new String[]{${javaStr(d.to)}, ${javaStr(d.out)}});`);
      } else if (nd) {
        out.push(`        row.put(${javaStr(sym)}, Arrays.asList(${dests.map(javaStr).join(', ')}));`);
      } else {
        out.push(`        row.put(${javaStr(sym)}, ${javaStr(dests[0])});`);
      }
    });
    out.push(`        DELTA.put(${javaStr(from)}, row);`);
  });
  if (ir.machine === 'Moore') {
    ir.states.forEach(s => {
      out.push(`        OUTPUT.put(${javaStr(names.get(s.id))}, ${javaStr(s.output == null ? '' : s.output)});`);
    });
  }
  out.push('    }');
  out.push('');
  out.push('    private static List<String> tokenize(String input) {');
  if (ir.isSymbolic) {
    out.push('        List<String> out = new ArrayList<>();');
    out.push('        for (int i = 0; i < input.length(); ) {');
    out.push('            int cp = input.codePointAt(i);');
    out.push('            out.add(new String(Character.toChars(cp)));');
    out.push('            i += Character.charCount(cp);');
    out.push('        }');
    out.push('        return out;');
  } else {
    out.push('        List<String> out = new ArrayList<>();');
    out.push('        for (String part : input.trim().split("\\\\s+")) {');
    out.push('            if (!part.isEmpty()) out.add(part);');
    out.push('        }');
    out.push('        return out;');
  }
  out.push('    }');
  out.push('');

  if (nd) {
    out.push(`    private static final String EPSILON = ${javaStr(ir.sym.eps)};`);
    out.push('');
    out.push('    private static Set<String> epsilonClosure(Collection<String> states) {');
    out.push('        Set<String> seen = new HashSet<>(states);');
    out.push('        Deque<String> stack = new ArrayDeque<>(states);');
    out.push('        while (!stack.isEmpty()) {');
    out.push('            Map<String, List<String>> row = DELTA.get(stack.pop());');
    out.push('            if (row == null) continue;');
    out.push('            for (String target : row.getOrDefault(EPSILON, Collections.emptyList())) {');
    out.push('                if (seen.add(target)) stack.push(target);');
    out.push('            }');
    out.push('        }');
    out.push('        return seen;');
    out.push('    }');
    out.push('');
    out.push('    public static boolean accepts(String input) {');
    out.push('        Set<String> current = epsilonClosure(Collections.singletonList(START));');
    out.push('        for (String symbol : tokenize(input)) {');
    out.push('            Set<String> next = new HashSet<>();');
    out.push('            for (String state : current) {');
    out.push('                Map<String, List<String>> row = DELTA.get(state);');
    out.push('                if (row != null) next.addAll(row.getOrDefault(symbol, Collections.emptyList()));');
    out.push('            }');
    out.push('            current = epsilonClosure(next);');
    out.push('            if (current.isEmpty()) return false;');
    out.push('        }');
    out.push('        for (String state : current) if (ACCEPTING.contains(state)) return true;');
    out.push('        return false;');
    out.push('    }');
  } else if (codegenIsTransducer(ir)) {
    const sep = ir.isSymbolic ? '""' : '" "';
    out.push(`    private static final String SEP = ${sep};`);
    out.push('');
    out.push('    public static String transduce(String input) {');
    out.push('        String state = START;');
    out.push('        StringBuilder out = new StringBuilder();');
    if (ir.machine === 'Mealy') {
      // A `first` flag rather than a length check: an empty emitted symbol
      // would otherwise swallow the separator before the one after it.
      out.push('        boolean first = true;');
      out.push('        for (String symbol : tokenize(input)) {');
      out.push('            Map<String, String[]> row = DELTA.get(state);');
      out.push('            String[] edge = row == null ? null : row.get(symbol);');
      out.push('            if (edge == null) return null; // undefined transition');
      out.push('            if (!first) out.append(SEP);');
      out.push('            out.append(edge[1]);');
      out.push('            state = edge[0];');
      out.push('            first = false;');
      out.push('        }');
    } else {
      out.push('        out.append(OUTPUT.get(state));');
      out.push('        for (String symbol : tokenize(input)) {');
      out.push('            Map<String, String> row = DELTA.get(state);');
      out.push('            String next = row == null ? null : row.get(symbol);');
      out.push('            if (next == null) return null; // undefined transition');
      out.push('            state = next;');
      out.push('            out.append(SEP).append(OUTPUT.get(state));');
      out.push('        }');
    }
    out.push('        return out.toString();');
    out.push('    }');
  } else {
    out.push('    public static boolean accepts(String input) {');
    out.push('        String state = START;');
    out.push('        for (String symbol : tokenize(input)) {');
    out.push('            Map<String, String> row = DELTA.get(state);');
    out.push('            String next = row == null ? null : row.get(symbol);');
    out.push('            if (next == null) return false; // dead: no such transition');
    out.push('            state = next;');
    out.push('        }');
    out.push('        return ACCEPTING.contains(state);');
    out.push('    }');
  }

  out.push('}');
  return out.join('\n');
}

// ══════════════════════════════════════════════════════════════════
//  C
// ══════════════════════════════════════════════════════════════════
//  Narrower than the others on purpose. C has no string map, so the
//  clean, genuinely idiomatic output is a dense table indexed by state
//  and symbol — which needs every symbol to be one byte. Word-length
//  alphabets and nondeterminism both push this into building a hash
//  map and a subset simulator in C, and the result would be neither
//  readable nor obviously correct.
function codegenC(ir) {
  const support = codegenSupport(ir);
  if (!support.ok) return codegenUnsupported(support.reason, '/*');

  if (ir.machine !== 'DFA') {
    return codegenUnsupported(
      `C generation covers deterministic finite automata only. ${ir.machineLabel} needs either a `
      + `subset simulation or an output function, which in C means hand-rolling a string map — `
      + `use the JavaScript, Python or Java target instead.`, '//');
  }
  const oneByte = ir.sigma.every(s => [...s].length === 1 && s.charCodeAt(0) < 128);
  if (!oneByte) {
    return codegenUnsupported(
      'C generation needs every input symbol to be a single ASCII character, because the '
      + 'transition table is indexed directly by symbol. This alphabet has multi-character or '
      + 'non-ASCII symbols — use the JavaScript, Python or Java target instead.', '//');
  }

  const names = exportUniqueIdents(ir.states, s => s.toUpperCase());
  const order = ir.states.map(s => s.id);
  const idx = new Map(order.map((id, i) => [id, i]));
  const sigma = [...ir.sigma].sort();

  // -1 is the dead state: no transition on this symbol.
  const table = order.map(id => sigma.map(sym => {
    const t = ir.transitions.find(x => x.from === id && x.symbol === sym);
    return t ? idx.get(t.to) : -1;
  }));

  const out = [];
  out.push(codegenBanner(ir, '//'));
  out.push('');
  out.push('#include <stdbool.h>');
  out.push('#include <stddef.h>');
  out.push('');
  out.push(`#define STATE_COUNT ${order.length}`);
  out.push(`#define SYMBOL_COUNT ${sigma.length}`);
  out.push('');
  out.push('// State indices, in canvas order.');
  order.forEach((id, i) => out.push(`#define ${names.get(id)} ${i}`));
  out.push('');
  out.push(`static const char SYMBOLS[SYMBOL_COUNT] = {${sigma.map(s => `'${s === "'" ? "\\'" : s === '\\' ? '\\\\' : s}'`).join(', ')}};`);
  out.push('');
  out.push('// DELTA[state][symbol index]; -1 means no transition (reject).');
  out.push('static const int DELTA[STATE_COUNT][SYMBOL_COUNT] = {');
  table.forEach((row, i) => {
    out.push(`    {${row.map(v => String(v).padStart(2)).join(', ')}},  // ${ir.states[i].name}`);
  });
  out.push('};');
  out.push('');
  const accIdx = ir.states.filter(s => s.isAccept).map(s => idx.get(s.id));
  out.push(`static const int ACCEPTING[] = {${accIdx.length ? accIdx.join(', ') : '-1'}};`);
  out.push(`static const size_t ACCEPTING_COUNT = ${accIdx.length};`);
  out.push('');
  out.push('static int symbol_index(char c) {');
  out.push('    for (int i = 0; i < SYMBOL_COUNT; i++) {');
  out.push('        if (SYMBOLS[i] == c) return i;');
  out.push('    }');
  out.push('    return -1;');
  out.push('}');
  out.push('');
  out.push('bool automaton_accepts(const char *input) {');
  out.push(`    int state = ${names.get(ir.startId)};`);
  out.push('    for (const char *p = input; *p; p++) {');
  out.push('        int s = symbol_index(*p);');
  out.push('        if (s < 0) return false;  // symbol not in the alphabet');
  out.push('        state = DELTA[state][s];');
  out.push('        if (state < 0) return false;  // dead: no such transition');
  out.push('    }');
  out.push('    for (size_t i = 0; i < ACCEPTING_COUNT; i++) {');
  out.push('        if (ACCEPTING[i] == state) return true;');
  out.push('    }');
  out.push('    return false;');
  out.push('}');
  return out.join('\n');
}

// ══════════════════════════════════════════════════════════════════
//  XSTATE
// ══════════════════════════════════════════════════════════════════
//  XState dispatches one event to one target, so a nondeterministic
//  machine has no faithful config — determinise it first.
function codegenXState(ir) {
  const support = codegenSupport(ir);
  if (!support.ok) return codegenUnsupported(support.reason, '//');
  if (codegenIsNondeterministic(ir)) {
    return codegenUnsupported(
      'XState resolves one event to one target, so a nondeterministic machine cannot be expressed '
      + 'directly. Run Algorithms › NFA → DFA (subset construction) first, then export the result.', '//');
  }

  const names = codegenNames(ir);
  const states = {};
  ir.states.forEach(s => {
    const name = names.get(s.id);
    const on = {};
    ir.transitions.filter(t => t.from === s.id).forEach(t => {
      // Event names are the input symbols; XState treats them as opaque strings.
      if (ir.machine === 'Mealy') {
        on[t.symbol] = { target: names.get(t.to), actions: [{ type: 'emit', params: { output: t.output == null ? '' : t.output } }] };
      } else {
        on[t.symbol] = names.get(t.to);
      }
    });
    const node = {};
    if (Object.keys(on).length) node.on = on;
    // Accepting is not an XState concept; carry it as metadata rather than
    // pretending it is a final state, which would halt the machine.
    const meta = {};
    if (s.isAccept) meta.accepting = true;
    if (ir.machine === 'Moore' && s.output != null && s.output !== '') meta.output = s.output;
    if (Object.keys(meta).length) node.meta = meta;
    states[name] = node;
  });

  const config = {
    id: exportIdent(ir.machine, 'automaton').toLowerCase(),
    initial: names.get(ir.startId),
    states
  };

  return [
    codegenBanner(ir, '//'),
    '// Accepting states are marked in `meta.accepting` — XState has no',
    '// accept notion, and a `final` state would stop the machine instead.',
    '',
    `export const machine = ${JSON.stringify(config, null, 2)};`,
    ''
  ].join('\n');
}

// ══════════════════════════════════════════════════════════════════
//  SCXML  (W3C State Chart XML)
// ══════════════════════════════════════════════════════════════════
function codegenSCXML(ir) {
  const support = codegenSupport(ir);
  if (!support.ok) return codegenUnsupported(support.reason, '<!--');

  const names = codegenNames(ir);
  const out = [];
  out.push('<?xml version="1.0" encoding="UTF-8"?>');
  out.push(`<!-- ${codegenBanner(ir, '').trim().split('\n').join(' | ').trim()} -->`);
  out.push('<scxml xmlns="http://www.w3.org/2005/07/scxml" version="1.0"'
    + ` initial="${xmlAttr(names.get(ir.startId))}" datamodel="ecmascript">`);

  ir.states.forEach(s => {
    const name = names.get(s.id);
    const edges = ir.transitions.filter(t => t.from === s.id);
    // Accepting states stay <state>, not <final>: entering a <final> ends
    // the machine, but an accepting state here can still be left.
    const attrs = `id="${xmlAttr(name)}"`;
    if (!edges.length && !s.isAccept && ir.machine !== 'Moore') {
      out.push(`  <state ${attrs}/>`);
      return;
    }
    out.push(`  <state ${attrs}>`);
    if (s.isAccept) out.push('    <datamodel><data id="accepting" expr="true"/></datamodel>');
    if (ir.machine === 'Moore' && s.output != null && s.output !== '') {
      out.push(`    <onentry><log label="output" expr="${xmlAttr(JSON.stringify(s.output))}"/></onentry>`);
    }
    edges.forEach(t => {
      const ev = xmlAttr(t.symbol);
      const target = xmlAttr(names.get(t.to));
      if (ir.machine === 'Mealy') {
        out.push(`    <transition event="${ev}" target="${target}">`);
        out.push(`      <log label="output" expr="${xmlAttr(JSON.stringify(t.output == null ? '' : t.output))}"/>`);
        out.push('    </transition>');
      } else {
        out.push(`    <transition event="${ev}" target="${target}"/>`);
      }
    });
    out.push('  </state>');
  });

  out.push('</scxml>');
  return out.join('\n');
}

// ══════════════════════════════════════════════════════════════════
//  TEST SUITES
// ══════════════════════════════════════════════════════════════════
//  The generated cases come from exportSampleWords, so they are derived
//  from the machine rather than written by hand — the same idea as
//  model-based test generation. Pair with the JavaScript/Python target
//  and the suite runs against generated source.
function codegenJest(ir, opts = {}) {
  const support = codegenSupport(ir);
  if (!support.ok) return codegenUnsupported(support.reason, '//');
  if (codegenIsTransducer(ir)) {
    return codegenUnsupported(
      'Test generation asserts membership in L(M). A transducer has no accept/reject notion '
      + 'unless "transducers accept" is enabled in Settings.', '//');
  }

  const samples = exportSampleWords(opts);
  const acc = samples.accepted.map(w => exportWordText(w, ir));
  const rej = samples.rejected.map(w => exportWordText(w, ir));
  const mod = opts.module || './automaton';

  return [
    codegenBanner(ir, '//'),
    '// Cases are derived from the machine itself, in shortlex order.',
    '',
    `const { accepts } = require(${jsStr(mod)});`,
    '',
    `describe(${jsStr(`L(M) — ${ir.machineLabel}`)}, () => {`,
    acc.length ? `  test.each([\n${acc.map(w => `    ${jsStr(w)},`).join('\n')}\n  ])('accepts %j', (word) => {\n    expect(accepts(word)).toBe(true);\n  });` : '  // no accepted words found within the search budget',
    '',
    rej.length ? `  test.each([\n${rej.map(w => `    ${jsStr(w)},`).join('\n')}\n  ])('rejects %j', (word) => {\n    expect(accepts(word)).toBe(false);\n  });` : '  // no rejected words found within the search budget',
    '});',
    ''
  ].join('\n');
}

function codegenPytest(ir, opts = {}) {
  const support = codegenSupport(ir);
  if (!support.ok) return codegenUnsupported(support.reason, '#');
  if (codegenIsTransducer(ir)) {
    return codegenUnsupported(
      'Test generation asserts membership in L(M). A transducer has no accept/reject notion '
      + 'unless "transducers accept" is enabled in Settings.', '#');
  }

  const samples = exportSampleWords(opts);
  const acc = samples.accepted.map(w => exportWordText(w, ir));
  const rej = samples.rejected.map(w => exportWordText(w, ir));
  const mod = (opts.module || 'automaton').replace(/^\.\//, '').replace(/\.py$/, '');

  const out = [];
  out.push(codegenBanner(ir, '#'));
  out.push('# Cases are derived from the machine itself, in shortlex order.');
  out.push('');
  out.push('import pytest');
  out.push('');
  out.push(`from ${mod} import accepts`);
  out.push('');
  out.push('');
  if (acc.length) {
    out.push(`@pytest.mark.parametrize('word', [\n${acc.map(w => `    ${pyStr(w)},`).join('\n')}\n])`);
    out.push('def test_accepts(word):');
    out.push('    assert accepts(word) is True');
    out.push('');
    out.push('');
  }
  if (rej.length) {
    out.push(`@pytest.mark.parametrize('word', [\n${rej.map(w => `    ${pyStr(w)},`).join('\n')}\n])`);
    out.push('def test_rejects(word):');
    out.push('    assert accepts(word) is False');
    out.push('');
  }
  return out.join('\n');
}

// ══════════════════════════════════════════════════════════════════
//  REGISTRY
// ══════════════════════════════════════════════════════════════════
// Extends the Export dialog built in export-ui.js. Declared here so the
// dialog needs no knowledge of code generation.
if (typeof ExportFormats !== 'undefined') {
  ExportFormats['code-js'] = {
    label: 'JavaScript', group: 'Code', ext: 'js', mime: 'text/javascript',
    blurb: 'A transition table and a recogniser. Exports <code>accepts()</code> as a CommonJS module.',
    options: [], build: ir => codegenJavaScript(ir)
  };
  ExportFormats['code-py'] = {
    label: 'Python', group: 'Code', ext: 'py', mime: 'text/x-python',
    blurb: 'Dict-based transition table with an <code>accepts()</code> function.',
    options: [], build: ir => codegenPython(ir)
  };
  ExportFormats['code-java'] = {
    label: 'Java', group: 'Code', ext: 'java', mime: 'text/x-java-source',
    options: [{ id: 'className', type: 'text', label: 'Class name', def: 'Automaton' }],
    extFor: () => 'java',
    build: (ir, o) => codegenJava(ir, o)
  };
  ExportFormats['code-c'] = {
    label: 'C', group: 'Code', ext: 'c', mime: 'text/x-csrc',
    blurb: 'A dense <code>DELTA[state][symbol]</code> table. DFAs over single-byte alphabets only.',
    options: [], build: ir => codegenC(ir)
  };
  ExportFormats['code-xstate'] = {
    label: 'XState config', group: 'Code', ext: 'js', mime: 'text/javascript',
    blurb: 'Statechart config for XState v5. Deterministic machines only.',
    options: [], build: ir => codegenXState(ir)
  };
  ExportFormats['code-scxml'] = {
    label: 'SCXML', group: 'Code', ext: 'scxml', mime: 'application/scxml+xml',
    blurb: 'W3C State Chart XML, for interop with SCXML runtimes.',
    options: [], build: ir => codegenSCXML(ir)
  };
  ExportFormats['test-jest'] = {
    label: 'Jest test suite', group: 'Tests', ext: 'test.js', mime: 'text/javascript',
    blurb: 'Cases derived from L(M) — pair with the JavaScript target.',
    options: [
      { id: 'module', type: 'text', label: 'Import from', def: './automaton' },
      { id: 'accepted', type: 'number', label: 'Accepted cases', def: 15, min: 0, max: 200, step: 5 },
      { id: 'rejected', type: 'number', label: 'Rejected cases', def: 15, min: 0, max: 200, step: 5 },
      { id: 'maxLength', type: 'number', label: 'Max length', def: 8, min: 1, max: 20, step: 1 }
    ],
    build: (ir, o) => codegenJest(ir, o)
  };
  ExportFormats['test-pytest'] = {
    label: 'pytest suite', group: 'Tests', ext: 'py', mime: 'text/x-python',
    blurb: 'Cases derived from L(M) — pair with the Python target.',
    options: [
      { id: 'module', type: 'text', label: 'Import from', def: 'automaton' },
      { id: 'accepted', type: 'number', label: 'Accepted cases', def: 15, min: 0, max: 200, step: 5 },
      { id: 'rejected', type: 'number', label: 'Rejected cases', def: 15, min: 0, max: 200, step: 5 },
      { id: 'maxLength', type: 'number', label: 'Max length', def: 8, min: 1, max: 20, step: 1 }
    ],
    build: (ir, o) => codegenPytest(ir, o)
  };
}
