// SPDX-License-Identifier: LicenseRef-PolyForm-Noncommercial-1.0.0
// Copyright (c) 2026 Shreyan Chaubey. See LICENSE.
//
// ══════════════════════════════════════════════════════════════════
//  STATEMATE — PROMPT CONSTRUCTION
// ══════════════════════════════════════════════════════════════════
//  Assembled from the app's own registries rather than written out per
//  machine, so a machine added to state.js can be built by StateMate
//  without anyone editing a prompt:
//
//    the field list       from transitionFieldsFor / stateFieldsFor,
//                         which read MachineTypes
//    the notation         from App.config.sym — the user's own ε, ⊔, Z, ⊢, ⊣,
//                         so a workspace with custom symbols is described in
//                         the symbols it actually uses
//    the concept text     from MachineGuides, which reference.test.js already
//                         guarantees exists for every machine
//    the worked example   the bundled example file for this machine, run
//                         through machineToSpec — so the few-shot cannot
//                         drift from the schema, because it is generated by
//                         the same function the schema is defined beside
//
//  Nothing here is machine-specific prose. If you find yourself adding an
//  `if (machine === …)` with a paragraph in it, it belongs in the guide.

import {
  App, MachineCategories, MachineTypes, OmegaAcceptance, getMachineConfig,
  isOmegaAutomaton, isTwoWayFA, omegaAcceptanceOf, usesParityPriorities, MIN_TAPES, maxTapes } from './state.js';
import { MachineGuides } from './machine-guide.js';
import {
  MAX_SPEC_STATES, MIN_SPEC_TESTS, machineToSpec, stateFieldsFor,
  testKindFor, transitionFieldsFor
} from './statemate-spec.js';
import { hasSingleValuedDelta, isAnyTM } from './utils.js';
import { isMultiTape } from './machines/index.js';

// One line per spec field. Kept beside the field list rather than in the
// prompt text so the two cannot disagree about what exists.
const FIELD_DOCS = {
  from: 'name of the source state, exactly as spelled in "states"',
  to: 'name of the target state, exactly as spelled in "states"',
  on: 'the input symbol read',
  write: 'the symbol written to the tape cell under the head',
  move: 'head movement: "L", "R" or "S"',
  pop: 'symbol removed from the top of the stack',
  push: 'symbols pushed onto the stack (leftmost ends up on top)',
  pop2: 'symbol removed from the second stack',
  push2: 'symbols pushed onto the second stack',
  out: 'the output symbol or word emitted by this move',
  weight: 'probability of this move, a number in [0, 1]',
  tapeSyms: 'array of the symbols read, one per tape',
  tapeWrites: 'array of the symbols written, one per tape',
  tapeDirs: 'array of head movements, one per tape'
};

const STATE_FIELD_DOCS = {
  name: 'a short, meaningful name — this is what appears in the circle',
  start: 'true on exactly one state',
  accept: 'true on each accepting state',
  priority: 'a small non-negative integer',
  out: 'the symbol this state emits'
};

// ══════════════════════════════════════════════════════════════════
//  GROUNDING FROM THE REFERENCE
// ══════════════════════════════════════════════════════════════════

function stripMarkup(html) {
  return String(html)
    .replace(/<[^>]+>/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * The first prose of a machine's guide, flattened. Math blocks are dropped:
 * they are LaTeX, they are long, and everything they say is said again in the
 * surrounding prose.
 */
function guideGrounding(machine, budget = 1400) {
  const guide = MachineGuides[machine] || (machine === 'PDA' ? MachineGuides['DPDA'] : null);
  if (!guide) return '';

  const lines = [];
  for (const section of guide.sections || []) {
    for (const block of section.blocks || []) {
      if (block.t === 'p') lines.push(stripMarkup(block.x));
      else if (block.t === 'ul') block.x.forEach(item => lines.push('- ' + stripMarkup(item)));
      if (lines.join(' ').length > budget) break;
    }
    if (lines.join(' ').length > budget) break;
  }

  const text = lines.join('\n');
  return text.length > budget ? text.slice(0, budget) + '…' : text;
}

// ══════════════════════════════════════════════════════════════════
//  THE WORKED EXAMPLE
// ══════════════════════════════════════════════════════════════════
//  The bundled example for this machine, compiled into spec form. Fetched
//  once per machine and cached; a failure just means no few-shot, which is
//  a slightly weaker prompt rather than a broken feature.

const fewShotCache = new Map();

export async function loadFewShot(machine) {
  if (fewShotCache.has(machine)) return fewShotCache.get(machine);

  const file = getMachineConfig(machine).file;
  if (!file || typeof fetch !== 'function') {
    fewShotCache.set(machine, null);
    return null;
  }

  let spec = null;
  try {
    const res = await fetch(`js/examples/${file}.json`);
    if (res && res.ok !== false) {
      const data = await res.json();
      const source = {
        machine: data.machine,
        states: data.states,
        transitions: data.transitions,
        startId: data.startId,
        accepts: data.accepts,
        sigma: data.sigma,
        stackAlpha: data.stackAlpha,
        outputAlpha: data.outputAlpha,
        tapeCount: data.tapeCount
      };
      spec = machineToSpec(source);
      spec.title = data.meta?.title || 'Example';
      spec.blurb = data.meta?.blurb || '';
      // Only a couple of tests: the few-shot is teaching the shape, not the
      // coverage, and every extra line here is paid for on every request.
      spec.tests = (data.meta?.inputs || []).slice(0, 3).map(t => ({
        w: t.w || 'ε',
        ...(t.expect ? { expect: t.expect } : {}),
        ...(t.out !== undefined ? { out: t.out } : {})
      }));
    }
  } catch (e) {
    spec = null;
  }

  fewShotCache.set(machine, spec);
  return spec;
}

/** Test seam — the cache is module-level state and must not cross tests. */
export function _clearFewShotCache() {
  fewShotCache.clear();
}

// ══════════════════════════════════════════════════════════════════
//  THE SCHEMA BLOCK
// ══════════════════════════════════════════════════════════════════

function schemaBlock(machine, { notes = false } = {}) {
  const cfg = getMachineConfig(machine);
  const stateFields = stateFieldsFor(machine);
  const transFields = transitionFieldsFor(machine);
  const kind = testKindFor(machine);

  const alphabets = [`  "sigma": [ … ],                 the input alphabet Σ`];
  if (cfg.hasStack) {
    const label = cfg.hasTape ? 'the tape alphabet Γ (must contain the blank)' : 'the stack alphabet Γ (must contain the bottom marker)';
    alphabets.push(`  "stackAlpha": [ … ],             ${label}`);
  }
  if (cfg.isTransducer) alphabets.push(`  "outputAlpha": [ … ],            the output alphabet Δ`);
  if (isMultiTape(machine)) alphabets.push(`  "tapeCount": ${App.tapeCount},                   number of tapes (${MIN_TAPES}–${maxTapes()})`);

  const testLine = kind === 'omega'
    ? `  "tests": [ { "w": "a(bc)", "expect": "accept" }, … ]   ω-words as u(v): stem u, then v repeated forever`
    : kind === 'output'
      ? `  "tests": [ { "w": "abb", "out": "011" }, … ]          the exact output word this machine emits`
      : `  "tests": [ { "w": "abb", "expect": "accept" }, … ]    "accept" or "reject"`;

  return [
    '{',
    '  "kind": "machine",',
    '  "plan": "one sentence on the idea behind your construction",',
    `  "machine": "${machine}",`,
    '  "title": "a short name for this machine",',
    '  "blurb": "one or two sentences a student would find useful",',
    '  "caveat": "…",                   OPTIONAL — see below; omit it unless it applies',
    ...alphabets,
    '  "states": [',
    `    { ${stateFields.map(f => `"${f}": …`).join(', ')} }`,
    '  ],',
    '  "transitions": [',
    `    { ${transFields.map(f => `"${f}": …`).join(', ')} }`,
    '  ],',
    testLine,
    // Only offered when the user asked for it — an unasked-for sticky note on
    // someone's diagram is clutter, not an explanation.
    ...(notes
      ? ['  "notes": [ { "text": "one insight about the construction", "anchor": "<a state name>" } ]   at most two']
      : []),
    '}'
  ].join('\n');
}

// ══════════════════════════════════════════════════════════════════
//  YOU ARE NOT LIMITED TO THE CURRENT MACHINE
// ══════════════════════════════════════════════════════════════════
//  Switching has always worked — validateSpec accepts any key in
//  MachineTypes, compileSpec starts clean when the type changes, and
//  assignCandidate calls applyMachineSwitch. The model simply had no way to
//  know, so it refused perfectly buildable requests ("I build only DFAs, I
//  cannot construct Turing machines") instead of changing the canvas.
//
//  Only the current machine's rules are spelled out in full — every machine's
//  would be an enormous prompt. The signature line is what a switch needs to
//  get the transition shape right, and the linter's repair round covers the
//  rest, since lintCandidate judges the machine the answer actually names.

function machineMenu(current) {
  const lines = [];
  for (const cat of MachineCategories) {
    const entries = cat.machines
      .filter(m => MachineTypes[m] && m !== current)
      .map(m => {
        const extra = transitionFieldsFor(m).filter(f => !['from', 'to', 'on'].includes(f));
        const fields = extra.length ? ` (+ ${extra.join(', ')})` : '';
        return `    ${m} — ${MachineTypes[m].fullName}${fields}`;
      });
    if (entries.length) lines.push(`  ${cat.label}:`, ...entries);
  }
  return lines.join('\n');
}

function switchBlock(machine) {
  return [
    `YOU CAN CHANGE THE MODEL. The canvas is currently a ${machine}, but "machine" is yours to set: name a different one and the app switches the canvas to it. Every transition then carries that model's fields, listed in brackets below, and its own rules apply.`,
    machineMenu(machine),
    `Switch when the request needs it — a language no ${machine} can recognise, or an explicit ask for another model. Say so in "caveat" when you do, because the switch replaces what is on the canvas rather than editing it. Do not switch when the request fits the current model: a needless change throws away the user's diagram.`
  ].join('\n');
}

// The other turn. Its whole purpose is the request that is not a request for
// a machine at all, so the copy spends most of its words fencing that off from
// the request that is merely hard — which is what "caveat" is for — and from
// the request that only needs a different model, which is a switch.
function replyBlock(machine) {
  return [
    `THE OTHER SHAPE — only when the request is not a request for a machine:`,
    '{',
    '  "kind": "reply",',
    '  "text": "a short paragraph — what you cannot do, and what you could do instead"',
    '}',
    `A reply draws nothing. Use it when there is no machine to build and no change to make: a question about theory, a question about the machine already on the canvas, an instruction this tool cannot carry out, a request that names no language.`,
    `Answering is not declining. When the canvas holds a machine and the request only asks about it — "why does it reject aab", "is this minimal", "what language does it accept", "explain state q2" — reply with the answer and leave the machine alone. Rebuilding a diagram someone asked a question about is destructive, not helpful.`,
    `Do NOT use it for a request that is merely hard, vague, or impossible to satisfy exactly — build the closest correct machine and put the gap in "caveat". Do NOT use it because the request needs a model other than ${machine} — switch instead. Never claim you can only build ${machine}s; you can build any model in the list above. If the request names any change to make, however small, build or edit rather than reply; when in doubt about that, build.`,
    // The reply card renders markdown, so saying so is the difference between
    // a formatted answer and one with literal asterisks in it. "text" is a
    // JSON string either way — the newlines in it have to be escaped as \\n.
    `"text" is rendered as Markdown: **bold**, lists, \`code\`, tables, and $TeX$ or $$display TeX$$ all typeset. Use it for structure, keep it short, and remember it is a JSON string — escape newlines as \\n. Raw HTML is not rendered.`
  ].join('\n');
}

function fieldGlossary(machine) {
  const lines = [];
  lines.push('State fields:');
  stateFieldsFor(machine).forEach(f => lines.push(`  ${f} — ${STATE_FIELD_DOCS[f] || ''}`));
  lines.push('Transition fields (every transition carries all of them):');
  transitionFieldsFor(machine).forEach(f => lines.push(`  ${f} — ${FIELD_DOCS[f] || ''}`));
  return lines.join('\n');
}

// ══════════════════════════════════════════════════════════════════
//  THE RULES THAT ARE NOT NEGOTIABLE
// ══════════════════════════════════════════════════════════════════
//  These duplicate the linter deliberately. The linter is what makes the
//  feature correct; saying the same thing here is what keeps most requests
//  from needing a repair round in the first place.

function machineRules(machine) {
  const cfg = getMachineConfig(machine);
  const sym = App.config.sym;
  const rules = [];

  if (hasSingleValuedDelta(machine)) {
    rules.push(`${machine} is DETERMINISTIC. No state may have two transitions that could both apply to the same situation. Check every state before you answer.`);
  } else {
    rules.push(`${machine} is nondeterministic: several transitions may apply at once, and the machine accepts if any run accepts.`);
  }

  rules.push(cfg.hasEpsilon
    ? `ε-transitions are allowed. Write the read symbol as "${sym.eps}" to consume no input.`
    : `ε-transitions are NOT allowed in a ${machine}. Every transition must read a real symbol.`);

  rules.push(`"${sym.any}" as a read symbol is a wildcard matching any input symbol. A concrete symbol beats it out of the same state.`);

  if (cfg.hasStack && !cfg.hasTape) {
    rules.push(`The stack starts holding "${sym.stackBottom}". Use "${sym.eps}" for pop to mean "do not pop" and for push to mean "push nothing". A multi-character push string lands with its leftmost character on top.`);
  }
  if (cfg.hasTape) {
    rules.push(`The blank symbol is "${sym.blank}". Γ must contain it and every symbol of Σ. A tape transition must give both "write" and "move".`);
  }
  if (cfg.hasEndMarkers) {
    rules.push(`The input is bracketed by the end markers "${sym.leftMarker}" and "${sym.rightMarker}". They are read from the tape, and they must NOT appear in Σ.`);
  }
  if (isTwoWayFA(machine)) {
    rules.push(`The head moves in both directions: every transition must give "move" as "L", "R" or "S".`);
  }
  if (cfg.isWeighted) {
    rules.push(`For every state and every input symbol, the weights of the transitions leaving that state on that symbol must sum to exactly 1. A word is accepted when its acceptance probability exceeds the cut-point ${App.config.pfaCutPoint}.`);
  }
  if (isOmegaAutomaton(machine)) {
    const acc = OmegaAcceptance[omegaAcceptanceOf(machine)];
    rules.push(`Acceptance is ${acc.label}: ${acc.say}. The input is an infinite word written u(v) — the stem u, then v repeated forever.`);
    if (usesParityPriorities(machine)) {
      rules.push(`There is NO set of accepting states. Every state carries a "priority" integer instead; do not mark states as accepting.`);
    }
    if (acc.structural) {
      rules.push(`Additionally, every cycle in the automaton must lie wholly inside the accepting set or wholly outside it.`);
    }
  }
  if (cfg.isTransducer) {
    rules.push(machine === 'Moore'
      ? `A Moore machine emits from the state: give each state an "out". Transitions carry no output.`
      : `Output is emitted per transition. Use "" for a move that emits nothing.`);
  }
  if (isAnyTM(machine)) {
    rules.push(`Halt by moving to an accepting state. A run with no applicable transition halts and rejects.`);
  }

  rules.push(`Use at most ${MAX_SPEC_STATES} states, and prefer the smallest machine that is correct.`);
  return rules.map((r, i) => `${i + 1}. ${r}`).join('\n');
}

// ══════════════════════════════════════════════════════════════════
//  ASSEMBLY
// ══════════════════════════════════════════════════════════════════

export async function buildSystemPrompt(machine = App.machine, { notes = false } = {}) {
  const cfg = getMachineConfig(machine);
  const fewShot = await loadFewShot(machine);

  const parts = [
    `You build automata for AutomataStudio, a teaching/designing tool for automata theory. You are given a request and you answer with one machine, as JSON. Nothing else.`,
    ``,
    `CURRENT MODEL: ${machine} — ${cfg.fullName}. This is what the canvas holds, and what the schema and rules below describe. It is a starting point, not a limit — see YOU CAN CHANGE THE MODEL.`,
    ``,
    `OUTPUT FORMAT — a single JSON object, no prose, no code fences, keys in this order:`,
    schemaBlock(machine, { notes }),
    ``,
    switchBlock(machine),
    ``,
    replyBlock(machine),
    ``,
    fieldGlossary(machine),
    ``,
    `NOTATION IN THIS WORKSPACE — use these exact characters:`,
    `  ε (empty / no move) = "${App.config.sym.eps}"`,
    `  wildcard            = "${App.config.sym.any}"`,
    ...(cfg.hasTape ? [`  blank               = "${App.config.sym.blank}"`] : []),
    ...(cfg.hasStack && !cfg.hasTape ? [`  stack bottom        = "${App.config.sym.stackBottom}"`] : []),
    ...(cfg.hasEndMarkers ? [`  end markers         = "${App.config.sym.leftMarker}" and "${App.config.sym.rightMarker}"`] : []),
    ``,
    `RULES FOR ${machine}:`,
    machineRules(machine),
    ``,
    `TESTS ARE MANDATORY AND THEY WILL BE EXECUTED.`,
    `Give at least ${MIN_SPEC_TESTS} tests, including the shortest interesting word and at least one that must be rejected. The app runs them against the machine you just described, using its real simulator, before drawing anything. If your predictions do not match what your machine does, you will be asked to fix it — so trace them yourself first.`,
    ``,
    `IF YOU CANNOT DO EXACTLY WHAT WAS ASKED, SAY SO IN "caveat".`,
    `Build the closest correct machine you can, and set "caveat" to one sentence naming the gap — that the language requested is not recognisable by a ${machine}, say, and what the machine you built recognises instead. Then write tests for the machine you actually built, not for the one that was asked for. Omit "caveat" entirely when the answer is exactly what was requested: it is not for describing a machine that is correct, which is what "blurb" is for.`,
    `"caveat" is about the MACHINE, never about you or about producing the answer. Do not write that something was corrected, repaired, fixed, revised or updated, and do not refer to a previous attempt — the user is looking at one machine and has no idea there was another. "This DFA accepts only n ≤ 3, because aⁿbⁿ is not regular" is a caveat. "The machine was corrected to accurately reflect the language" is not, and will be discarded.`
  ];

  const grounding = guideGrounding(machine);
  if (grounding) {
    parts.push(``, `REFERENCE — what a ${machine} is, from this app's own documentation:`, grounding);
  }

  if (fewShot) {
    parts.push(
      ``,
      `A COMPLETE, VALID ANSWER for a different ${machine} — copy this shape exactly:`,
      JSON.stringify(fewShot, null, 1)
    );
  }

  return parts.join('\n');
}

/**
 * Past turns, as provider messages.
 *
 * The transcript carries *intent*, never machines. A user turn goes verbatim;
 * an assistant turn that built something is reduced to its one-line summary,
 * and only a reply survives word for word.
 *
 * That is not a size optimisation, though it is also that. The canvas is the
 * state: compileSpec() diffs by state name against whatever is live right
 * now, and buildUserMessage attaches that machine fresh on every turn. Replay
 * three past machines alongside it and the model has four candidates for
 * "the machine" and no way to tell which one the next edit lands on.
 */
export function threadMessages(turns = []) {
  return turns.map(turn => ({
    role: turn.role,
    content: turn.role === 'assistant' && turn.kind === 'machine'
      ? `[built: ${turn.text}]`
      : turn.text
  }));
}

/**
 * The user turn. `mode` is 'build' or 'edit'; the canvas is only attached in
 * edit mode or when the user has explicitly asked for it.
 */
/**
 * The parts of the machine this turn is *pointing at*.
 *
 * A pointer into the machine, never a substitute for it — the whole spec is
 * still attached above, because almost every question about one state ("why
 * does this reject aab") can only be answered from the rest of the diagram.
 * All-or-nothing attachment was the gap this closes: on a forty-state machine
 * there was no way to say "this one".
 *
 * Everything here is named, because the dialect has no ids and a model shown
 * `s7` has been shown a token attached to nothing.
 */
function focusBlock(focus) {
  const lines = ['THE REQUEST IS ABOUT THESE PARTS OF THE MACHINE — the reader selected them on the canvas:'];
  if (focus.states.length) lines.push(`  states: ${focus.states.join(', ')}`);
  if (focus.transitions.length) {
    lines.push('  transitions:');
    focus.transitions.forEach(t => lines.push(`    ${t}`));
  }
  if (focus.notes.length) focus.notes.forEach(n => lines.push(`  note: ${n}`));
  if (focus.words.length) lines.push(`  input words: ${focus.words.join(', ')}`);
  lines.push('Treat anything unqualified in the request as referring to these. The rest of the machine is still yours to read, and to change if the request needs it.');
  return lines.join('\n');
}

export function buildUserMessage({ prompt, intent, canvasSpec = null, authority = 'auto', focus = null, images = 0 }) {
  const parts = [];

  // The pictures themselves are content parts on the same turn — see
  // toProviderContent in statemate-provider.js — and this is the sentence that
  // says what they are for. Without it a diagram is just an image the model
  // may or may not decide the request is about; the transcription instruction
  // is what turns a photographed drawing into a machine.
  if (images) {
    parts.push(
      `${images === 1 ? 'An image is' : `${images} images are`} attached to this turn. If ${images === 1 ? 'it shows' : 'they show'} a state diagram, a transition table or handwritten notes, read the machine out of ${images === 1 ? 'it' : 'them'} — states, start state, accepting states and every transition — and use that as the request's subject.`,
      `Say in "caveat" what you could not make out, rather than inventing it.`,
      ``
    );
  }

  if (canvasSpec) {
    parts.push(
      intent === 'edit'
        ? `THE MACHINE CURRENTLY ON THE CANVAS — the request below is about this machine:`
        : `FOR CONTEXT, the machine currently on the canvas:`,
      JSON.stringify(canvasSpec),
      ``
    );
    // Edit mode is a subject, not an instruction. Telling the model to modify
    // the machine made every turn an edit — ask why a state rejects a word and
    // you got a rebuilt diagram instead of an answer, which is both wrong and
    // destructive. The two cases are spelled out so the request decides.
    if (intent === 'edit') {
      parts.push(
        `If the request asks for a change, return the modified machine, and keep the names of every state you are not changing so the diagram survives the edit.`,
        `If the request only asks a question about this machine, answer it with a reply and change nothing.`,
        ``
      );
    }
  } else if (intent === 'edit') {
    parts.push(`The canvas is empty, so build the machine from scratch.`, ``);
  }

  // After the machine and before the request: it is a qualification of the
  // request, and it is meaningless without the machine above it.
  if (focus) parts.push(focusBlock(focus), ``);

  // Ask mode is read-only, and saying so is the difference between an answer
  // and a machine that gets built and thrown away. The pipeline refuses to
  // write either way — this is what stops the wasted round trip.
  if (authority === 'ask') {
    parts.push(
      `THIS TURN IS READ-ONLY. Nothing you return will be drawn on the canvas.`,
      `Answer with "kind": "reply". If the request asks for a machine, describe the one you would build — how many states, what each one remembers, the shape of the transitions — instead of returning it. The reader can turn that description into a real build with one click.`,
      ``
    );
  }

  parts.push(`REQUEST: ${prompt}`);
  parts.push(``, `Answer with the JSON object only.`);
  return parts.join('\n');
}

/**
 * The repair turn. Generated, never free text: the failures the simulator and
 * linter actually found, capped so a wide failure cannot crowd out the
 * original request.
 *
 * It no longer restates the answer being corrected. The rejected answer is now
 * its own assistant turn in the thread, which is both cheaper and the shape a
 * model expects — it reads its own last message rather than a quotation of it.
 */
/** One traced step, as a line under the failure it explains. */
function repairTraceLine(step) {
  const bits = [`${step.at}.`, step.note || ''];
  if (step.stack !== undefined) bits.push(`stack:[${step.stack}]`);
  if (step.stack2 !== undefined) bits.push(`stack2:[${step.stack2}]`);
  if (step.tape !== undefined) bits.push(`tape:${step.tape} head:${step.head}`);
  if (step.tapes) bits.push(`tapes:${step.tapes.join(' | ')} heads:${(step.heads || []).join(',')}`);
  if (step.out !== undefined) bits.push(`out:${step.out}`);
  return `    ${bits.filter(Boolean).join(' ')}`;
}

export function buildRepairMessage({ prompt, failures = [], findings = [], traces = [] }) {
  const parts = [`That answer cannot be used.`, ``];

  if (failures.length) {
    parts.push(`It failed ${failures.length} of the checks you predicted:`);
    failures.slice(0, 8).forEach(f => parts.push(`  ${f}`));
    parts.push(``);
  }

  // The path each contradicted word actually took. Without it this message
  // says a machine is wrong and gives nothing to look at, so the cheapest
  // correct move available is to re-read the transition list and guess —
  // which is how a repair round turns into a rewrite.
  if (traces.length) {
    parts.push(`Here is what those words did, step by step, in your machine:`);
    traces.forEach(trace => {
      if (trace.error) {
        parts.push(`  "${trace.word}" — could not be read: ${trace.why}`);
        return;
      }
      const elided = trace.elided ? ` — ${trace.steps} steps, ${trace.elided} omitted from the middle` : '';
      parts.push(`  "${trace.word}" — ${trace.verdict}${elided}`);
      (trace.trace || []).forEach(step => parts.push(repairTraceLine(step)));
    });
    parts.push(``);
  }

  if (findings.length) {
    parts.push(`Problems found in the machine itself:`);
    findings.slice(0, 6).forEach(f => parts.push(`  · ${f.message}`));
    parts.push(``);
  }

  parts.push(
    `The original request was: ${prompt}`,
    ``,
    `Return the corrected machine — "kind": "machine", same schema, same key order, no prose. A reply is not an acceptable answer here.`
  );
  return parts.join('\n');
}

/**
 * Openers for the idle console.
 *
 * In edit mode the machine already exists, so a build prompt is the wrong
 * offer — it would replace the thing the user is looking at. These are the
 * two halves of that mode instead: one question, then changes, so the empty
 * state shows that asking is a thing you can do here at all.
 */
export function editStarterPrompts(machine = App.machine) {
  const cfg = getMachineConfig(machine);
  return [
    'what language does this accept?',
    ...(cfg.hasTape || cfg.hasStack ? [] : ['is this the smallest machine for it?']),
    'add a trap state for everything else',
    'rename the states to something clearer'
  ];
}

/** Starter prompts for the idle console, tailored to the current machine. */
export function starterPrompts(machine = App.machine) {
  const cfg = getMachineConfig(machine);
  if (isOmegaAutomaton(machine)) {
    return [
      'infinitely many a\'s',
      'only finitely many b\'s',
      'after every a, eventually a b'
    ];
  }
  if (cfg.hasTape) {
    return [
      'accepts aⁿbⁿcⁿ',
      'decides whether the input is a palindrome',
      'appends a 1 to the end of the input'
    ];
  }
  if (cfg.hasStack) {
    return [
      'balanced parentheses',
      'aⁿbⁿ for n ≥ 1',
      'strings with twice as many a\'s as b\'s'
    ];
  }
  if (cfg.isTransducer) {
    return [
      'outputs 1 whenever it has seen an even number of a\'s',
      'replaces every a with bb',
      'a binary increment'
    ];
  }
  return [
    'strings where every a is followed by a b',
    'binary numbers divisible by 3',
    'an even number of a\'s and an odd number of b\'s'
  ];
}

/** Every machine name, for the "did you mean a different model" hint. */
export function knownMachines() {
  return Object.keys(MachineTypes);
}
