// SPDX-License-Identifier: LicenseRef-PolyForm-Noncommercial-1.0.0
// Copyright (c) 2026 Shreyan Chaubey. See LICENSE.
//
// ══════════════════════════════════════════════════════════════════
//  STATEMATE — PROMPT CONSTRUCTION
// ══════════════════════════════════════════════════════════════════
//  Assembled from the app's own registries rather than written out per
//  machine, so a machine added to state.js can be built by StateMate
//  without anyone editing a prompt:
//
//    the field list       from transitionFieldsFor / stateFieldsFor,
//                         which read MachineTypes
//    the notation         from App.config.sym — the user's own ε, ⊔, Z, ⊢, ⊣,
//                         so a workspace with custom symbols is described in
//                         the symbols it actually uses
//    the concept text     from MachineGuides, which reference.test.js already
//                         guarantees exists for every machine
//    the worked example   the bundled example file for this machine, run
//                         through machineToSpec — so the few-shot cannot
//                         drift from the schema, because it is generated by
//                         the same function the schema is defined beside
//
//  Nothing here is machine-specific prose. If you find yourself adding an
//  `if (machine === …)` with a paragraph in it, it belongs in the guide.
//
//  ── Tone ─────────────────────────────────────────────────────────
//  The prompt is written to a colleague, not to a parser. It used to be a
//  list of prohibitions in capitals — "Nothing else", "NOT", "will be
//  discarded" — and a model prompted like that answers like it: terse,
//  defensive, a form filled in rather than a person helped. The rules a
//  machine has to obey are still here, stated once each, with the reason
//  where the reason changes what a model does. Everything the prompt used to
//  shout is also enforced after the fact — by validateSpec, the linter and
//  the verifier — so the prompt can afford to explain instead of warn.
//
//  ── Size ─────────────────────────────────────────────────────────
//  Every word here is paid for on every request. The worked example is
//  rendered one row per state and transition rather than pretty-printed, and
//  omits the `false` flags validateSpec already defaults; the notation and
//  the rules are one list rather than two that repeated each other; and the
//  guide excerpt prefers what is particular to this app over textbook
//  definitions the model already knows.

import {
  App, MachineCategories, MachineTypes, OmegaAcceptance, getMachineConfig,
  isOmegaAutomaton, isTwoWayFA, omegaAcceptanceOf, usesParityPriorities, MIN_TAPES, maxTapes } from './state.js';
import { MachineGuides } from './machine-guide.js';
import {
  MAX_SPEC_STATES, MIN_SPEC_TESTS, machineToSpec, stateFieldsFor,
  testKindFor, transitionFieldsFor
} from './statemate-spec.js';
import { hasSingleValuedDelta, isAnyTM } from './utils.js';
import { isMultiTape, machineSupportsBlocks } from './machines/index.js';
import { blockMembers } from './blocks.js';
import { scopeTrail } from './view-graph.js';

// Only the fields whose meaning is not obvious from their name. `from`, `to`,
// `on`, `name`, `start` and `accept` explain themselves, and the schema line
// already shows they exist. Kept beside the field list rather than in the
// prompt text so the two cannot disagree about what exists.
const FIELD_DOCS = {
  write: 'symbol written under the head',
  move: '"L", "R" or "S"',
  pop: 'symbol taken off the top of the stack',
  push: 'symbols pushed; the leftmost ends up on top',
  pop2: 'symbol taken off the second stack',
  push2: 'symbols pushed onto the second stack',
  below: 'stacks inserted below the top one, "|"-separated, each top-first (ε for none)',
  above: 'stacks inserted above the top one, "|"-separated, each top-first (ε for none)',
  out: 'output emitted by this move',
  weight: 'probability of this move, in [0, 1]',
  tapeSyms: 'symbols read, one per tape',
  tapeWrites: 'symbols written, one per tape',
  tapeDirs: 'head moves, one per tape'
};

const STATE_FIELD_DOCS = {
  priority: 'a small non-negative integer',
  out: 'the symbol this state emits'
};

// ══════════════════════════════════════════════════════════════════
//  GROUNDING FROM THE REFERENCE
// ══════════════════════════════════════════════════════════════════

function stripMarkup(html) {
  return String(html)
    .replace(/<[^>]+>/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

// A sentence about this app's own conventions — where the tape is bounded,
// what the input syntax is, which of two textbook conventions is in force.
const APP_SPECIFIC = /\b(this app|the app|in this app|here the)\b/i;

/**
 * What a model needs from the guide, within a budget.
 *
 * The guide opens with the definition — which every model already knows — and
 * the old excerpt spent its whole budget there and was cut mid-sentence at
 * exactly the line that mattered: "In this app the tape is infinite to the
 * right and bounded on …". So the sentences about this app's own conventions
 * are taken first, wherever they sit in the guide, and the opening prose fills
 * whatever room is left. Whole lines only, in the guide's own order; math
 * blocks are dropped, because everything they say is said again in prose.
 */
function guideGrounding(machine, budget = 900) {
  const guide = MachineGuides[machine] || (machine === 'PDA' ? MachineGuides['DPDA'] : null);
  if (!guide) return '';

  const lines = [];
  for (const section of guide.sections || []) {
    for (const block of section.blocks || []) {
      if (block.t === 'p') lines.push(stripMarkup(block.x));
      else if (block.t === 'ul') block.x.forEach(item => lines.push('- ' + stripMarkup(item)));
    }
  }
  // A line ending in a colon introduces the table or formula after it, which
  // is not being sent — alone it reads as a sentence cut off.
  for (let i = lines.length - 1; i >= 0; i--) if (/:\s*$/.test(lines[i])) lines.splice(i, 1);

  const chosen = new Set();
  let used = 0;
  const take = i => {
    if (chosen.has(i) || used + lines[i].length > budget) return;
    chosen.add(i);
    used += lines[i].length + 1;
  };
  lines.forEach((line, i) => { if (APP_SPECIFIC.test(line)) take(i); });
  lines.forEach((_, i) => take(i));
  return [...chosen].sort((a, b) => a - b).map(i => lines[i]).join('\n');
}

// ══════════════════════════════════════════════════════════════════
//  THE WORKED EXAMPLE
// ══════════════════════════════════════════════════════════════════
//  The bundled example for this machine, compiled into spec form. Fetched
//  once per machine and cached; a failure just means no few-shot, which is
//  a slightly weaker prompt rather than a broken feature.

const fewShotCache = new Map();

/**
 * Three test words for the example, mixing verdicts where the file allows.
 *
 * The prompt asks for at least one word that must be rejected, and the
 * example used to take the file's first three inputs — which for most
 * examples were three accepts, so the one complete answer the model was shown
 * broke the rule stated above it.
 */
function exampleTests(inputs) {
  const all = Array.isArray(inputs) ? inputs : [];
  const acc = all.filter(t => t.expect === 'accept');
  const rej = all.filter(t => t.expect === 'reject');
  const picked = [acc[0], rej[0], acc[1] || rej[1]].filter(Boolean);
  for (const t of all) {
    if (picked.length >= 3) break;
    if (!picked.includes(t)) picked.push(t);
  }
  return picked.slice(0, 3).map(t => ({
    w: t.w || 'ε',
    ...(t.expect ? { expect: t.expect } : {}),
    ...(t.out !== undefined ? { out: t.out } : {})
  }));
}

export async function loadFewShot(machine) {
  if (fewShotCache.has(machine)) return fewShotCache.get(machine);

  const file = getMachineConfig(machine).file;
  if (!file || typeof fetch !== 'function') {
    fewShotCache.set(machine, null);
    return null;
  }

  let spec = null;
  try {
    const res = await fetch(`js/examples/${file}.json`);
    if (res && res.ok !== false) {
      const data = await res.json();
      const source = {
        machine: data.machine,
        states: data.states,
        transitions: data.transitions,
        startId: data.startId,
        accepts: data.accepts,
        sigma: data.sigma,
        stackAlpha: data.stackAlpha,
        outputAlpha: data.outputAlpha,
        tapeCount: data.tapeCount
      };
      const body = machineToSpec(source);
      // Key order is the answer's order: kind and title first, the machine,
      // then the tests. The file's own order put the alphabet after the
      // transitions and had no "kind" at all, under a line telling the model
      // to copy the shape exactly.
      spec = {
        kind: 'machine',
        machine: body.machine,
        title: data.meta?.title || 'Example',
        blurb: data.meta?.blurb || '',
        ...Object.fromEntries(['sigma', 'stackAlpha', 'outputAlpha', 'tapeCount']
          .filter(k => body[k] !== undefined).map(k => [k, body[k]])),
        states: body.states,
        transitions: body.transitions,
        tests: exampleTests(data.meta?.inputs)
      };
    }
  } catch (e) {
    spec = null;
  }

  fewShotCache.set(machine, spec);
  return spec;
}

/** Test seam — the cache is module-level state and must not cross tests. */
export function _clearFewShotCache() {
  fewShotCache.clear();
}

/**
 * The example as the model should write one: a row per state and per
 * transition, and no `false` flags, since an absent flag already means false.
 * Pretty-printed with one field per line it was ~40% whitespace — 4.5k
 * characters for the multi-tape example — paid for on every request.
 */
export function renderExample(spec) {
  const row = value => JSON.stringify(value);
  const lean = s => Object.fromEntries(Object.entries(s).filter(([, v]) => v !== false));
  const lines = ['{'];
  const entries = Object.entries(spec);
  entries.forEach(([key, value], i) => {
    const comma = i < entries.length - 1 ? ',' : '';
    if (Array.isArray(value) && value.length && typeof value[0] === 'object') {
      const rows = key === 'states' ? value.map(lean) : value;
      lines.push(`  "${key}": [`);
      rows.forEach((item, j) => lines.push(`    ${row(item)}${j < rows.length - 1 ? ',' : ''}`));
      lines.push(`  ]${comma}`);
    } else {
      lines.push(`  "${key}": ${row(value)}${comma}`);
    }
  });
  lines.push('}');
  return lines.join('\n');
}

// ══════════════════════════════════════════════════════════════════
//  THE SCHEMA BLOCK
// ══════════════════════════════════════════════════════════════════

function schemaBlock(machine, { notes = false } = {}) {
  const cfg = getMachineConfig(machine);
  const stateFields = stateFieldsFor(machine);
  const transFields = transitionFieldsFor(machine);
  const kind = testKindFor(machine);

  const alphabets = [`  "sigma": [ … ],                  input alphabet Σ`];
  if (cfg.hasStack) {
    const label = cfg.hasTape ? 'tape alphabet Γ, including the blank' : 'stack alphabet Γ, including the bottom marker';
    alphabets.push(`  "stackAlpha": [ … ],             ${label}`);
  }
  if (cfg.isTransducer) alphabets.push(`  "outputAlpha": [ … ],            output alphabet Δ`);
  if (isMultiTape(machine)) alphabets.push(`  "tapeCount": ${App.tapeCount},                   number of tapes (${MIN_TAPES}–${maxTapes()})`);

  const testLine = kind === 'omega'
    ? `  "tests": [ { "w": "a(bc)", "expect": "accept" }, … ],  ω-words written u(v): stem u, then v forever`
    : kind === 'output'
      ? `  "tests": [ { "w": "abb", "out": "011" }, … ],         the exact output for that input`
      : `  "tests": [ { "w": "abb", "expect": "accept" }, … ],   "accept" or "reject"`;

  const blocks = machineSupportsBlocks(machine)
    ? [`  "blocks": [ { "name": "ALU/add", "parent": "ALU", "entry": "<state>", "exits": [ { "state": "<state>", "label": "carry" } ] } ],   optional — see Blocks`]
    : [];
  const stateShape = stateFields.map(f => `"${f}": …`)
    .concat(machineSupportsBlocks(machine) ? ['"block": "ALU/add" (optional)'] : [])
    .join(', ');

  return [
    '{',
    '  "kind": "machine",',
    '  "plan": "…",                      optional — one line on your approach; it shows while you work',
    `  "machine": "${machine}",`,
    '  "title": "…",                     a short name',
    '  "blurb": "…",                     one or two sentences for the card beside the diagram',
    ...alphabets,
    ...blocks,
    '  "states": [',
    `    { ${stateShape} }`,
    '  ],',
    '  "transitions": [',
    `    { ${transFields.map(f => `"${f}": …`).join(', ')} }`,
    '  ],',
    testLine,
    '  "caveat": "…",                    optional — see Tests and caveats',
    ...(notes
      ? ['  "notes": [ { "text": "…", "anchor": "<state>" } ],   up to two sticky notes on the diagram']
      : []),
    '  "message": "…"                    optional — what you want to say to them about it',
    '}'
  ].join('\n');
}

// ══════════════════════════════════════════════════════════════════
//  OTHER MODELS
// ══════════════════════════════════════════════════════════════════
//  Switching has always worked — validateSpec accepts any key in
//  MachineTypes, compileSpec starts clean when the type changes, and
//  assignCandidate calls applyMachineSwitch. The model simply had no way to
//  know, so it refused perfectly buildable requests ("I build only DFAs, I
//  cannot construct Turing machines") instead of changing the canvas.
//
//  Only the current machine's rules are spelled out in full — every machine's
//  would be an enormous prompt. The extra fields are what a switch needs to
//  get the transition shape right, and the linter's repair round covers the
//  rest, since lintCandidate judges the machine the answer actually names.
//  One line per category rather than one per machine: the same words, a
//  third of the lines.

function machineMenu(current) {
  const lines = [];
  for (const cat of MachineCategories) {
    const entries = cat.machines
      .filter(m => MachineTypes[m] && m !== current)
      .map(m => {
        const extra = transitionFieldsFor(m).filter(f => !['from', 'to', 'on'].includes(f));
        const fields = extra.length ? ` (+ ${extra.join(', ')})` : '';
        return `${m} — ${MachineTypes[m].fullName}${fields}`;
      });
    if (entries.length) lines.push(`- ${cat.label}: ${entries.join('; ')}`);
  }
  return lines.join('\n');
}

// ══════════════════════════════════════════════════════════════════
//  BLOCKS
// ══════════════════════════════════════════════════════════════════
//  A block is a subroutine drawn as one node, and it adds no computational
//  power — the expansion is the proof, and the machine stays flat. The rule
//  the paragraph exists to state is **absent means unchanged**: that is what
//  makes leaving it out safe, and what lets a model that never mentions the
//  hierarchy leave someone's grouping intact.

function blocksBlock(machine) {
  if (!machineSupportsBlocks(machine)) return '';
  return [
    `Blocks. A block is a sub-machine drawn as one box: control enters at its "entry" and leaves from its "exits". It adds no power — the machine you are shown is already flat, with the block path in each state's name (\`ALU/add/scan\`) — and a block is named by its path, since "ALU/add" and "FPU/add" are different blocks.`,
    `Leave "blocks" and "block" out unless you are creating, dissolving or rearranging blocks; left out, they stay exactly as they are. When you do send "blocks", it is the whole tree: a block you leave out of it is dissolved.`
  ].join('\n');
}

// ══════════════════════════════════════════════════════════════════
//  THE RULES
// ══════════════════════════════════════════════════════════════════
//  These duplicate the linter deliberately. The linter is what makes the
//  feature correct; saying the same thing here is what keeps most requests
//  from needing a repair round in the first place. The workspace's notation
//  is folded in here rather than listed separately — the old prompt stated ε,
//  the wildcard and the blank once as "notation" and again as rules.

function machineRules(machine) {
  const cfg = getMachineConfig(machine);
  const sym = App.config.sym;
  const rules = [];

  rules.push(hasSingleValuedDelta(machine)
    ? `It is deterministic: no state may have two transitions that could apply to the same situation.`
    : `It is nondeterministic: several transitions may apply at once, and a word is accepted if any run accepts.`);

  rules.push(cfg.hasEpsilon
    ? `"${sym.eps}" as the read symbol is an ε-move: it consumes no input.`
    : `There are no ε-moves; every transition reads a real symbol.`);

  rules.push(`"${sym.any}" as the read symbol is a wildcard for any input symbol; a concrete symbol out of the same state takes precedence over it.`);

  if (cfg.hasStack && !cfg.hasTape) {
    rules.push(`The stack starts holding "${sym.stackBottom}". "${sym.eps}" as pop means don't pop, and as push means push nothing.`);
  }
  if (cfg.hasTape) {
    rules.push(`The blank is "${sym.blank}"; Γ contains it and all of Σ. Every transition gives both "write" and "move".`);
  }
  if (cfg.hasEndMarkers) {
    rules.push(`The input is bracketed by the end markers "${sym.leftMarker}" and "${sym.rightMarker}", which are read from the tape and are not part of Σ.`);
  }
  if (isTwoWayFA(machine)) {
    rules.push(`The head moves both ways: every transition gives "move" as "L", "R" or "S".`);
  }
  if (cfg.isWeighted) {
    rules.push(`For each state and input symbol, the outgoing weights sum to exactly 1. A word is accepted when its probability exceeds the cut-point ${App.config.pfaCutPoint}.`);
  }
  if (isOmegaAutomaton(machine)) {
    const acc = OmegaAcceptance[omegaAcceptanceOf(machine)];
    rules.push(`Acceptance is ${acc.label}: ${acc.say}. Inputs are infinite words written u(v) — the stem u, then v repeated forever.`);
    if (usesParityPriorities(machine)) {
      rules.push(`There are no accepting states: every state carries a "priority" instead.`);
    }
    if (acc.structural) {
      rules.push(`Every cycle must lie wholly inside the accepting set or wholly outside it.`);
    }
  }
  if (cfg.isTransducer) {
    rules.push(machine === 'Moore'
      ? `Output comes from states: give each state an "out"; transitions carry none.`
      : `Output comes from transitions; use "" for a move that emits nothing.`);
  }
  if (isAnyTM(machine)) {
    rules.push(`It accepts by entering an accepting state; with no applicable transition it halts and rejects.`);
  }

  rules.push(`At most ${MAX_SPEC_STATES} states — and the smallest correct machine is the best one.`);
  return rules.map(r => `- ${r}`).join('\n');
}

/** Only the fields whose names do not say what they hold. */
function fieldNotes(machine) {
  const notes = [
    ...stateFieldsFor(machine).filter(f => STATE_FIELD_DOCS[f]).map(f => `"${f}" on a state: ${STATE_FIELD_DOCS[f]}`),
    ...transitionFieldsFor(machine).filter(f => FIELD_DOCS[f]).map(f => `"${f}": ${FIELD_DOCS[f]}`)
  ];
  return notes.length ? `Fields: ${notes.join('; ')}.` : '';
}

// ══════════════════════════════════════════════════════════════════
//  ASSEMBLY
// ══════════════════════════════════════════════════════════════════

/**
 * The system prompt. Deterministic in its arguments — the provider caches it
 * as a prefix, and anything that varied between calls would turn every cache
 * read into a write.
 *
 * `tools` says the model has agent tools: its first move may then be a tool
 * call rather than an answer, which the old opening line ("you answer with
 * one machine, as JSON. Nothing else.") flatly contradicted.
 */
export async function buildSystemPrompt(machine = App.machine, { notes = false, tools = false } = {}) {
  const cfg = getMachineConfig(machine);
  const fewShot = await loadFewShot(machine);

  const parts = [
    `You are StateMate, the assistant built into AutomataStudio, an app for designing and learning automata. You work with the person at the canvas: build and edit machines, explain how they work, answer theory questions, and think problems through with them. Talk like a knowledgeable colleague — clear, direct, and happy to explain your reasoning.`,
    ``,
    `The app reads your answer, so each answer is a single JSON object${tools ? ' (tool calls aside)' : ''} — no text around it, no code fence. It comes in two kinds.`,
    ``,
    `A machine, when they want something built or changed:`,
    schemaBlock(machine, { notes }),
    ``,
    `A reply, for everything else — a question, an explanation, a discussion, or a question of your own when the request could mean very different machines:`,
    `{ "kind": "reply", "text": "…" }`,
    ``,
    `"text" and "message" are shown to them as Markdown ($TeX$ and $$display TeX$$ typeset). Write them the way you would say it: your reasoning, the assumptions you made, what they might try next. They are JSON strings, so newlines are written \\n.`,
    ``,
    `Which to send:`,
    `- A question about the machine on the canvas — why it rejects a word, what it accepts, whether it is minimal — gets a reply. Rebuilding something they only asked about would throw away their work.`,
    `- Any change they ask for, however small, gets the machine.`,
    `- A request that is hard to meet exactly still gets the closest honest machine, with the gap named in "caveat" — or a reply explaining why, if nothing close would help.`,
    `- If it is ambiguous in a way that changes the machine a lot, ask. If it is ambiguous in a small way, build it and say what you assumed.`,
    ``,
    `The current model is ${machine} (${cfg.fullName}). That is what the canvas holds and what the rules below describe, but "machine" is yours to set: when the request needs a different model — a language no ${machine} can recognise, or they ask for one — switch to it, and mention it, since switching replaces what is on the canvas. You can build any of these, each with its extra transition fields:`,
    machineMenu(machine),
    ``,
    `Rules for a ${machine}:`,
    machineRules(machine),
    ...(fieldNotes(machine) ? [fieldNotes(machine)] : []),
    ...(blocksBlock(machine) ? [``, blocksBlock(machine)] : []),
    ``,
    `Tests and caveats. Give at least ${MIN_SPEC_TESTS} test words, including the shortest interesting one and at least one that should be rejected. The app runs them on your machine with its real simulator before drawing anything, and sends back any that disagree — so trace them first. Test the machine you actually built, not the one you wish you could have.`,
    `"caveat" is one sentence about a gap between the request and the machine — "aⁿbⁿ is not regular, so this accepts it only for n ≤ 3". Leave it out when the machine is what was asked for. It describes the machine, not your process: no "corrected", "fixed" or "previous attempt" — they only ever see the one machine.`
  ];

  const grounding = guideGrounding(machine);
  if (grounding) {
    parts.push(``, `About the ${machine}, from the app's reference:`, grounding);
  }

  if (fewShot) {
    parts.push(``, `A complete machine answer, for a different ${machine}:`, renderExample(fewShot));
  }

  return parts.filter((line, i, all) => !(line === '' && all[i - 1] === '')).join('\n');
}


/**
 * Past turns, as provider messages.
 *
 * The transcript carries *intent*, never machines. A user turn goes verbatim;
 * an assistant turn that built something is reduced to its one-line summary,
 * and only a reply survives word for word.
 *
 * That is not a size optimisation, though it is also that. The canvas is the
 * state: compileSpec() diffs by state name against whatever is live right
 * now, and buildUserMessage attaches that machine fresh on every turn. Replay
 * three past machines alongside it and the model has four candidates for
 * "the machine" and no way to tell which one the next edit lands on.
 */
export function threadMessages(turns = []) {
  return turns.map(turn => ({
    role: turn.role,
    content: turn.role === 'assistant' && turn.kind === 'machine'
      ? `[built: ${turn.text}]`
      : turn.text
  }));
}

/**
 * The user turn. `mode` is 'build' or 'edit'; the canvas is only attached in
 * edit mode or when the user has explicitly asked for it.
 */
/**
 * The parts of the machine this turn is *pointing at*.
 *
 * A pointer into the machine, never a substitute for it — the whole spec is
 * still attached above, because almost every question about one state ("why
 * does this reject aab") can only be answered from the rest of the diagram.
 * All-or-nothing attachment was the gap this closes: on a forty-state machine
 * there was no way to say "this one".
 *
 * Everything here is named, because the dialect has no ids and a model shown
 * `s7` has been shown a token attached to nothing.
 */
function focusBlock(focus) {
  const lines = ['THE REQUEST IS ABOUT THESE PARTS OF THE MACHINE — the reader selected them on the canvas:'];
  if (focus.states.length) lines.push(`  states: ${focus.states.join(', ')}`);
  if (focus.transitions.length) {
    lines.push('  transitions:');
    focus.transitions.forEach(t => lines.push(`    ${t}`));
  }
  if (focus.notes.length) focus.notes.forEach(n => lines.push(`  note: ${n}`));
  if (focus.words.length) lines.push(`  input words: ${focus.words.join(', ')}`);
  lines.push('Treat anything unqualified in the request as referring to these. The rest of the machine is still yours to read, and to change if the request needs it.');
  return lines.join('\n');
}

/**
 * How the block being shown is reached, and where it hands control back.
 *
 * A scoped spec without this is a disconnected fragment — you can see the
 * sub-machine and nothing about how it is entered, which is most of what a
 * question about it turns on. The same reason a drilled-in view draws ports.
 *
 * It is stated as *prose beside* the machine rather than as fields inside it,
 * because it describes the machine **around** the one being shown, and that one
 * is not on the table: nothing the model returns may change it, and a field it
 * could write to would say otherwise.
 */
function boundaryBlock(sc) {
  const cap = xs => xs.slice(0, 8).map(c => `${c.from} → ${c.to}`).join('; ')
    + (xs.length > 8 ? `; and ${xs.length - 8} more` : '');
  const lines = [`ITS BOUNDARY. Control enters this block at "${sc.entry}".`];
  lines.push(sc.exits.length
    ? `It declares ${sc.exits.length} exit${sc.exits.length === 1 ? '' : 's'}: `
      + sc.exits.map(e => `"${e.label}" at ${e.state}`).join(', ') + '.'
    : `It declares no exits.`);
  if (sc.crossings.in.length) lines.push(`Reached from outside by: ${cap(sc.crossings.in)}.`);
  if (sc.crossings.out.length) lines.push(`Leaves for outside by: ${cap(sc.crossings.out)}.`);
  lines.push(
    `Those outside states are NOT in the machine above and you cannot change them. `
    + `Keep the entry and the exits where they are unless the request asks otherwise — `
    + `they are what the rest of the machine is wired to.`
  );
  return lines.join('\n');
}

/**
 * The level the reader is looking at, as a sentence.
 *
 * Empty at the top level, which is the overwhelmingly common case and where
 * the flat machine and the drawn one are the same thing -- so a machine with no
 * blocks in it sends exactly the prompt it always sent.
 */
function scopeBlock() {
  const trail = scopeTrail();
  if (!trail.length) return '';
  const path = trail.map(b => b.name).join('/');
  const names = blockMembers(trail[trail.length - 1].id).map(s => s.name);
  const shown = names.slice(0, 12).join(', ');
  return [
    `THE READER IS INSIDE THE BLOCK "${path}". The machine above is flat, as it always is -- `
    + `a block is a grouping over it, not a separate machine -- but only this level is on their screen.`,
    `Its states are: ${shown}${names.length > 12 ? `, and ${names.length - 12} more` : ''}.`,
    `Read "this", "here" and an unqualified state name as belonging to that block unless the request says otherwise, `
    + `and prefer an answer about it to one about the whole machine.`
  ].join('\n');
}

export function buildUserMessage({ prompt, intent, canvasSpec = null, authority = 'auto', tutor = false, focus = null, images = 0 }) {
  const parts = [];

  // The pictures themselves are content parts on the same turn — see
  // toProviderContent in statemate-provider.js — and this is the sentence that
  // says what they are for. Without it a diagram is just an image the model
  // may or may not decide the request is about; the transcription instruction
  // is what turns a photographed drawing into a machine.
  if (images) {
    parts.push(
      `${images === 1 ? 'An image is' : `${images} images are`} attached to this turn. If ${images === 1 ? 'it shows' : 'they show'} a state diagram, a transition table or handwritten notes, read the machine out of ${images === 1 ? 'it' : 'them'} — states, start state, accepting states and every transition — and use that as the request's subject.`,
      `Say in "caveat" what you could not make out, rather than inventing it.`,
      ``
    );
  }

  if (canvasSpec) {
    // When the reader is inside a block, the subject *is* that block — the spec
    // above was cut down to it (scopedSource), so the heading has to say so or
    // the model reads a forty-state fragment as a whole machine that is missing
    // most of itself.
    const sc = canvasSpec.scope;
    parts.push(
      sc
        ? (intent === 'edit'
          ? `THE BLOCK THE READER IS INSIDE — "${sc.path}". The request below is about this block and everything nested in it, NOT the machine around it:`
          : `FOR CONTEXT, the block the reader is inside — "${sc.path}":`)
        : (intent === 'edit'
          ? `THE MACHINE CURRENTLY ON THE CANVAS — the request below is about this machine:`
          : `FOR CONTEXT, the machine currently on the canvas:`),
      JSON.stringify(canvasSpec),
      ``
    );
    if (sc) parts.push(boundaryBlock(sc), ``);
    // Edit mode is a subject, not an instruction. Telling the model to modify
    // the machine made every turn an edit — ask why a state rejects a word and
    // you got a rebuilt diagram instead of an answer, which is both wrong and
    // destructive. The two cases are spelled out so the request decides.
    if (intent === 'edit') {
      parts.push(
        `To change it, send back the whole modified machine, keeping the names of the states you are not changing — that is how the diagram keeps its layout. If they are only asking about it, reply and leave it as it is.`,
        ``
      );
    }
  } else if (intent === 'edit') {
    parts.push(`The canvas is empty, so anything you build starts from scratch.`, ``);
  }

  // Where the reader is standing, when that is not the top level.
  //
  // The machine sent above is flat -- every state at every depth, with the path
  // written into its name -- because that is what the machine *is*: blocks are a
  // grouping over a flat machine and inlining is their semantics. But "this"
  // means something different depending on which level is on screen, and until
  // this line the model had no way to know that a reader asking why the adder
  // rejects `11+01` was looking at forty of the three thousand states it was
  // handed.
  // Only when the machine above is the *whole* one. A scoped spec has already
  // said where the reader is, in its heading and its boundary; saying it again
  // here would be the same fact twice, once as a qualification of a machine
  // that is no longer being sent.
  const where = canvasSpec && !canvasSpec.scope ? scopeBlock() : '';
  if (where) parts.push(where, ``);

  // After the machine and before the request: it is a qualification of the
  // request, and it is meaningless without the machine above it.
  if (focus) parts.push(focusBlock(focus), ``);

  // Ask mode is read-only, and saying so is the difference between an answer
  // and a machine that gets built and thrown away. The pipeline refuses to
  // write either way — this is what stops the wasted round trip.
  // An exercise that allows hints only. The ask-mode block below would invite
  // the model to *describe* the machine it would build, which for a student
  // is the answer in prose — so this one comes first and says the opposite.
  // The pipeline enforces the part that can be enforced (nothing is drawn, a
  // machine answer is discarded); this is the part that can only be asked.
  if (tutor) {
    parts.push(
      `They are a student working on an exercise whose author allows hints only, so be a tutor here rather than a solver.`,
      `Answer with a reply, and don't give the answer away in any form — no machine, no transition list or table, no state-by-state solution, no grammar or regular expression for the target language.`,
      `What helps: a word their machine gets wrong and why, the idea the exercise is practising, a question that leads to the next step, or whether a claim they make is true.`,
      `If they ask you to solve it, tell them the exercise wants them to work it out, and offer a hint instead.`,
      ``
    );
  } else if (authority === 'ask') {
    parts.push(
      `StateMate is in ask mode, so this turn is read-only: nothing you return will be drawn.`,
      `Answer with a reply. If they want a machine, describe the one you would build — how many states, what each remembers, the shape of the transitions. They can turn that into a real build with one click.`,
      ``
    );
  }

  parts.push(`Their message: ${prompt}`);
  return parts.join('\n');
}

/**
 * The repair turn. Generated, never free text: the failures the simulator and
 * linter actually found, capped so a wide failure cannot crowd out the
 * original request.
 *
 * It no longer restates the answer being corrected. The rejected answer is now
 * its own assistant turn in the thread, which is both cheaper and the shape a
 * model expects — it reads its own last message rather than a quotation of it.
 */
/** One traced step, as a line under the failure it explains. */
function repairTraceLine(step) {
  const bits = [`${step.at}.`, step.note || ''];
  if (step.stack !== undefined) bits.push(`stack:[${step.stack}]`);
  if (step.stack2 !== undefined) bits.push(`stack2:[${step.stack2}]`);
  if (step.tape !== undefined) bits.push(`tape:${step.tape} head:${step.head}`);
  if (step.tapes) bits.push(`tapes:${step.tapes.join(' | ')} heads:${(step.heads || []).join(',')}`);
  if (step.out !== undefined) bits.push(`out:${step.out}`);
  return `    ${bits.filter(Boolean).join(' ')}`;
}

export function buildRepairMessage({ prompt, failures = [], findings = [], traces = [] }) {
  const parts = [`The app checked that machine, and it isn't right yet.`, ``];

  if (failures.length) {
    parts.push(`${failures.length} of your own test predictions didn't hold:`);
    failures.slice(0, 8).forEach(f => parts.push(`  ${f}`));
    parts.push(``);
  }

  // The path each contradicted word actually took. Without it this message
  // says a machine is wrong and gives nothing to look at, so the cheapest
  // correct move available is to re-read the transition list and guess —
  // which is how a repair round turns into a rewrite.
  if (traces.length) {
    parts.push(`Here is what those words actually did in your machine, step by step:`);
    traces.forEach(trace => {
      if (trace.error) {
        parts.push(`  "${trace.word}" — could not be read: ${trace.why}`);
        return;
      }
      const elided = trace.elided ? ` — ${trace.steps} steps, ${trace.elided} omitted from the middle` : '';
      parts.push(`  "${trace.word}" — ${trace.verdict}${elided}`);
      (trace.trace || []).forEach(step => parts.push(repairTraceLine(step)));
    });
    parts.push(``);
  }

  if (findings.length) {
    parts.push(`Problems in the machine itself:`);
    findings.slice(0, 6).forEach(f => parts.push(`  · ${f.message}`));
    parts.push(``);
  }

  parts.push(
    `Their original message: ${prompt}`,
    ``,
    `Send the corrected machine as a machine answer. If the tests themselves were wrong, fix the tests; if the request can't be met exactly, say so in "caveat".`
  );
  return parts.join('\n');
}

/**
 * Openers for the idle console.
 *
 * In edit mode the machine already exists, so a build prompt is the wrong
 * offer — it would replace the thing the user is looking at. These are the
 * two halves of that mode instead: one question, then changes, so the empty
 * state shows that asking is a thing you can do here at all.
 */
export function editStarterPrompts(machine = App.machine) {
  const cfg = getMachineConfig(machine);
  return [
    'what language does this accept?',
    ...(cfg.hasTape || cfg.hasStack ? [] : ['is this the smallest machine for it?']),
    'add a trap state for everything else',
    'rename the states to something clearer'
  ];
}

/** Starter prompts for the idle console, tailored to the current machine. */
export function starterPrompts(machine = App.machine) {
  const cfg = getMachineConfig(machine);
  if (isOmegaAutomaton(machine)) {
    return [
      'infinitely many a\'s',
      'only finitely many b\'s',
      'after every a, eventually a b'
    ];
  }
  if (cfg.hasTape) {
    return [
      'accepts aⁿbⁿcⁿ',
      'decides whether the input is a palindrome',
      'appends a 1 to the end of the input'
    ];
  }
  if (cfg.hasStack) {
    return [
      'balanced parentheses',
      'aⁿbⁿ for n ≥ 1',
      'strings with twice as many a\'s as b\'s'
    ];
  }
  if (cfg.isTransducer) {
    return [
      'outputs 1 whenever it has seen an even number of a\'s',
      'replaces every a with bb',
      'a binary increment'
    ];
  }
  return [
    'strings where every a is followed by a b',
    'binary numbers divisible by 3',
    'an even number of a\'s and an odd number of b\'s'
  ];
}

