// SPDX-License-Identifier: LicenseRef-PolyForm-Noncommercial-1.0.0
// Copyright (c) 2026 Shreyan Chaubey. See LICENSE.
//
// ══════════════════════════════════════════════════════════════════
//  STATEMATE — PROMPT CONSTRUCTION
// ══════════════════════════════════════════════════════════════════
//  Assembled from the app's own registries rather than written out per
//  machine, so a machine added to state.js can be built by StateMate
//  without anyone editing a prompt:
//
//    the field list       from transitionFieldsFor / stateFieldsFor,
//                         which read MachineTypes
//    the notation         from App.config.sym — the user's own ε, ⊔, Z, ⊢, ⊣,
//                         so a workspace with custom symbols is described in
//                         the symbols it actually uses
//    the concept text     from MachineGuides, which reference.test.js already
//                         guarantees exists for every machine
//    the worked example   the bundled example file for this machine, run
//                         through machineToSpec — so the few-shot cannot
//                         drift from the schema, because it is generated by
//                         the same function the schema is defined beside
//
//  Nothing here is machine-specific prose. If you find yourself adding an
//  `if (machine === …)` with a paragraph in it, it belongs in the guide.

import {
  App, MachineTypes, OmegaAcceptance, getMachineConfig, isOmegaAutomaton,
  isTwoWayFA, omegaAcceptanceOf, usesParityPriorities
} from './state.js';
import { MachineGuides } from './machine-guide.js';
import {
  MAX_SPEC_STATES, MIN_SPEC_TESTS, machineToSpec, stateFieldsFor,
  testKindFor, transitionFieldsFor
} from './statemate-spec.js';
import { hasSingleValuedDelta, isAnyTM } from './utils.js';

// One line per spec field. Kept beside the field list rather than in the
// prompt text so the two cannot disagree about what exists.
const FIELD_DOCS = {
  from: 'name of the source state, exactly as spelled in "states"',
  to: 'name of the target state, exactly as spelled in "states"',
  on: 'the input symbol read',
  write: 'the symbol written to the tape cell under the head',
  move: 'head movement: "L", "R" or "S"',
  pop: 'symbol removed from the top of the stack',
  push: 'symbols pushed onto the stack (leftmost ends up on top)',
  pop2: 'symbol removed from the second stack',
  push2: 'symbols pushed onto the second stack',
  out: 'the output symbol or word emitted by this move',
  weight: 'probability of this move, a number in [0, 1]',
  tapeSyms: 'array of the symbols read, one per tape',
  tapeWrites: 'array of the symbols written, one per tape',
  tapeDirs: 'array of head movements, one per tape'
};

const STATE_FIELD_DOCS = {
  name: 'a short, meaningful name — this is what appears in the circle',
  start: 'true on exactly one state',
  accept: 'true on each accepting state',
  priority: 'a small non-negative integer',
  out: 'the symbol this state emits'
};

// ══════════════════════════════════════════════════════════════════
//  GROUNDING FROM THE REFERENCE
// ══════════════════════════════════════════════════════════════════

function stripMarkup(html) {
  return String(html)
    .replace(/<[^>]+>/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * The first prose of a machine's guide, flattened. Math blocks are dropped:
 * they are LaTeX, they are long, and everything they say is said again in the
 * surrounding prose.
 */
function guideGrounding(machine, budget = 1400) {
  const guide = MachineGuides[machine] || (machine === 'PDA' ? MachineGuides['DPDA'] : null);
  if (!guide) return '';

  const lines = [];
  for (const section of guide.sections || []) {
    for (const block of section.blocks || []) {
      if (block.t === 'p') lines.push(stripMarkup(block.x));
      else if (block.t === 'ul') block.x.forEach(item => lines.push('- ' + stripMarkup(item)));
      if (lines.join(' ').length > budget) break;
    }
    if (lines.join(' ').length > budget) break;
  }

  const text = lines.join('\n');
  return text.length > budget ? text.slice(0, budget) + '…' : text;
}

// ══════════════════════════════════════════════════════════════════
//  THE WORKED EXAMPLE
// ══════════════════════════════════════════════════════════════════
//  The bundled example for this machine, compiled into spec form. Fetched
//  once per machine and cached; a failure just means no few-shot, which is
//  a slightly weaker prompt rather than a broken feature.

const fewShotCache = new Map();

export async function loadFewShot(machine) {
  if (fewShotCache.has(machine)) return fewShotCache.get(machine);

  const file = getMachineConfig(machine).file;
  if (!file || typeof fetch !== 'function') {
    fewShotCache.set(machine, null);
    return null;
  }

  let spec = null;
  try {
    const res = await fetch(`js/examples/${file}.json`);
    if (res && res.ok !== false) {
      const data = await res.json();
      const source = {
        machine: data.machine,
        states: data.states,
        transitions: data.transitions,
        startId: data.startId,
        accepts: data.accepts,
        sigma: data.sigma,
        stackAlpha: data.stackAlpha,
        outputAlpha: data.outputAlpha,
        tapeCount: data.tapeCount
      };
      spec = machineToSpec(source);
      spec.title = data.meta?.title || 'Example';
      spec.blurb = data.meta?.blurb || '';
      // Only a couple of tests: the few-shot is teaching the shape, not the
      // coverage, and every extra line here is paid for on every request.
      spec.tests = (data.meta?.inputs || []).slice(0, 3).map(t => ({
        w: t.w || 'ε',
        ...(t.expect ? { expect: t.expect } : {}),
        ...(t.out !== undefined ? { out: t.out } : {})
      }));
    }
  } catch (e) {
    spec = null;
  }

  fewShotCache.set(machine, spec);
  return spec;
}

/** Test seam — the cache is module-level state and must not cross tests. */
export function _clearFewShotCache() {
  fewShotCache.clear();
}

// ══════════════════════════════════════════════════════════════════
//  THE SCHEMA BLOCK
// ══════════════════════════════════════════════════════════════════

function schemaBlock(machine, { notes = false } = {}) {
  const cfg = getMachineConfig(machine);
  const stateFields = stateFieldsFor(machine);
  const transFields = transitionFieldsFor(machine);
  const kind = testKindFor(machine);

  const alphabets = [`  "sigma": [ … ],                 the input alphabet Σ`];
  if (cfg.hasStack) {
    const label = cfg.hasTape ? 'the tape alphabet Γ (must contain the blank)' : 'the stack alphabet Γ (must contain the bottom marker)';
    alphabets.push(`  "stackAlpha": [ … ],             ${label}`);
  }
  if (cfg.isTransducer) alphabets.push(`  "outputAlpha": [ … ],            the output alphabet Δ`);
  if (machine === 'MTM') alphabets.push(`  "tapeCount": ${App.tapeCount},                   number of tapes (2–4)`);

  const testLine = kind === 'omega'
    ? `  "tests": [ { "w": "a(bc)", "expect": "accept" }, … ]   ω-words as u(v): stem u, then v repeated forever`
    : kind === 'output'
      ? `  "tests": [ { "w": "abb", "out": "011" }, … ]          the exact output word this machine emits`
      : `  "tests": [ { "w": "abb", "expect": "accept" }, … ]    "accept" or "reject"`;

  return [
    '{',
    '  "plan": "one sentence on the idea behind your construction",',
    `  "machine": "${machine}",`,
    '  "title": "a short name for this machine",',
    '  "blurb": "one or two sentences a student would find useful",',
    ...alphabets,
    '  "states": [',
    `    { ${stateFields.map(f => `"${f}": …`).join(', ')} }`,
    '  ],',
    '  "transitions": [',
    `    { ${transFields.map(f => `"${f}": …`).join(', ')} }`,
    '  ],',
    testLine,
    // Only offered when the user asked for it — an unasked-for sticky note on
    // someone's diagram is clutter, not an explanation.
    ...(notes
      ? ['  "notes": [ { "text": "one insight about the construction", "anchor": "<a state name>" } ]   at most two']
      : []),
    '}'
  ].join('\n');
}

function fieldGlossary(machine) {
  const lines = [];
  lines.push('State fields:');
  stateFieldsFor(machine).forEach(f => lines.push(`  ${f} — ${STATE_FIELD_DOCS[f] || ''}`));
  lines.push('Transition fields (every transition carries all of them):');
  transitionFieldsFor(machine).forEach(f => lines.push(`  ${f} — ${FIELD_DOCS[f] || ''}`));
  return lines.join('\n');
}

// ══════════════════════════════════════════════════════════════════
//  THE RULES THAT ARE NOT NEGOTIABLE
// ══════════════════════════════════════════════════════════════════
//  These duplicate the linter deliberately. The linter is what makes the
//  feature correct; saying the same thing here is what keeps most requests
//  from needing a repair round in the first place.

function machineRules(machine) {
  const cfg = getMachineConfig(machine);
  const sym = App.config.sym;
  const rules = [];

  if (hasSingleValuedDelta(machine)) {
    rules.push(`${machine} is DETERMINISTIC. No state may have two transitions that could both apply to the same situation. Check every state before you answer.`);
  } else {
    rules.push(`${machine} is nondeterministic: several transitions may apply at once, and the machine accepts if any run accepts.`);
  }

  rules.push(cfg.hasEpsilon
    ? `ε-transitions are allowed. Write the read symbol as "${sym.eps}" to consume no input.`
    : `ε-transitions are NOT allowed in a ${machine}. Every transition must read a real symbol.`);

  rules.push(`"${sym.any}" as a read symbol is a wildcard matching any input symbol. A concrete symbol beats it out of the same state.`);

  if (cfg.hasStack && !cfg.hasTape) {
    rules.push(`The stack starts holding "${sym.stackBottom}". Use "${sym.eps}" for pop to mean "do not pop" and for push to mean "push nothing". A multi-character push string lands with its leftmost character on top.`);
  }
  if (cfg.hasTape) {
    rules.push(`The blank symbol is "${sym.blank}". Γ must contain it and every symbol of Σ. A tape transition must give both "write" and "move".`);
  }
  if (cfg.hasEndMarkers) {
    rules.push(`The input is bracketed by the end markers "${sym.leftMarker}" and "${sym.rightMarker}". They are read from the tape, and they must NOT appear in Σ.`);
  }
  if (isTwoWayFA(machine)) {
    rules.push(`The head moves in both directions: every transition must give "move" as "L", "R" or "S".`);
  }
  if (cfg.isWeighted) {
    rules.push(`For every state and every input symbol, the weights of the transitions leaving that state on that symbol must sum to exactly 1. A word is accepted when its acceptance probability exceeds the cut-point ${App.config.pfaCutPoint}.`);
  }
  if (isOmegaAutomaton(machine)) {
    const acc = OmegaAcceptance[omegaAcceptanceOf(machine)];
    rules.push(`Acceptance is ${acc.label}: ${acc.say}. The input is an infinite word written u(v) — the stem u, then v repeated forever.`);
    if (usesParityPriorities(machine)) {
      rules.push(`There is NO set of accepting states. Every state carries a "priority" integer instead; do not mark states as accepting.`);
    }
    if (acc.structural) {
      rules.push(`Additionally, every cycle in the automaton must lie wholly inside the accepting set or wholly outside it.`);
    }
  }
  if (cfg.isTransducer) {
    rules.push(machine === 'Moore'
      ? `A Moore machine emits from the state: give each state an "out". Transitions carry no output.`
      : `Output is emitted per transition. Use "" for a move that emits nothing.`);
  }
  if (isAnyTM(machine)) {
    rules.push(`Halt by moving to an accepting state. A run with no applicable transition halts and rejects.`);
  }

  rules.push(`Use at most ${MAX_SPEC_STATES} states, and prefer the smallest machine that is correct.`);
  return rules.map((r, i) => `${i + 1}. ${r}`).join('\n');
}

// ══════════════════════════════════════════════════════════════════
//  ASSEMBLY
// ══════════════════════════════════════════════════════════════════

export async function buildSystemPrompt(machine = App.machine, { notes = false } = {}) {
  const cfg = getMachineConfig(machine);
  const fewShot = await loadFewShot(machine);

  const parts = [
    `You build finite-state machines for Automata Playground, a teaching tool. You are given a request and you answer with one machine, as JSON. Nothing else.`,
    ``,
    `TARGET MODEL: ${machine} — ${cfg.fullName}.`,
    ``,
    `OUTPUT FORMAT — a single JSON object, no prose, no code fences, keys in this order:`,
    schemaBlock(machine, { notes }),
    ``,
    fieldGlossary(machine),
    ``,
    `NOTATION IN THIS WORKSPACE — use these exact characters:`,
    `  ε (empty / no move) = "${App.config.sym.eps}"`,
    `  wildcard            = "${App.config.sym.any}"`,
    ...(cfg.hasTape ? [`  blank               = "${App.config.sym.blank}"`] : []),
    ...(cfg.hasStack && !cfg.hasTape ? [`  stack bottom        = "${App.config.sym.stackBottom}"`] : []),
    ...(cfg.hasEndMarkers ? [`  end markers         = "${App.config.sym.leftMarker}" and "${App.config.sym.rightMarker}"`] : []),
    ``,
    `RULES FOR ${machine}:`,
    machineRules(machine),
    ``,
    `TESTS ARE MANDATORY AND THEY WILL BE EXECUTED.`,
    `Give at least ${MIN_SPEC_TESTS} tests, including the shortest interesting word and at least one that must be rejected. The app runs them against the machine you just described, using its real simulator, before drawing anything. If your predictions do not match what your machine does, you will be asked to fix it — so trace them yourself first.`
  ];

  const grounding = guideGrounding(machine);
  if (grounding) {
    parts.push(``, `REFERENCE — what a ${machine} is, from this app's own documentation:`, grounding);
  }

  if (fewShot) {
    parts.push(
      ``,
      `A COMPLETE, VALID ANSWER for a different ${machine} — copy this shape exactly:`,
      JSON.stringify(fewShot, null, 1)
    );
  }

  return parts.join('\n');
}

/**
 * The user turn. `mode` is 'build' or 'edit'; the canvas is only attached in
 * edit mode or when the user has explicitly asked for it.
 */
export function buildUserMessage({ prompt, mode, canvasSpec = null, followUp = null }) {
  const parts = [];

  if (followUp) {
    parts.push(
      `Earlier in this session the user asked: "${followUp.prompt}"`,
      `You produced: ${followUp.summary}`,
      `They are now following up. Treat the request below as a correction to that machine.`,
      ``
    );
  }

  if (canvasSpec) {
    parts.push(
      mode === 'edit'
        ? `THE MACHINE CURRENTLY ON THE CANVAS — modify this. Keep the names of every state you are not changing, so the diagram survives the edit:`
        : `FOR CONTEXT, the machine currently on the canvas:`,
      JSON.stringify(canvasSpec),
      ``
    );
  } else if (mode === 'edit') {
    parts.push(`The canvas is empty, so build the machine from scratch.`, ``);
  }

  parts.push(`REQUEST: ${prompt}`);
  parts.push(``, `Answer with the JSON object only.`);
  return parts.join('\n');
}

/**
 * The repair turn. Generated, never free text: the failures the simulator and
 * linter actually found, capped so a wide failure cannot crowd out the
 * original request.
 */
export function buildRepairMessage({ prompt, spec, failures = [], findings = [] }) {
  const parts = [
    `Your previous answer was:`,
    JSON.stringify(spec),
    ``
  ];

  if (failures.length) {
    parts.push(`It failed ${failures.length} of the checks you predicted:`);
    failures.slice(0, 8).forEach(f => parts.push(`  ${f}`));
    parts.push(``);
  }

  if (findings.length) {
    parts.push(`Problems found in the machine itself:`);
    findings.slice(0, 6).forEach(f => parts.push(`  · ${f.message}`));
    parts.push(``);
  }

  parts.push(
    `The original request was: ${prompt}`,
    ``,
    `Return the corrected machine. Same JSON schema, same key order, no prose.`
  );
  return parts.join('\n');
}

/** Starter prompts for the idle palette, tailored to the current machine. */
export function starterPrompts(machine = App.machine) {
  const cfg = getMachineConfig(machine);
  if (isOmegaAutomaton(machine)) {
    return [
      'infinitely many a\'s',
      'only finitely many b\'s',
      'after every a, eventually a b'
    ];
  }
  if (cfg.hasTape) {
    return [
      'accepts aⁿbⁿcⁿ',
      'decides whether the input is a palindrome',
      'appends a 1 to the end of the input'
    ];
  }
  if (cfg.hasStack) {
    return [
      'balanced parentheses',
      'aⁿbⁿ for n ≥ 1',
      'strings with twice as many a\'s as b\'s'
    ];
  }
  if (cfg.isTransducer) {
    return [
      'outputs 1 whenever it has seen an even number of a\'s',
      'replaces every a with bb',
      'a binary increment'
    ];
  }
  return [
    'strings where every a is followed by a b',
    'binary numbers divisible by 3',
    'an even number of a\'s and an odd number of b\'s'
  ];
}

/** Every machine name, for the "did you mean a different model" hint. */
export function knownMachines() {
  return Object.keys(MachineTypes);
}
