// ======================================================================
// THEORY VIEW
// ======================================================================

const THEORY_CARD_IDS = [
  'th-fa',
  'th-regular',
  'th-rg',
  'th-regex',
  'th-decision',
  'th-cfl',
  'th-cfg-analysis',
  'th-cfg-normal',
  'th-pda-cfg',
  'th-tm',
  'th-utm-ndtm',
  'th-undecidable',
  'th-complexity',
  'th-algorithms',
  'th-closure-card',
  'th-nerode',
  'th-moore',
  'th-mealy',
  'th-mtm'
];

function theoryNavClick(link) {
  document.querySelectorAll('.theory-nav-link').forEach(l => l.classList.remove('active'));
  link.classList.add('active');

  const targetId = link.getAttribute('href').slice(1);
  const allSections = ['th-hierarchy', 'th-cards-section', 'th-pump', 'th-closure-tbl', 'th-pump-cfl', 'th-decidability'];
  allSections.forEach(id => {
    const el = $(id);
    if (el) el.style.display = 'none';
  });

  if (THEORY_CARD_IDS.includes(targetId)) {
    const sec = $('th-cards-section');
    if (sec) sec.style.display = '';
    document.querySelectorAll('#theory-grid .theory-card').forEach(card => {
      card.style.display = card.id === targetId ? '' : 'none';
    });
  } else {
    const sec = $(targetId);
    if (sec) sec.style.display = '';
  }

  const content = $('v-theory')?.querySelector('.algo-content');
  if (content) content.scrollTo({ top: 0, behavior: 'smooth' });
}

function renderTheoryView() {
  const cards = [
    {
      id: 'th-fa',
      color: 'var(--accent)',
      title: 'Finite Automata',
      sub: 'DFA · NFA · EPSILON-NFA · COMPUTATION MODELS',
      body: `<b>Core Models</b>
A deterministic finite automaton (DFA) is a 5-tuple <em>M = (Q, Sigma, delta, q0, F)</em>, where <em>Q</em> is a finite state set, <em>Sigma</em> is the input alphabet, <em>delta: Q x Sigma -> Q</em> is a total transition function, <em>q0</em> is the start state, and <em>F subseteq Q</em> is the accept set. Totality matters: on every symbol, from every state, the machine must know what to do. When a transition seems "missing," the standard repair is to add a trap state and route all undefined moves there.

<b>Nondeterminism</b>
An NFA replaces single-valued transitions with set-valued transitions: <em>delta: Q x Sigma -> 2^Q</em>. An epsilon-NFA extends this further by allowing moves that consume no input. A string is accepted if at least one computation path reaches an accept state after all input is consumed. Nondeterminism changes how we describe a machine, but not what class of languages it can recognize.

<b>Epsilon-Closure</b>
For a state <em>q</em>, the epsilon-closure is the set of states reachable from <em>q</em> by zero or more epsilon moves. This is the key bridge between epsilon-NFAs and ordinary NFAs or DFAs. Conceptually, epsilon-closure tells us which states are "already active" before reading the next real symbol.

<b>Equivalence of DFA, NFA, and Epsilon-NFA</b>
All three models recognize exactly the regular languages. The easy direction is containment: every DFA is an NFA, and every NFA is an epsilon-NFA. The nontrivial direction is simulation: subset construction turns any NFA into an equivalent DFA by treating each reachable set of NFA states as a single DFA state.

<b>Subset Construction and State Explosion</b>
If an NFA has <em>n</em> states, the equivalent DFA can have as many as <em>2^n</em> states. This upper bound is tight. The exponential blow-up is not an artifact of a poor algorithm; some regular languages truly require exponentially larger DFAs than their NFA descriptions.

<b>Computation Trees and Acceptance</b>
The app's NFA computation tree view illustrates a subtle but essential fact: rejection in an NFA means every branch fails, while acceptance means at least one branch succeeds. This existential semantics is why NFAs are often easier to design from a language description than DFAs.

<b>Minimal DFA</b>
Every regular language has a unique minimal DFA up to isomorphism. The states of the minimal DFA correspond to genuinely different "future behaviors" of prefixes. This is the intuition behind distinguishability, minimization, and the Myhill-Nerode theorem.` },
    {
      id: 'th-regular',
      color: 'var(--gold)',
      title: 'Regular Languages',
      sub: 'KLEENE THEOREM · CLOSURE · PUMPING LEMMA',
      body: `<b>Equivalent Characterizations</b>
A language is regular if and only if it is accepted by a DFA, if and only if it is accepted by an NFA, if and only if it can be described by a regular expression, and if and only if it can be generated by a regular grammar. This equivalence is one of the foundational organizing results of automata theory.

<b>Regular Operations</b>
Regular languages are built from the base languages <em>emptyset</em>, <em>{epsilon}</em>, and <em>{a}</em> for each symbol <em>a</em>, using union, concatenation, and Kleene star. These are not just syntactic conveniences; they correspond directly to machine constructions and algebraic closure principles.

<b>Closure Properties</b>
Regular languages are closed under union, intersection, complement, difference, concatenation, star, reversal, homomorphism, and inverse homomorphism. Closure is powerful in both directions. It lets us construct new regular languages from old ones, and it lets us derive contradictions when a supposed regular language would force a non-regular one through closure arguments.

<b>Pumping Lemma</b>
If <em>L</em> is regular, then there exists a pumping length <em>p</em> such that every sufficiently long string <em>w in L</em> can be written as <em>w = xyz</em> with <em>|xy| <= p</em>, <em>|y| >= 1</em>, and <em>xy^i z in L</em> for all <em>i >= 0</em>. The proof comes from repeated state visits in a DFA computation. A loop in the state graph induces a repeatable substring.

<b>How the Pumping Lemma Is Used Correctly</b>
The pumping lemma is a one-way implication: all regular languages pump, but not every pumping-looking language is regular for that reason alone. So the lemma is mainly a tool for proving non-regularity by contradiction. You choose a strategic long string and show that every valid split fails under some pumping exponent.

<b>Why Myhill-Nerode Is Stronger</b>
The pumping lemma gives a necessary condition for regularity. Myhill-Nerode gives a necessary and sufficient one. In practice, pumping lemma proofs are often more ad hoc, while Myhill-Nerode exposes the structural reason a language needs infinitely many states.

<b>Decision Problems</b>
Membership, emptiness, finiteness, equivalence, containment, and universality are all decidable for regular languages. This tractability is one reason regular languages are so central in compilers, model checking, text processing, and hardware verification.` },
    {
      id: 'th-rg',
      color: 'var(--gold)',
      title: 'Regular Grammars',
      sub: 'RIGHT-LINEAR · LEFT-LINEAR · RG <-> NFA',
      body: `<b>Shape of a Regular Grammar</b>
A right-linear grammar has productions of the form <em>A -> aB</em>, <em>A -> a</em>, or optionally <em>A -> epsilon</em>. A left-linear grammar has the mirrored shape <em>A -> Ba</em> or <em>A -> a</em>. Mixing left-linear and right-linear forms arbitrarily can produce languages that are not regular, so the directionality matters.

<b>Why Right-Linear Grammars Match NFAs</b>
Each nonterminal behaves like a state. A production <em>A -> aB</em> becomes a transition from state <em>A</em> to state <em>B</em> on symbol <em>a</em>. A production <em>A -> a</em> becomes a transition on <em>a</em> into a distinguished accepting state. An epsilon production makes the corresponding state accepting.

<b>NFA to Regular Grammar</b>
Going the other way, each state becomes a variable. A transition <em>p -a-> q</em> becomes a production <em>P -> aQ</em>. If <em>q</em> is accepting, we also need a terminal-only production when appropriate so the derivation can stop exactly when the automaton accepts. This correspondence is what the app's DFA/NFA to regular grammar conversion is visualizing.

<b>Left-Linear vs Right-Linear</b>
Both forms generate exactly the regular languages, but they encode derivations in different directions. Right-linear grammars line up more naturally with left-to-right machine computation, which is why they are the standard choice in automata textbooks and tools.

<b>What the Conversion Teaches</b>
These conversions are not only about representation changes. They show that "grammar generation" and "machine recognition" are two views of the same low-level memoryless process. That equivalence is the regular-language case of a broader theme that repeats with CFGs and PDAs.` },
    {
      id: 'th-regex',
      color: 'var(--accent)',
      title: 'Regular Expressions and Automata',
      sub: 'THOMPSON · GNFA · EPSILON ELIMINATION',
      body: `<b>Regular Expressions as Algebraic Descriptions</b>
A regular expression denotes a language, not a matching procedure. The primitives are <em>emptyset</em>, <em>epsilon</em>, and symbols; the constructors are union, concatenation, and star. Parentheses and precedence only control how these constructors are grouped.

<b>Thompson Construction</b>
Thompson's method compiles a regex into an equivalent epsilon-NFA by composing small gadgets. A symbol uses one edge. Union forks with epsilon transitions. Concatenation joins submachines end-to-start. Star creates a new entry/exit pattern that supports zero or more repetitions. The construction is linear in the size of the expression and guarantees a systematic machine shape.

<b>Why Epsilon Transitions Appear</b>
Epsilon edges are not a weakness of Thompson's construction; they are what makes the construction modular. They let us connect subexpressions without prematurely committing to specific symbol consumption. Later, epsilon-closure and elimination absorb those administrative moves into ordinary NFA or DFA behavior.

<b>State Elimination and GNFAs</b>
To convert an automaton back into a regex, we typically pass through a generalized NFA (GNFA), where edge labels are whole regular expressions. Eliminating a state means preserving every path that used to pass through that state by updating direct edges with concatenation, union, and star expressions. The final surviving edge from the new start to the new accept is the desired regex.

<b>Practical Consequence</b>
Regex to NFA and NFA to regex are not merely dual procedures. Together they complete the proof of Kleene's theorem in operational form: every regex has an automaton, and every finite automaton has a regex.

<b>What to Watch For</b>
State elimination often produces very large, hard-to-read expressions. That does not mean the algorithm is wrong; it reflects the fact that compact machine structure can expand when translated into algebraic syntax. The app's visual and textual conversions help make that expansion explicit.` },
    {
      id: 'th-decision',
      color: 'var(--green)',
      title: 'DFA Decision Procedures',
      sub: 'EMPTINESS · FINITENESS · UNIVERSALITY · EQUIVALENCE',
      body: `<b>Emptiness</b>
A DFA language is empty exactly when no accepting state is reachable from the start state. This is a graph reachability problem, so it is decidable in linear time in the size of the transition graph.

<b>Finiteness</b>
A regular language is infinite if and only if there exists a cycle reachable from the start state that can also reach an accept state. Intuitively, such a cycle can be pumped arbitrarily many times while still preserving a path to acceptance. If no such productive cycle exists, only finitely many accepted strings are possible.

<b>Universality</b>
A complete DFA is universal exactly when every state reachable from the start is accepting, or equivalently when the complement DFA has empty language. This demonstrates how complement and emptiness combine into a standard decision pattern.

<b>Equivalence</b>
Two DFAs are equivalent if they accept exactly the same language. A standard test constructs the symmetric-difference machine and checks emptiness. If the symmetric difference accepts some string, that string is a concrete witness of inequivalence.

<b>Complement and Product</b>
Complement is easy for total DFAs: flip accepting and rejecting states. Product construction combines machines so one component tracks each input in parallel. Choosing the accept condition appropriately yields union, intersection, difference, and symmetric difference.

<b>Why These Matter</b>
The app's decision-property tools are algorithmic expressions of deep closure facts. They show that regular languages are not just expressive; they are computationally manageable. This combination is why finite automata are used in so many automated reasoning tasks.` },
    {
      id: 'th-cfl',
      color: 'var(--green)',
      title: 'Context-Free Languages',
      sub: 'CFG · PDA · NPDA · PARSING · PUMPING',
      body: `<b>Context-Free Grammars</b>
A context-free grammar is a 4-tuple <em>G = (V, Sigma, R, S)</em> where each production has a single variable on the left. The defining idea is locality of rewriting: a variable can be expanded without looking at surrounding symbols. That single restriction already yields languages with nested structure, recursive syntax, and unbounded counting in one dimension.

<b>Derivations and Parse Trees</b>
Derivations are sequential rewrites; parse trees are their hierarchical form. Leftmost and rightmost derivations may differ as derivation sequences even when they describe the same tree. When they produce different trees for the same string, the grammar is ambiguous.

<b>Pushdown Automata</b>
PDAs extend finite automata with a stack. This extra unbounded but disciplined memory is exactly what is needed for balanced parentheses, nested scopes, and matched recursive constructs. In this app, <em>PDA</em> denotes the deterministic model, while <em>NPDA</em> denotes the general nondeterministic model.

<b>Determinism Is Subtle</b>
Deterministic PDAs are strictly weaker than general PDAs. Nondeterministic PDAs recognize exactly the context-free languages, but deterministic PDAs do not capture all CFLs. They still cover many useful language families, especially those designed for deterministic parsing, which is why parsing theory distinguishes general CFG membership from LL and LR subclasses.

<b>Pumping for CFLs</b>
The CFL pumping lemma comes from repeated variables on deep parse-tree paths. Unlike the regular pumping lemma, two regions are pumped in sync. The lemma is useful for showing that some languages require more than one stack discipline, but it is often technically trickier to apply.

<b>Closure Profile</b>
CFLs are closed under union, concatenation, star, reversal, homomorphism, and inverse homomorphism. They are not closed under general intersection or complement. However, CFLs are closed under intersection with regular languages, which is one of the most useful hybrid constructions in formal language proofs.` },
    {
      id: 'th-cfg-analysis',
      color: 'var(--green)',
      title: 'CFG Analysis and Parsing',
      sub: 'FIRST/FOLLOW · LL(1) · AMBIGUITY · DERIVATIONS',
      body: `<b>FIRST Sets</b>
FIRST(X) records which terminals can appear at the beginning of some string derived from <em>X</em>. For a terminal, FIRST is the terminal itself. For a variable, it is computed from productions, propagating epsilon where necessary. FIRST is the predictive summary of what can begin next.

<b>FOLLOW Sets</b>
FOLLOW(A) records which terminals may appear immediately to the right of variable <em>A</em> in some sentential form. The end marker belongs to FOLLOW of the start symbol. FOLLOW matters because epsilon-producing variables need a fallback lookahead set when no terminal is forced by FIRST.

<b>LL(1) Condition</b>
A grammar is LL(1) when one symbol of lookahead is enough to choose the correct production for each variable in a predictive parser. Formally, productions for the same nonterminal must have disjoint FIRST sets, and if one alternative can derive epsilon, its FOLLOW set must also be disjoint from the FIRST sets of the others.

<b>Left Recursion</b>
Immediate left recursion, such as <em>A -> A alpha | beta</em>, breaks naive top-down parsing because expansion can loop before consuming input. Eliminating left recursion rewrites the grammar into an equivalent form better suited for predictive parsing. This changes the grammar, not the language.

<b>Ambiguity</b>
Ambiguity means some string has more than one parse tree. The classic arithmetic-expression grammar without precedence or associativity rules is ambiguous because expressions like <em>id + id * id</em> admit multiple structural readings. Ambiguity is a property of the grammar, not necessarily of the language; some languages have both ambiguous and unambiguous grammars, while others are inherently ambiguous.

<b>Why the App Includes These Tools</b>
FIRST/FOLLOW, LL(1) table generation, derivations, parse trees, and ambiguity checks are all different windows onto the same question: how much of a string's structure is forced by the grammar, and how early can a parser know what to do next?` },
    {
      id: 'th-cfg-normal',
      color: 'var(--green)',
      title: 'Normal Forms and CYK',
      sub: 'CNF · GNF · CYK · GRAMMAR SIMPLIFICATION',
      body: `<b>Why Normal Forms Exist</b>
Normal forms are disciplined rewritings of grammars that preserve the language while enforcing a regular production shape. They are not usually the grammar form humans want to read, but they are the form algorithms want to consume.

<b>Chomsky Normal Form</b>
In CNF, every production is either <em>A -> BC</em> or <em>A -> a</em>, plus possibly <em>S -> epsilon</em> when epsilon belongs to the language. Converting to CNF typically proceeds by removing useless symbols, epsilon-productions, and unit productions, then binarizing longer right-hand sides.

<b>Why CNF Matters</b>
CNF makes every derivation tree essentially binary. That binary structure is exactly what dynamic-programming parsers like CYK exploit: every substring split corresponds to some binary decomposition.

<b>Greibach Normal Form</b>
In GNF, each production begins with a terminal: <em>A -> a alpha</em> where <em>alpha</em> is a string of variables. GNF is useful because every derivation step consumes one terminal immediately. It is closely tied to proofs about top-down derivation length and constructions from CFGs to PDAs.

<b>CYK Algorithm</b>
CYK decides whether a string belongs to a CFG in CNF by filling a triangular table. Each cell stores the variables that can derive a given substring. Length-1 substrings are filled from terminal productions; longer substrings are built by trying all split points and binary rules. Membership holds exactly when the start variable appears in the cell for the whole string.

<b>Simplification and Decidability</b>
Removing useless symbols and deciding emptiness or finiteness are not cosmetic cleanups. They help expose whether a grammar has productive derivations at all, whether it can generate arbitrarily long strings, and whether later conversions will carry dead structure into more complicated forms.` },
    {
      id: 'th-pda-cfg',
      color: 'var(--green)',
      title: 'PDA, NPDA, and CFG Equivalence',
      sub: 'CFG -> NPDA · PDA/NPDA -> CFG · TOP-DOWN · BOTTOM-UP',
      body: `<b>The Fundamental Equivalence</b>
Context-free languages are exactly the languages accepted by nondeterministic PDAs. This is the context-free analogue of the DFA/NFA/regex equivalence for regular languages, but the constructions are more intricate because the stack has to encode partially completed syntax.

<b>Top-Down CFG to NPDA</b>
The standard top-down construction starts with the grammar's start variable on the stack. If the top of the stack is a variable, the NPDA nondeterministically expands it using a production. If the top is a terminal matching the current input symbol, the machine consumes that symbol and pops it. Acceptance means the grammar has derived the input exactly.

<b>Bottom-Up Intuition</b>
Bottom-up constructions model reduction rather than prediction. The stack stores partially recognized material, and transitions simulate reversing derivation steps. This perspective connects more naturally to shift-reduce parsing and LR-style reasoning.

<b>PDA / NPDA to CFG</b>
The reverse construction is more technical. A common method introduces variables of the form <em>[p A q]</em>, intended to generate exactly the strings that take the machine from state <em>p</em> with stack symbol <em>A</em> on top to state <em>q</em> after that symbol has been removed. Productions encode the ways the automaton can consume input while matching pushes with corresponding later pops.

<b>Why Acceptance Mode Matters</b>
PDAs may accept by final state or by empty stack. These two conventions are equivalent in expressive power, but the conversion details differ. The app's explicit and empty-stack paradigms reflect that theoretical distinction.

<b>What This Section Should Teach</b>
The key lesson is not just that CFGs and NPDAs are equivalent. It is that syntax trees and stack behavior are two descriptions of the same nested dependency structure: one generative, one operational. The deterministic PDA model then sits inside that picture as the parsing-friendly but strictly smaller subclass.` },
    {
      id: 'th-tm',
      color: 'var(--orange)',
      title: 'Turing Machines',
      sub: 'DECIDABILITY · RECOGNIZABILITY · UNIVERSAL MODEL',
      body: `<b>Formal Model</b>
A standard single-tape Turing machine is a 7-tuple <em>M = (Q, Sigma, Gamma, delta, q0, q_accept, q_reject)</em>. The tape alphabet <em>Gamma</em> contains the input alphabet and the blank symbol. At each step the machine reads one cell, writes one symbol, moves left or right, and changes state.

<b>Recognition vs Decision</b>
A TM recognizes a language if it accepts every string in the language and may reject or loop on strings outside it. A TM decides a language if it halts on every input, accepting strings in the language and rejecting strings outside it. This halt-on-all-inputs condition is what separates decidable languages from merely recognizable ones.

<b>Why TMs Matter</b>
Finite automata have no unbounded memory; PDAs have one stack; TMs have unrestricted read-write tape. That qualitative jump is what makes TMs the standard model for general-purpose computation and for undecidability proofs.

<b>Configuration View</b>
A TM computation is best understood as a sequence of configurations: current state, full tape contents up to the used region, and head position. Many proofs in computability work by transforming machines into equivalent machines that manipulate configurations in a controlled way.

<b>Church-Turing Thesis</b>
The Church-Turing thesis is not a formal theorem. It is the claim that every effectively calculable procedure can be carried out by a Turing machine. Its strength comes from repeated confirmation across every standard computational model that has been studied seriously.

<b>The App's TM Features</b>
Single-tape simulation, universal-machine ideas, nondeterministic branching, and multi-tape variants all sit naturally under this section because they refine one central question: what changes computation speed or description style, and what changes computation power?` },
    {
      id: 'th-utm-ndtm',
      color: 'var(--orange)',
      title: 'UTM and Nondeterministic TMs',
      sub: 'SIMULATION · ENCODINGS · BRANCHING COMPUTATION',
      body: `<b>Universal Turing Machine</b>
A universal Turing machine (UTM) takes an encoding <em>&lt;M, w&gt;</em> and simulates machine <em>M</em> on input <em>w</em>. This is the formal ancestor of the stored-program computer: the program itself is data, and one fixed interpreter can execute many different machines from their descriptions.

<b>Why Encodings Matter</b>
Universality depends on being able to encode states, symbols, transitions, and input strings in a computable, unambiguous way. Once that is done, questions about machines become questions about strings, which is exactly what undecidability reductions exploit.

<b>Nondeterministic TMs</b>
An NDTM can branch into multiple possible next moves. It accepts if any branch accepts. This is the Turing-machine analogue of NFA semantics. Nondeterminism does not change language-recognition power for TMs, but it does change complexity-theoretic viewpoints, because polynomial-time nondeterminism gives rise to the class NP.

<b>Simulation by Dovetailing or BFS</b>
To simulate an NDTM deterministically, we cannot just follow one branch deeply, because another shallow branch might accept. Standard simulations enumerate configurations breadth-first or dovetail over branches so that every finite accepting path is eventually found.

<b>What the UTM Simulator Illustrates</b>
A UTM is one of the cleanest demonstrations that programs are objects inside computation, not outside it. The simulator makes that concrete by turning machine descriptions into inputs for another machine. That move is the gateway to self-reference, diagonalization, and the halting problem.` },
    {
      id: 'th-undecidable',
      color: 'var(--red)',
      title: 'Undecidability',
      sub: 'HALTING · ATM · REDUCTIONS · RICE',
      body: `<b>Acceptance and Halting Problems</b>
The language <em>A_TM = {&lt;M, w&gt; | M accepts w}</em> is recognizable but undecidable. The halting problem <em>HALT_TM = {&lt;M, w&gt; | M halts on w}</em> is also undecidable. These are not obscure corner cases; they are the baseline sources from which many other undecidable problems are derived.

<b>Diagonalization</b>
Turing's proof idea is to assume a perfect halting decider exists and then build a machine that contradicts its own prediction when run on its own description. The paradox is not a gimmick. It reveals that self-reference plus universal simulation creates questions no algorithm can settle uniformly.

<b>Recognizable vs Co-Recognizable</b>
If both a language and its complement are recognizable, then the language is decidable. This gives a clean test for showing some recognizable languages are not decidable: show the complement is not recognizable. That is the status of <em>A_TM</em>.

<b>Many-One Reductions</b>
To prove a new problem undecidable, we reduce a known undecidable problem to it. A computable function <em>f</em> maps instances of problem <em>A</em> to instances of problem <em>B</em> so that yes-instances stay yes and no-instances stay no. If <em>B</em> were decidable, then <em>A</em> would be too, which is impossible.

<b>Rice's Theorem</b>
Any nontrivial semantic property of the language recognized by a TM is undecidable. "Semantic" means it depends only on the language recognized, not on the syntactic presentation of the machine. Questions like emptiness, finiteness, universality, and "accepts epsilon" all fall under Rice's theorem.

<b>Why This Connects to the App</b>
The theory section distinguishes decidability tables for regular and context-free models from undecidability on TMs so users can see where the boundary shifts. The app's richer TM features should be paired with explanations of which questions remain algorithmically solvable and which do not.` },
    {
      id: 'th-complexity',
      color: 'var(--purple)',
      title: 'Complexity Theory',
      sub: 'P · NP · PSPACE · REDUCTIONS',
      body: `<b>Computation Cost, Not Just Computability</b>
Complexity theory asks how many resources an algorithm needs, usually time or space as a function of input length. Two problems may both be decidable, but one may require exponential time while another is solvable in polynomial time.

<b>Class P</b>
P is the class of languages decidable in polynomial time by a deterministic TM. It is the canonical tractability class because polynomial slowdowns remain manageable under reasonable changes of machine model.

<b>Class NP</b>
NP consists of languages decidable in polynomial time by a nondeterministic TM, or equivalently languages whose yes-instances have polynomial-size certificates verifiable in polynomial time. This verifier viewpoint is often the more useful one in proofs and algorithm design.

<b>Polynomial-Time Reductions</b>
A problem <em>A</em> reduces to problem <em>B</em> if every instance of <em>A</em> can be translated to an instance of <em>B</em> in polynomial time while preserving the answer. NP-complete problems are the hardest problems inside NP under these reductions.

<b>NP-Completeness</b>
SAT was the first NP-complete problem. To prove another problem NP-complete, we show it belongs to NP and that a known NP-complete problem reduces to it. The reduction direction matters: to show <em>B</em> is hard, reduce something already known hard into <em>B</em>.

<b>Beyond NP</b>
PSPACE captures problems solvable with polynomial memory. We know <em>P subseteq NP subseteq PSPACE subseteq EXP</em>. Some containments are known to be strict, while the most famous one, whether <em>P = NP</em>, remains open.

<b>Why This Belongs Beside Automata Theory</b>
Automata theory classifies what can be recognized with different memory models. Complexity theory refines that by classifying how efficiently those recognitions can be carried out. Multi-tape TMs, CYK, and nondeterministic simulation all connect directly to that refinement.` },
    {
      id: 'th-algorithms',
      color: 'var(--accent)',
      title: 'Key Algorithms',
      sub: 'CONSTRUCTIONS · NORMAL FORMS · DECISION TESTS',
      body: `<b>Finite-Automata Algorithms</b>
The app implements epsilon-closure computation, subset construction, table-filling minimization, dead-state analysis, complement, product construction, emptiness, finiteness, universality, and equivalence. These are the standard operational toolkit for regular languages.

<b>Regex and Grammar Algorithms</b>
Regex to epsilon-NFA is handled by Thompson construction. DFA or NFA to regex uses generalized-NFA elimination. Regular-grammar and automaton conversions expose the equivalence among the main regular formalisms.

<b>CFG Algorithms</b>
FIRST/FOLLOW computation, LL(1) table generation, left-recursion removal, CNF and GNF conversion, CYK parsing, derivation generation, and parse-tree construction form the grammar-analysis side of the app. Each corresponds to a standard theorem or construction in formal-language theory.

<b>PDA and TM Algorithms</b>
CFG to NPDA and PDA/NPDA to CFG illustrate language-class equivalence on the context-free level, while the separate PDA mode highlights what changes when determinism is enforced. UTM, NDTM, and TM-to-grammar features represent the more advanced computability side of the project.

<b>Pedagogical Point</b>
This app is not just a simulator. It is a constructive theory environment. Almost every algorithm in the interface is there because it either proves an equivalence theorem, decides a property, or exposes the shape of a classical proof.` },
    {
      id: 'th-closure-card',
      color: 'var(--green)',
      title: 'Closure Properties',
      sub: 'REGULAR · CFL · CSL · RE · RECURSIVE',
      body: `<b>What Closure Means</b>
A class is closed under an operation when applying the operation to members of the class never takes you outside the class. Closure results are often the quickest way to understand the strengths and weaknesses of a computational model.

<b>Regular Languages</b>
Regular languages enjoy very strong closure behavior because finite control can be combined in systematic product-style ways. Complement, intersection, and reversal are especially clean examples.

<b>Context-Free Languages</b>
CFLs are closed under union, concatenation, star, reversal, homomorphism, and inverse homomorphism, but not under general intersection or complement. This asymmetry is one of the clearest signs that one stack is powerful but limited.

<b>Recursive and RE Languages</b>
Recursive languages are closed under the Boolean operations because deciders always halt. RE languages are closed under union and intersection but not complement in general; that failure is exactly what separates recognizability from full decidability.

<b>How to Use Closure in Proofs</b>
Closure arguments usually follow one of two patterns: build a target language from known languages using allowed operations, or assume a language belongs to a class and derive an impossible closure consequence from it. The closure table and decision tables in the theory view are meant to support both styles of reasoning.` },
    {
      id: 'th-nerode',
      color: 'var(--orange)',
      title: 'Myhill-Nerode Theorem',
      sub: 'DISTINGUISHABILITY · MINIMALITY · NON-REGULARITY',
      body: `<b>Distinguishable Prefixes</b>
Two strings <em>x</em> and <em>y</em> are distinguishable with respect to a language <em>L</em> if there exists some extension <em>z</em> such that exactly one of <em>xz</em> and <em>yz</em> lies in <em>L</em>. If no such <em>z</em> exists, the strings are equivalent for the purposes of future acceptance.

<b>Equivalence Classes as States</b>
The Myhill-Nerode relation partitions all strings into equivalence classes of identical future behavior. If there are only finitely many such classes, they can serve directly as DFA states. This gives a conceptual proof that regularity is exactly finite-index distinguishability.

<b>Minimal DFA</b>
The minimal DFA for a regular language has exactly one state per Myhill-Nerode class. This is why minimal DFAs are unique up to renaming: the classes are determined by the language itself, not by a particular construction procedure.

<b>Proving Non-Regularity</b>
To show a language is not regular, it is enough to produce infinitely many pairwise distinguishable strings. This is often cleaner than a pumping-lemma proof because it targets the reason finite memory fails: too many genuinely different future obligations.

<b>Connection to Minimization</b>
DFA minimization algorithms are computational versions of Myhill-Nerode reasoning. They start from a given automaton and merge states only when no distinguishing continuation exists.` },
    {
      id: 'th-moore',
      color: 'var(--purple)',
      title: 'Moore Machines',
      sub: 'OUTPUT ON STATES · SYNCHRONOUS TRANSDUCTION',
      body: `<b>Definition</b>
A Moore machine is a finite-state transducer whose output depends only on the current state. Formally, it has a state-transition function <em>delta</em> and an output function <em>lambda: Q -> Delta</em>. Because output is state-based, the machine emits an initial output before any input is read.

<b>Behavioral Consequence</b>
Outputs change only when the state changes. This gives Moore machines a synchronous, stable feel that is especially useful in hardware and control systems, where glitch-free output changes matter.

<b>Expressive Relationship to Mealy Machines</b>
Moore and Mealy machines realize the same finite-state transductions up to the usual convention about initial output alignment. However, a Moore machine may need more states because output information is encoded into state identity itself.

<b>Why the Table View Matters</b>
The app's Moore table tool makes visible that transition behavior and output behavior are separated. That separation is exactly the design tradeoff Moore machines make: clarity and timing stability in exchange for possible state blow-up.` },
    {
      id: 'th-mealy',
      color: 'var(--accent)',
      title: 'Mealy Machines',
      sub: 'OUTPUT ON TRANSITIONS · COMPACT TRANSDUCERS',
      body: `<b>Definition</b>
A Mealy machine is a finite-state transducer with output function <em>lambda: Q x Sigma -> Delta</em>. The output is determined by the current state together with the current input symbol, so output is attached to transitions rather than states.

<b>Operational Effect</b>
For an input of length <em>n</em>, a Mealy machine emits exactly <em>n</em> output symbols. There is no separate initial output. This often yields a more compact encoding than a Moore machine because output need not be baked into every destination state.

<b>Conversion to and from Moore</b>
Converting Moore to Mealy is straightforward: each transition inherits the output of its destination state. Converting Mealy to Moore usually requires splitting states according to incoming output labels so that each Moore state has a single fixed output.

<b>Applications</b>
Mealy machines are natural for tokenization, streaming transforms, and protocol response logic, where the emitted symbol depends immediately on the input just seen. They are also the conceptual stepping stone toward richer finite-state transducers used in language technology.` },
    {
      id: 'th-mtm',
      color: 'var(--orange)',
      title: 'Multi-Tape Turing Machines',
      sub: 'EFFICIENCY · SIMULATION · MACHINE VARIANTS',
      body: `<b>Definition</b>
A <em>k</em>-tape TM reads and writes on <em>k</em> tapes simultaneously, with one head per tape. The transition function consumes a <em>k</em>-tuple of tape symbols and returns a new state, a <em>k</em>-tuple of symbols to write, and a movement choice for each head.

<b>Power vs Efficiency</b>
Multi-tape TMs do not recognize more languages than single-tape TMs, but they can be dramatically faster. The standard simulation of a <em>k</em>-tape machine by a single-tape machine incurs at most quadratic overhead.

<b>Why They Matter in Complexity Theory</b>
Because multi-tape and single-tape models are polynomially equivalent, complexity classes like P do not depend on which one we choose. That robustness is why the theory can focus on asymptotic classes rather than machine-specific engineering details.

<b>Practical Intuition</b>
Extra tapes act like organized workspace. One tape may hold the input, another a stack-like scratch structure, and another intermediate data. This makes algorithm design much closer to how programmers think, even though the underlying power is unchanged.

<b>Connection to the App</b>
The MTM tools should be read as a lesson in efficiency and encoding, not a lesson in extra computability. They demonstrate a recurring theme in theory: richer machine structure often changes complexity before it changes expressiveness.` }
  ];

  const grid = $('theory-grid');
  if (grid) {
    grid.innerHTML = cards.map(card => `
<div class="theory-card" id="${card.id}" style="--accent-c:${card.color};scroll-margin-top:20px">
  <div class="tc-title">${card.title}</div>
  <div class="tc-sub">${card.sub}</div>
  <div class="tc-body" style="white-space:pre-line">${card.body}</div>
</div>`).join('');
  }

  renderClosureTable();
  renderPumpVis();
  setTimeout(() => renderCFLPumpVis(), 50);

  const initLink = $('tnl-hierarchy');
  if (initLink) theoryNavClick(initLink);
}

function renderClosureTable() {
  const el = $('closure-table');
  if (!el) return;

  const ops = ['Union', 'Intersection', 'Complement', 'Concatenation', 'Kleene *', 'Homomorphism', 'Inverse Hom.', 'Reversal'];
  const classes = ['Regular', 'CFL', 'CSL', 'Recursive', 'RE'];
  const closed = {
    Regular: [1, 1, 1, 1, 1, 1, 1, 1],
    CFL: [1, 0, 0, 1, 1, 1, 1, 1],
    CSL: [1, 1, 1, 1, 1, 1, 1, 1],
    Recursive: [1, 1, 1, 1, 1, 1, 1, 1],
    RE: [1, 1, 0, 1, 1, 1, 1, 1]
  };

  let html = '<div style="overflow-x:auto"><table class="result-table"><thead><tr><th>Class</th>';
  html += ops.map(op => `<th>${op}</th>`).join('');
  html += '</tr></thead><tbody>';

  classes.forEach(cls => {
    html += `<tr><th style="text-align:left;background:var(--surface2)">${cls}</th>`;
    closed[cls].forEach(v => {
      html += `<td style="color:${v ? 'var(--green)' : 'var(--red)'}">${v ? '&#10003;' : '&#10007;'}</td>`;
    });
    html += '</tr>';
  });

  html += '</tbody></table></div>';
  el.innerHTML = html;
}

function renderPumpVis() {
  const pEl = $('pump-vis');
  const pw = $('pump-w');
  if (!pEl || !pw) return;

  const x = parseInt($('pump-x')?.value, 10) || 0;
  const y = parseInt($('pump-y')?.value, 10) || 3;
  const p = parseInt($('pump-p')?.value, 10) || 3;
  const pi = parseInt($('pump-i')?.value, 10) || 2;

  if (x + y > pw.value.length) {
    $('pump-result').innerHTML = '<div class="pump-result fail">|x| + |y| exceeds string length.</div>';
    return;
  }
  if (y < 1) {
    $('pump-result').innerHTML = '<div class="pump-result fail">|y| must be at least 1.</div>';
    return;
  }
  if (x + y > p) {
    $('pump-result').innerHTML = '<div class="pump-result fail">|xy| must be at most p.</div>';
    return;
  }

  const xPart = pw.value.slice(0, x);
  const yPart = pw.value.slice(x, x + y);
  const zPart = pw.value.slice(x + y);
  const pumped = xPart + yPart.repeat(pi) + zPart;

  pEl.innerHTML =
    [...xPart].map(c => `<div class="pump-char x-part">${c}</div>`).join('') +
    [...yPart].map(c => `<div class="pump-char y-part">${c}</div>`).join('') +
    [...zPart].map(c => `<div class="pump-char z-part">${c}</div>`).join('');

  const info = `x = "${xPart}" (|x| = ${x})  y = "${yPart}" (|y| = ${y})  z = "${zPart}"`;
  $('pump-result').innerHTML = `<div style="font-size:.68rem;color:var(--text2);margin-bottom:6px">${info}</div>
<div class="pump-result ok">Pumped string xy^${pi}z = "${pumped}"<br>Check whether the pumped string still lies in your language.</div>`;
}
