// ══════════════════════════════════════════════════════════════════
//  LEXER CODE GENERATION
// ══════════════════════════════════════════════════════════════════
// A built lexer (js/lexer/build.js) → a standalone, dependency-free source
// file. Import-free apart from the builder's constants.
//
// Every target is the same program: the tables the builder produced, and a
// maximal-munch driver around them — run the DFA as far as it goes, return to
// the last accepting state, emit (or skip) that rule's token, repeat. The
// driver is the one runLexer() in build.js runs in the app, so the token
// stream on screen is the token stream the generated code produces;
// tests/lexer.test.js runs the JavaScript output in a sandbox, and the Python
// and C outputs too where an interpreter and a compiler are installed, and
// compares them token for token.
//
// Tables rather than generated `switch` code: a lexer's DFA is wide (a column
// per character class) and its states are anonymous, so a switch would be
// hundreds of cases nobody reads. The table is also what flex and re2c's
// table mode emit, which is the reference a reader will compare against.

const WRAP = 96;

function rows(values, indent, fmt = String) {
  const lines = [];
  let cur = '';
  values.forEach((v, i) => {
    const piece = fmt(v) + (i < values.length - 1 ? ',' : '');
    if (cur && (indent + cur + ' ' + piece).length > WRAP) { lines.push(indent + cur); cur = piece; }
    else cur = cur ? cur + ' ' + piece : piece;
  });
  if (cur) lines.push(indent + cur);
  return lines.join('\n');
}

function asciiClasses(lx) {
  const out = [];
  for (let c = 0; c < 128; c++) out.push(lx.classOf.has(c) ? lx.classOf.get(c) : -1);
  return out;
}

function extraClasses(lx) {
  return [...lx.classOf.entries()].filter(([c]) => c >= 128).sort((a, b) => a[0] - b[0]);
}

function header(lx, comment, lang) {
  const lines = [
    `Lexer generated by AutomataStudio — ${lx.rules.length} rules, ${lx.nStates}-state DFA over ${lx.nClasses} character classes.`,
    'Longest match wins; on a tie the rule listed first wins.',
    '',
    'Rules:',
    ...lx.rules.map(r => `  ${r.skip ? 'skip ' : ''}${r.name.padEnd(12)} ${r.pattern}`)
  ];
  if (lang === 'c' && extraClasses(lx).length) {
    lines.push('', 'Note: this C lexer reads bytes. The rules name non-ASCII characters, which', 'it cannot match; use the JavaScript or Python output for Unicode input.');
  }
  if (comment === '#') return lines.map(l => ('# ' + l).trimEnd()).join('\n');
  if (comment === '//') return lines.map(l => ('// ' + l).trimEnd()).join('\n');
  return ['/*', ...lines.map(l => (' * ' + cSafe(l)).trimEnd()), ' */'].join('\n');
}

// A rule's pattern can contain `*/`, which would end a C block comment early.
const cSafe = s => s.replace(/\*\//g, '*\\/');

export function emitLexerJS(lx) {
  const names = lx.rules.map(r => JSON.stringify(r.name));
  const extras = extraClasses(lx);
  return `${header(lx, '//', 'js')}
'use strict';

const TOKEN_NAMES = [
${rows(names, '  ')}
];
const SKIP = [
${rows(lx.rules.map(r => r.skip), '  ')}
];
const N_CLASSES = ${lx.nClasses};
// Character class of each ASCII character; -1 where no rule can read it.
const ASCII_CLASS = [
${rows(asciiClasses(lx), '  ')}
];
const EXTRA_CLASS = new Map([${extras.map(([c, k]) => `[${c}, ${k}]`).join(', ')}]);
// TRANS[state * N_CLASSES + class] is the next state, or -1.
const TRANS = [
${rows([...lx.trans], '  ')}
];
// ACCEPT[state] is the index of the rule it accepts, or -1.
const ACCEPT = [
${rows([...lx.accept], '  ')}
];

class LexError extends Error {
  constructor(message, line, col) {
    super(message);
    this.name = 'LexError';
    this.line = line;
    this.col = col;
  }
}

function classOf(cp) {
  if (cp < 128) return ASCII_CLASS[cp];
  const k = EXTRA_CLASS.get(cp);
  return k === undefined ? -1 : k;
}

/** Split \`input\` into tokens: [{ type, text, line, col }]. Throws LexError. */
function tokenize(input) {
  const chars = Array.from(input);
  const tokens = [];
  let pos = 0, line = 1, col = 1;
  while (pos < chars.length) {
    let state = ${lx.start}, lastRule = -1, lastEnd = pos;
    for (let i = pos; i < chars.length; i++) {
      const k = classOf(chars[i].codePointAt(0));
      if (k < 0) break;
      state = TRANS[state * N_CLASSES + k];
      if (state < 0) break;
      if (ACCEPT[state] >= 0) { lastRule = ACCEPT[state]; lastEnd = i + 1; }
    }
    if (lastRule < 0) {
      throw new LexError(\`Unexpected \${JSON.stringify(chars[pos])} at line \${line}, column \${col}\`, line, col);
    }
    const text = chars.slice(pos, lastEnd).join('');
    if (!SKIP[lastRule]) tokens.push({ type: TOKEN_NAMES[lastRule], text, line, col });
    for (let i = pos; i < lastEnd; i++) {
      if (chars[i] === '\\n') { line++; col = 1; } else col++;
    }
    pos = lastEnd;
  }
  return tokens;
}

if (typeof module !== 'undefined' && module.exports) module.exports = { tokenize, LexError, TOKEN_NAMES };
`;
}

export function emitLexerPython(lx) {
  const extras = extraClasses(lx);
  const pyBool = b => (b ? 'True' : 'False');
  return `${header(lx, '#', 'py')}
from typing import List, NamedTuple

TOKEN_NAMES = (
${rows(lx.rules.map(r => JSON.stringify(r.name)), '    ')}
)
SKIP = (
${rows(lx.rules.map(r => r.skip), '    ', pyBool)}
)
N_CLASSES = ${lx.nClasses}
# Character class of each ASCII character; -1 where no rule can read it.
ASCII_CLASS = (
${rows(asciiClasses(lx), '    ')}
)
EXTRA_CLASS = {${extras.map(([c, k]) => `${c}: ${k}`).join(', ')}}
# TRANS[state * N_CLASSES + cls] is the next state, or -1.
TRANS = (
${rows([...lx.trans], '    ')}
)
# ACCEPT[state] is the index of the rule it accepts, or -1.
ACCEPT = (
${rows([...lx.accept], '    ')}
)


class Token(NamedTuple):
    type: str
    text: str
    line: int
    col: int


class LexError(Exception):
    def __init__(self, message: str, line: int, col: int):
        super().__init__(message)
        self.line = line
        self.col = col


def _class_of(ch: str) -> int:
    cp = ord(ch)
    return ASCII_CLASS[cp] if cp < 128 else EXTRA_CLASS.get(cp, -1)


def tokenize(text: str) -> List[Token]:
    """Split \`text\` into tokens. Raises LexError on input no rule matches."""
    tokens: List[Token] = []
    pos, line, col = 0, 1, 1
    while pos < len(text):
        state, last_rule, last_end = ${lx.start}, -1, pos
        for i in range(pos, len(text)):
            k = _class_of(text[i])
            if k < 0:
                break
            state = TRANS[state * N_CLASSES + k]
            if state < 0:
                break
            if ACCEPT[state] >= 0:
                last_rule, last_end = ACCEPT[state], i + 1
        if last_rule < 0:
            raise LexError(f"Unexpected {text[pos]!r} at line {line}, column {col}", line, col)
        lexeme = text[pos:last_end]
        if not SKIP[last_rule]:
            tokens.append(Token(TOKEN_NAMES[last_rule], lexeme, line, col))
        for ch in lexeme:
            if ch == "\\n":
                line, col = line + 1, 1
            else:
                col += 1
        pos = last_end
    return tokens


if __name__ == "__main__":
    import json
    import sys

    for tok in tokenize(sys.stdin.read()):
        print(json.dumps(tok._asdict()))
`;
}

function cIdent(name, used) {
  const base = 'TOK_' + name.toUpperCase().replace(/[^A-Z0-9_]/g, '_');
  let id = base, n = 2;
  while (used.has(id)) id = `${base}_${n++}`;
  used.add(id);
  return id;
}

export function emitLexerC(lx) {
  const used = new Set();
  const enums = lx.rules.map(r => cIdent(r.name, used));
  const type = lx.nStates > 32767 || lx.nClasses > 32767 ? 'int' : 'short';
  return `${header(lx, '/*', 'c')}
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>

enum token_type {
${enums.map((e, i) => `    ${e} = ${i},`).join('\n')}
    TOKEN_TYPE_COUNT
};

static const char *const TOKEN_NAMES[] = {
${rows(lx.rules.map(r => JSON.stringify(r.name)), '    ')}
};
static const unsigned char SKIP[] = {
${rows(lx.rules.map(r => (r.skip ? 1 : 0)), '    ')}
};
#define N_CLASSES ${lx.nClasses}
/* Character class of each ASCII byte; -1 where no rule can read it. */
static const ${type} CLASS_OF[128] = {
${rows(asciiClasses(lx), '    ')}
};
/* TRANS[state * N_CLASSES + cls] is the next state, or -1. */
static const ${type} TRANS[] = {
${rows([...lx.trans], '    ')}
};
/* ACCEPT[state] is the rule it accepts, or -1. */
static const ${type} ACCEPT[] = {
${rows([...lx.accept], '    ')}
};

typedef struct {
    const char *src;
    size_t len, pos;
    int line, col;
} lexer;

typedef struct {
    enum token_type type;
    const char *text; /* points into the source; not NUL-terminated */
    size_t len;
    int line, col;
} token;

void lexer_init(lexer *lx, const char *src, size_t len) {
    lx->src = src; lx->len = len; lx->pos = 0; lx->line = 1; lx->col = 1;
}

const char *token_name(enum token_type t) { return TOKEN_NAMES[t]; }

/* 1: a token was read into *out. 0: end of input.
   -1: no rule matches at lx->pos (line lx->line, column lx->col). */
int lexer_next(lexer *lx, token *out) {
    while (lx->pos < lx->len) {
        int state = ${lx.start}, last_rule = -1;
        size_t last_end = lx->pos;
        for (size_t i = lx->pos; i < lx->len; i++) {
            unsigned char c = (unsigned char)lx->src[i];
            int k = c < 128 ? CLASS_OF[c] : -1;
            if (k < 0) break;
            state = TRANS[state * N_CLASSES + k];
            if (state < 0) break;
            if (ACCEPT[state] >= 0) { last_rule = ACCEPT[state]; last_end = i + 1; }
        }
        if (last_rule < 0) return -1;
        out->type = (enum token_type)last_rule;
        out->text = lx->src + lx->pos;
        out->len = last_end - lx->pos;
        out->line = lx->line;
        out->col = lx->col;
        for (size_t i = lx->pos; i < last_end; i++) {
            if (lx->src[i] == '\\n') { lx->line++; lx->col = 1; } else lx->col++;
        }
        lx->pos = last_end;
        if (!SKIP[last_rule]) return 1;
    }
    return 0;
}

#ifdef LEXER_MAIN
/* cc -DLEXER_MAIN lexer.c && ./a.out < input.txt */
int main(void) {
    size_t cap = 1 << 16, len = 0, n;
    char *buf = malloc(cap);
    while (buf && (n = fread(buf + len, 1, cap - len, stdin)) > 0) {
        len += n;
        if (len == cap) buf = realloc(buf, cap *= 2);
    }
    if (!buf) return 2;
    lexer lx;
    token t;
    int r;
    lexer_init(&lx, buf, len);
    while ((r = lexer_next(&lx, &t)) == 1)
        printf("%d:%d %s %.*s\\n", t.line, t.col, token_name(t.type), (int)t.len, t.text);
    if (r < 0) fprintf(stderr, "unexpected character at line %d, column %d\\n", lx.line, lx.col);
    free(buf);
    return r < 0;
}
#endif
`;
}

export const LEXER_EMITTERS = {
  js: { ext: 'js', mime: 'text/javascript', emit: emitLexerJS },
  py: { ext: 'py', mime: 'text/x-python', emit: emitLexerPython },
  c: { ext: 'c', mime: 'text/x-csrc', emit: emitLexerC }
};
