// npm run cli:docs → docs/cli-reference.md, from the commands' own help.
//
// The reference is generated, not written, so it cannot drift from what
// `automata <command> --help` prints: the usage text lives in each command's
// module, the examples and topics in help.mjs, and this only lays them out as
// Markdown. tests/cli.test.js fails when the committed file is stale, the way
// the repo treats its other committed outputs (glyphs, icons, wasm).
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

export async function referenceMarkdown() {
  process.env.NO_COLOR = '1';
  await import('./env.mjs');
  const { COMMANDS, GROUPS } = await import('./main.mjs');
  const { EXAMPLES, SEE_ALSO, TOPICS } = await import('./help.mjs');
  const mods = new Map();
  const usageOf = async name => {
    const file = COMMANDS[name][0];
    if (!mods.has(file)) mods.set(file, await import(`./commands/${file}.mjs`));
    return mods.get(file).commands[name].usage;
  };
  const anchor = s => s.toLowerCase().replace(/[^a-z0-9 -]/g, '').replace(/ /g, '-');
  const out = [
    '# `automata` command reference',
    '',
    '<!-- Generated by `npm run cli:docs` from each command\'s --help. Do not edit by hand:',
    '     change the usage text in cli/commands/*.mjs or the examples in cli/help.mjs. -->',
    '',
    'Every command, as `automata <command> --help` prints it. For a guided tour see [cli.md](cli.md).',
    '',
    '## Contents',
    ''
  ];
  for (const [title, names] of GROUPS) out.push(`- **${title}:** ${names.map(n => `[\`${n}\`](#${anchor(n)})`).join(' · ')}`);
  out.push(`- **Topics:** ${Object.keys(TOPICS).map(t => `[${t}](#topic-${t})`).join(' · ')}`, '');
  for (const [title, names] of GROUPS) {
    out.push(`## ${title}`, '');
    for (const name of names) {
      out.push(`### ${name}`, '', COMMANDS[name][1] + '.', '', '```text', await usageOf(name), '```', '');
      const ex = EXAMPLES[name] || [];
      if (ex.length) {
        out.push('**Examples**', '', '```sh');
        for (const [cmd, what] of ex) out.push(`# ${what}`, cmd);
        out.push('```', '');
      }
      const see = SEE_ALSO[name] || [];
      if (see.length) out.push(`See also: ${see.map(s => (s.startsWith('help ') ? `[${s}](#topic-${s.slice(5)})` : `[\`${s}\`](#${anchor(s)})`)).join(', ')}.`, '');
    }
  }
  out.push('## Topics', '');
  for (const [name, t] of Object.entries(TOPICS)) {
    out.push(`<a id="topic-${name}"></a>`, `### ${name}`, '', `_${t.summary}_ — \`automata help ${name}\``, '', '```text', t.text.replace(/^\n/, ''), '```', '');
  }
  return out.join('\n').replace(/\n{3,}/g, '\n\n');
}

// ── The guide's output blocks ─────────────────────────────────────
// docs/cli.md shows what commands print, not just the commands. Each such
// block is marked
//
//   <!-- automata-output: info div5.automaton -->
//   ```text
//   …
//   ```
//
// and filled with what `automata info div5.automaton` prints, run in a scratch
// copy of examples/cli/ — the files the guide tells a reader to cd into, so a
// block that writes a file cannot touch them — with colour off. The arguments
// are split the way a shell would split them, quotes and all, and no shell is
// involved, so a block reads the same on every platform. Only commands whose
// output does not change from run to run belong in a block: no timings, no
// randomness without --seed, no paths joined by the platform's separator.

const GUIDE = new URL('../docs/cli.md', import.meta.url);
const MARK = /(<!-- automata-output: (.+?) -->\r?\n```text\r?\n)[\s\S]*?(```)/g;

/** A command line split into words: quotes group, and "" is an empty word. */
export function shellWords(line) {
  const words = [];
  let word = null, quote = null;
  for (const ch of line) {
    if (quote) {
      if (ch === quote) quote = null; else word += ch;
    } else if (ch === '"' || ch === "'") {
      quote = ch;
      word ??= '';
    } else if (/\s/.test(ch)) {
      if (word !== null) words.push(word);
      word = null;
    } else word = (word ?? '') + ch;
  }
  if (word !== null) words.push(word);
  return words;
}

/** The guide with every output block run afresh. */
export async function guideMarkdown(text) {
  const { cpSync, mkdtempSync, rmSync } = await import('node:fs');
  const { spawnSync } = await import('node:child_process');
  const { tmpdir } = await import('node:os');
  const { join } = await import('node:path');
  const dir = mkdtempSync(join(tmpdir(), 'automata-guide-'));
  cpSync(fileURLToPath(new URL('../examples/cli/', import.meta.url)), dir, { recursive: true });
  const cli = fileURLToPath(new URL('./automata.mjs', import.meta.url));
  const env = { ...process.env, NO_COLOR: '1' };
  delete env.FORCE_COLOR;
  try {
    const blocks = [...text.matchAll(MARK)];
    let out = '', at = 0;
    for (const m of blocks) {
      const r = spawnSync(process.execPath, [cli, ...shellWords(m[2])], { cwd: dir, env, encoding: 'utf8', timeout: 120000 });
      const said = [r.stdout, r.stderr].filter(Boolean).join('').replace(/\r\n/g, '\n').split('\n').map(l => l.trimEnd()).join('\n').trimEnd();
      out += text.slice(at, m.index) + m[1] + `$ automata ${m[2]}\n${said}\n` + m[3];
      at = m.index + m[0].length;
    }
    return out + text.slice(at);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

export async function guideFresh() {
  const { readFileSync } = await import('node:fs');
  const committed = readFileSync(GUIDE, 'utf8').replace(/\r\n/g, '\n');
  return { committed, fresh: await guideMarkdown(committed) };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const md = await referenceMarkdown();
  writeFileSync(new URL('../docs/cli-reference.md', import.meta.url), md);
  process.stdout.write(`docs/cli-reference.md: ${md.split('\n').length} lines\n`);
  const { fresh } = await guideFresh();
  writeFileSync(GUIDE, fresh);
  process.stdout.write(`docs/cli.md: ${[...fresh.matchAll(MARK)].length} output blocks run\n`);
}
