// npm run cli:docs → docs/cli-reference.md, from the commands' own help.
//
// The reference is generated, not written, so it cannot drift from what
// `automata <command> --help` prints: the usage text lives in each command's
// module, the examples and topics in help.mjs, and this only lays them out as
// Markdown. tests/cli.test.js fails when the committed file is stale, the way
// the repo treats its other committed outputs (glyphs, icons, wasm).
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

export async function referenceMarkdown() {
  process.env.NO_COLOR = '1';
  await import('./env.mjs');
  const { COMMANDS, GROUPS } = await import('./main.mjs');
  const { EXAMPLES, SEE_ALSO, TOPICS } = await import('./help.mjs');
  const mods = new Map();
  const usageOf = async name => {
    const file = COMMANDS[name][0];
    if (!mods.has(file)) mods.set(file, await import(`./commands/${file}.mjs`));
    return mods.get(file).commands[name].usage;
  };
  const anchor = s => s.toLowerCase().replace(/[^a-z0-9 -]/g, '').replace(/ /g, '-');
  const out = [
    '# `automata` command reference',
    '',
    '<!-- Generated by `npm run cli:docs` from each command\'s --help. Do not edit by hand:',
    '     change the usage text in cli/commands/*.mjs or the examples in cli/help.mjs. -->',
    '',
    'Every command, as `automata <command> --help` prints it. For a guided tour see [cli.md](cli.md).',
    '',
    '## Contents',
    ''
  ];
  for (const [title, names] of GROUPS) out.push(`- **${title}:** ${names.map(n => `[\`${n}\`](#${anchor(n)})`).join(' · ')}`);
  out.push(`- **Topics:** ${Object.keys(TOPICS).map(t => `[${t}](#topic-${t})`).join(' · ')}`, '');
  for (const [title, names] of GROUPS) {
    out.push(`## ${title}`, '');
    for (const name of names) {
      out.push(`### ${name}`, '', COMMANDS[name][1] + '.', '', '```text', await usageOf(name), '```', '');
      const ex = EXAMPLES[name] || [];
      if (ex.length) {
        out.push('**Examples**', '', '```sh');
        for (const [cmd, what] of ex) out.push(`# ${what}`, cmd);
        out.push('```', '');
      }
      const see = SEE_ALSO[name] || [];
      if (see.length) out.push(`See also: ${see.map(s => (s.startsWith('help ') ? `[${s}](#topic-${s.slice(5)})` : `[\`${s}\`](#${anchor(s)})`)).join(', ')}.`, '');
    }
  }
  out.push('## Topics', '');
  for (const [name, t] of Object.entries(TOPICS)) {
    out.push(`<a id="topic-${name}"></a>`, `### ${name}`, '', `_${t.summary}_ — \`automata help ${name}\``, '', '```text', t.text.replace(/^\n/, ''), '```', '');
  }
  return out.join('\n').replace(/\n{3,}/g, '\n\n');
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const md = await referenceMarkdown();
  writeFileSync(new URL('../docs/cli-reference.md', import.meta.url), md);
  process.stdout.write(`docs/cli-reference.md: ${md.split('\n').length} lines\n`);
}
