// Compiles wasm/label-penalty.ts and writes it into js/wasm/ as base64.
//
// Committed output, run by hand — the arrangement build-glyphs.mjs already
// uses, and for the same reason: the compiler is a development dependency and
// what ships is a small generated file.
//
// Base64 in a JS module rather than a .wasm file beside it, because the module
// has to instantiate *synchronously*. buildLayoutContext runs inside a frame
// and cannot await anything, so fetch/instantiateStreaming is not available to
// it; a module that is already in the bundle is. See js/label-wasm.js.
//
//   npm run wasm
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = join(root, 'wasm', 'label-penalty.ts');
const tmp = join(root, 'wasm', 'label-penalty.wasm');
const out = join(root, 'js', 'wasm', 'label-penalty-bytes.js');

// -O3z, and no runtime export: the module allocates its grids once and never
// frees, so a garbage collector would be dead weight in a size budget that
// matters — see the note in label-wasm.js about the 4KB synchronous limit.
execFileSync(process.execPath, [
  join(root, 'node_modules', 'assemblyscript', 'bin', 'asc.js'),
  src, '--outFile', tmp, '-O3z', '--runtime', 'stub', '--noAssert'
], { stdio: 'inherit' });

const bytes = readFileSync(tmp);
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, `// GENERATED by scripts/build-wasm.mjs from wasm/label-penalty.ts — do not edit.
// ${bytes.length} bytes of WebAssembly, base64. See js/label-wasm.js.
export const LABEL_PENALTY_WASM =
  '${bytes.toString('base64')}';
`);
console.log(`wasm ${bytes.length} bytes -> ${(bytes.length * 4 / 3 / 1024).toFixed(1)}KB base64`);
if (bytes.length >= 4096) {
  console.warn('\n  WARNING: past 4096 bytes, Chrome refuses synchronous compilation on the\n' +
               '  main thread and js/label-wasm.js will fall back to the JS path.\n');
}
